### ISSUE TITLE
security risk: need html.escape

### ISSUE THREAD

**Issue by boolbag** [flask-admin/flask-admin#1000]
When database fields contain html, at the moment the raw html is output in the list [edit: in the case of editable fields]. For instance, `<h1>hello</h1>` will be rendered in the browser as a heading (unlike how it is rendered in this sentence). 

![escape](https://cloud.githubusercontent.com/assets/7551671/9376865/be7c7a10-4766-11e5-943c-8fa42ffbe518.jpg)

In my view, this is not a desired behavior and a security risk: think of raw JS stored in the database and rendered, raw, in the browser.

It seems to me that the output of any database field should go through `html.escape` before hitting the browser. 

As a temporary fix, you can bypass this problem with `column_formatters`, but there is a [related issue](https://github.com/flask-admin/flask-admin/issues/1001) that I will post separately.

**Edit: about the free cruise grand prize...** Please let me know how to collect my prize for posting issues #1000 and #1001!

Congratulations for making it this far, and huge thanks for the mammoth effort to everyone involved.

**Comment by pawl** [comment]
I'm having trouble reproducing this in chrome: ![](https://i.imgur.com/NkFCQoV.png)

Using this gist: https://gist.github.com/pawl/a70fd8ff2094bf43c6fb

**Comment by boolbag** [comment]
@pawl 
That was fast!
But add this to your gist (commenting out your add_view line):

```
class CarAdmin(sqla.ModelView):
    column_editable_list = ('desc', )

# later...
# admin.add_view(sqla.ModelView(Car, db.session))
admin.add_view(CarAdmin(Car, db.session))
```

Scary results... Thanks for all the alerts! :)
