### ISSUE TITLE
flag for column_formatters: ignore_while_editing

### ISSUE THREAD

**Issue by boolbag** [flask-admin/flask-admin#1001]
_EDIT:_ now that @pawl has fixed issue #1000 there is no longer a need of `column_formatters` to prepare html fields, so this issue loses its urgency. 

Be that as it may, the text prepared via other `column_formatters` is the one used in direct edit mode (see the original post for an example). I'll leave it as a suggestion that in direct edit mode, by default the `column_formatters` shouldn't interfere with the text shown while editing. Leaving it to the `flask-admin` gods to follow up or close the issue as they deem best in their higher wisdom. :)

_Original Post:_

Related to the issue of [raw html rendered in the browser](https://github.com/flask-admin/flask-admin/issues/1000), the temporary fix of using `column_formatters` has an issue of its own. 

To escape html entities in database fields, I use this formatter:

```
column_formatters = dict(
     val=lambda v, c, m, val: html.escape(m.val),
                          )
```

This allows the html to display in the list without being rendered. However, if the field is editable in list view, when you click on the field, you get the escaped html. For instance, `<h1>` becomes `&lt;h1$gt;` in the edit box. If you accept the edit, the escaped html is stored in the database, modifying your original data in a way that is not always obvious to restore! 

To me, this seems like this is a bug. In contrast, the regular edit form lets you edit `<h1>` as is, and this is the correct behavior.

As a fix, we could use a flag in the `column_formatters` definition: something like 

```
column_formatters = dict(
     ignore_while_editing = True,
     val=lambda v, c, m, val: html.escape(m.val),
                          )
```

`ignore_while_editing` should probably be `True` by default.

**Comment by petrus-jvrensburg** [comment]
Closing this, but please re-open if it's still a problem.
