### ISSUE TITLE
Cannot Delete Rows

### ISSUE THREAD

**Issue by boolbag** [flask-admin/flask-admin#1004]
On some tables, it's impossible to delete rows, which cripples the admin.

This originally cropped up with a MySQL database and a whole lot more related tables, but I reduced it to a [simple gist](https://gist.github.com/boolbag/9de8f3af7f31ce556791) with sqlite and the issue is the same. 

Head to the [Subscription Tab](http://127.0.0.1:5000/admin/subscription/) and try to delete Joe's subscription to time: this error message pops up.
![delete_joe](https://cloud.githubusercontent.com/assets/7551671/9401928/b8d15f8a-482a-11e5-9101-e8786c959b93.jpg)

Outside of flask-admin, I can delete the row without complaints from the two databases I've tried this with (sqlite, MySQL).

**Comment by pawl** [comment]
It says ```NOT NULL constraint failed```. If you remove ```nullable=False``` here then it will work:  https://gist.github.com/boolbag/9de8f3af7f31ce556791#file-cant_delete-py-L65

You can also reproduce the error by deleting the a record like this: https://gist.github.com/pawl/e995f091dafeb7b59ca6#file-cant_delete-py-L110

**Comment by boolbag** [comment]
@pawl Thanks for your message, but I don't see why I should have to remove `nullable=False`, which is a valid requirement for a database field. When you set a `NOT NULL` field in a database, it means that the field must have a value (an empty string is an acceptable value), as opposed to `NULL`. 

This has nothing to do with deleting rows, and in fact you can issue SQL to delete these rows. The database has no problem with the regular `DELETE` SQL, it only has problems with whatever crazy SQL is issued when you click the delete icon. 

This is a bug, I don't think it should be closed.

**Comment by boolbag** [comment]
@pawl Expanding on this point, if you add these two lines after the last commit of my gist:
```
    db.session.execute("DELETE from subscription WHERE subid = 1")
    db.session.commit()
```

You will see that the database is happy to delete Joe's subscription to TIme.
It's the delete button that doesn't work.

Please reopen the issue.

**Comment by pawl** [comment]
This same thing will happen even without Flask-Admin. Try this example: https://gist.github.com/pawl/14e6ca2dcdf0435925af

That example is just doing ```db.session.delete(model)``` and committing just like the delete button in Flask-Admin does: https://github.com/flask-admin/flask-admin/blob/master/flask_admin/contrib/sqla/view.py#L1037

It's not a Flask-Admin problem. It probably has something to do with how SQLAlchemy implements ```ondelete="CASCADE"```

**Comment by boolbag** [comment]
@pawl 
Thank you very much for digging up and explaining the source of the problem! So it's SQLA then... Maybe one of the reasons some say ORMs are an antipattern. :)

Although I'm at home in Python, flask-admin is new to me, as is SQLA (so used to working directly with the database). I'm excited to learn flask-admin because writing interfaces gets really tiring.

If I can ask what you may see as a rather trivial question, do you happen to know how I can get the row's table name (`__tablename__`) in an extended `list.html` template? For instance, I see that I can get the row number using `get_pk_value(row)`. If I knew how to access the table name, I could start adding buttons to build new functionality --- perhaps starting with a different delete button. Thank you in advance for any insights you have time to share.

**Comment by boolbag** [comment]
@pawl 
Finally got it working. Deleting rows is a really important function, so thought I'd post a [gist showing the solution](https://gist.github.com/boolbag/a166b40512d47d42aea2). 

- The solution is explained on this [SO post](http://stackoverflow.com/questions/5033547/sqlachemy-cascade-delete). 
- Instead of defining the relationship inside the child class, you define it inside the parent class, specifying `cascade="all,delete"`
- The relevant line is line 55: `subscriptionschedule = relationship("SubscriptionSchedule", cascade="all,delete", backref="subscription")`
