### ISSUE TITLE
Issue with Not-Nullable text fields: forms don't let you leave them empty

### ISSUE THREAD

**Issue by boolbag** [flask-admin/flask-admin#1011]
This will sound similar to [#1003](https://github.com/flask-admin/flask-admin/issues/1003), but the latter had to do with nullable fields, while this issue has to do with not-nullable fields.

For databases, `NULL` is not the same as an empty string. There are benefits to having `NOT NULL` fields that default to an empty string, and it's quite a common practice. 

In [this gist](https://gist.github.com/boolbag/61ecf048b7f08964b956), some rows are successfully created that have `NOT NULL` fields populated with empty strings. For variety, for the `nickname` field the empty string is explicitly provided, while for the `notes` name it is populated by the database because the default value is set.

Now if you click `edit` on one of the rows, you won't be able to leave `nickname` or `notes` as an empty string, even though they are already empty. Likewise, if you try to create a new record, you can not provide an empty string. 

This should be feasible for both fields, whether or not the default value is set to an empty string. 
If you feel the user should understand that an empty string will be created for this required field (marked with a red asterisk), maybe a greyed out `<empty string>` could appear in the form.

**Comment by boolbag** [comment]
For anyone who is not familiar with the common practice of `NOT NULL` fields with empty strings as default values, I have scanned this page from *High-Performance MySQL*, 3rd edition (a bible for MySQL).

![not-null](https://cloud.githubusercontent.com/assets/7551671/9422769/a2f542e4-48f7-11e5-8dff-2b02ea9e9ea9.png)

**Comment by pawl** [comment]
Looks like this pull request is related: #964

**Comment by boolbag** [comment]
Wow, yes, thanks, you are quite right! 

One difference is that #1013 focuses on the default value being an empty string. But `NOT NULL` fields should accept empty strings even if their default value is `Nicaragua`.

**Comment by boolbag** [comment]
@pawl Thank you you for the patch! Without testing extensively, when setting `server_default=text("''")`, your fix seems to be working perfectly. :)

Also, kudos to the rest of the flask-admin team on releasing 1.3! 
Would you say that the list of closed issues is the best place to look for a change log between 1.2 and 1.3? Are there some particular new features that stand out in your mind?

Many thanks, will keep exploring.

**Comment by pawl** [comment]
@boolbag I've been working on a presentation with details about the 1.3.0 release: http://imgur.com/a/7ui6P

mrjoes also put release notes here: https://github.com/flask-admin/flask-admin/releases

**Comment by boolbag** [comment]
Thank you @pawl ... That's terrific! :)
