### ISSUE TITLE
Issue with Inline Date

### ISSUE THREAD

**Issue by boolbag** [flask-admin/flask-admin#1018]
On [this gist](https://gist.github.com/boolbag/b8393294c5b3b7171eeb), clicking on the `Pet` tab, you will see the date of birth field `dob` filled in for one pet and empty for two others. 
- If you try to edit the date of birth for Jumbo by **clicking inline**, the year **1965** is not shown in the form, and it is not possible to scroll to a year before 1970.
- If you try to edit the two empty dob fields, you cannot pick a year before 1970.

**Comment by pawl** [comment]
Oops, added this comment to the wrong issue originally.

X-editable defaults to 1970 as the minimum date: http://vitalets.github.io/combodate/

I need to make a guide on how to override that part of the editable list view (and probably make it easier to override too): https://github.com/flask-admin/flask-admin/blob/master/flask_admin/model/widgets.py#L117

I think changing the default involves adding a line like: kwargs['data-minyear'] = '1900'

**Comment by pawl** [comment]
Looks like wtforms fails here on years before 1900 anyway (on python 2.7, because of limitations with strftime): https://github.com/wtforms/wtforms/blob/3f955152b64a75b1d8cebf35bc9761a7216f4abd/wtforms/fields/core.py#L729

It probably makes sense to set the default minimum year to 1900.

**Comment by boolbag** [comment]
@pawl Thank you for your suggestion! 

I tried changing the kwargs in that section with no success. Also tried above the `if` block in case `elif subfield.type == 'Select2Field':` was not the correct branch, but no luck. I tried with or without quotes, and tried other parameters as well: 
```
kwargs['data-minYear'] = '1950'
kwargs['data-yearDescending'] = 'False'
```
For some reason, these arguments don't seem to be read.

**Comment by pawl** [comment]
Here's the correct syntax: ```kwargs['data-combodate'] = '{"minYear": "1900"}'```

**Comment by boolbag** [comment]
@pawl 
You nailed it! 
It works perfectly at the top of `get_kwargs`.
Wow, all the other arguments are specified in the format you first outlined (for instance `kwargs['data-role'] = 'x-editable-boolean'`), so you're a hero for finding the magic format for this one.

Do you think this might be a sensible alteration to the default `widgets.py`?
If not, down the line, it would be nice to have a place to override the default so that updating `flask-admin` doesn't squash the tweak. 

Thank you for all your hard work on `flask-admin`. Excited to keep exploring it.
