### ISSUE TITLE
Issue with Inline Form Choices with Enum Field

### ISSUE THREAD

**Issue by boolbag** [flask-admin/flask-admin#1019]
In a database, it's normal not to know in what order `enum` fields are shown because they are sorted by their index value. However, using `form_choices`, it is possible to constrain the order of presentation of an `enum` field within the `CREATE` form.

Sadly, this is not working for inline editing. On [this gist](https://gist.github.com/boolbag/ec2bdd25ac5de0c12b63), if you try to edit the `favorite_day` field **inline**, you get a "random" order of days. In contrast, on the `CREATE` field, the options set in `form_choices` are respected.

**Comment by pawl** [comment]
X-editable defaults to 1970 as the minimum date: http://vitalets.github.io/combodate/

I need to make a guide on how to override that part of the editable list view (and probably make it easier to override too): https://github.com/flask-admin/flask-admin/blob/master/flask_admin/model/widgets.py#L117

I think changing the default involves adding a line like: ```kwargs['data-minyear'] = '1900'```
