### ISSUE TITLE
"Fork me on Github" Ribbon Blocking Docs On Mobile

### ISSUE THREAD

**Issue by pawl** [flask-admin/flask-admin#1024]
![](http://i.imgur.com/WilUadUm.png)

Reported here: https://www.reddit.com/r/Python/comments/3iawzj/whats_new_in_flaskadmin_130/cuez5rc

>Yeah this happens on my desktop pc too if I try to resize the browser. It's a CSS issue so it should be an easy fix. I found that it uses a different img class from a file called badge_only.css. This has the image width set to 100%. If you disable it somehow, it looks fine.

**Comment by petrus-jvrensburg** [comment]
Okay, let me check this out.
