### ISSUE TITLE
Validation errors from wtforms are not translated.

### ISSUE THREAD

**Issue by plaes** [flask-admin/flask-admin#1042]
Although flask-admin and its strings are properly localized, form validation errors from wtforms appear untranslated.

**Comment by pawl** [comment]
I tried using lazy_gettext, but that didn't work.

These links might help in figuring out the fix:
https://github.com/lepture/flask-wtf/blob/master/flask_wtf/i18n.py
https://github.com/lepture/flask-wtf/blob/8879e9827b0160776031bd06ef083b81282904e5/flask_wtf/form.py#L168
https://gist.github.com/satiani/7490106

**Comment by pawl** [comment]
I tried something similar to the solution here: https://gist.github.com/satiani/7490106

But, the problem with that solution is that it will no longer use WTForms's translations. So, non-custom validation errors like "This field is required." will show as english.

I think the easiest workaround for this will be using flask-wtf and overriding the base form in the modelview.

The permanent fix will probably be similar to this:
* https://github.com/lepture/flask-wtf/blob/8879e9827b0160776031bd06ef083b81282904e5/flask_wtf/form.py#L168
* https://github.com/lepture/flask-wtf/blob/master/flask_wtf/i18n.py

**Comment by ElLorans** [comment]
I get the same issue: flask-admin messages are translated, but default form validation errors from wtforms appear untranslated.
```
Flask-Admin==1.6.1
WTForms==3.0.1
Flask-WTF==1.1.1
flask-babel==3.1.0
Babel==2.12.1

```
