### ISSUE TITLE
validation disabled fields sqla

### ISSUE THREAD

**Issue by LevonXXL** [flask-admin/flask-admin#1043]
Hi. 

SQLA.

Just Assume ModelView used just for edit. 

form_widget_args = {
        'code': {'disabled': True},
        'created_at': {'disabled': True}
    }

code is Unique value. 

During editing POST event I receive validation error. 
1. Define field as disabled doesn't prevent from add validators into field attrs.
2. I should replace all validators in disabled fields

**Comment by pawl** [comment]
This should probably be something that's solved in WTForms. I created an issue for it here: https://github.com/wtforms/wtforms/issues/217

This is also worth reading: http://stackoverflow.com/a/16576294/1364191

"The correct approach with WTForms is to not have the field in the first place."
