### ISSUE TITLE
edit_modal = True doesn't work with form_edit_rules

### ISSUE THREAD

**Issue by kaldown** [flask-admin/flask-admin#1045]
This block don't work:
```
class MyModelView(ModelView)
    edit_modal = True
    form_edit_rules = [
        rules.FieldSet('name', 'date')
        ]
```
I should choose between modal and ruleset, both doesn't work.

**Comment by pawl** [comment]
Looks like adding ```{% set render_ctx = h.resolve_ctx() %}``` to the template fixes it.
