### ISSUE TITLE
Pre-filling fields in create view

### ISSUE THREAD

**Issue by jmagnusson** [flask-admin/flask-admin#1051]
It would be nice to be able to pre-configure the `create_view` endpoint by passing in GET parameters to it.

So this URL:
`http://mysite.dev/admin/productsku/?size=2&variant=3&season=1&season=2&ean_code=123456789`
Would produce something like this:
<img width="1001" alt="screen shot 2015-09-14 at 13 44 56" src="https://cloud.githubusercontent.com/assets/190835/9849007/f48bacd2-5ae6-11e5-8c8c-d8ae9825c3b8.png">

**Comment by rochacbruno** [comment]
:+1:

**Comment by mrjoes** [comment]
I'm not sure it is very safe to do so. Also, you can easily support it by overriding `get_create_form()` and passing values from `request`.

**Comment by rochacbruno** [comment]
@mrjoes So we can write an app to include in examples?

**Comment by mrjoes** [comment]
Ugh, examples folder will get really huge. Maybe some sort of recipe section on flask-admin.org would be better.

**Comment by jmagnusson** [comment]
Is safety really an issue? Not sure I follow.

**Comment by mrjoes** [comment]
Allows creating and distributing link to the app that'll have some non-safe values preselected even if defaults are totally safe.

**Comment by crzyhorse** [comment]
Since it seems that neither a code sample or a recipe section were added for this, and since I struggled with this, I thought I would post my solution.

`class MyModelView(ModelView):
     # override create form, not get_create_form as mentioned above. 
     def create_form(self):
         form = super(MyModelView, self).create_form()
         if ('variant') in request.args.keys():
             variant_query = self.session.query(Variant).filter(Variant.id = request.args['variant']).one()
             form.variant.query = [variant_query]
        if ('size') in request.args.keys():
             size_query = self.session.query(Size).filter(Size.id = request.args['size']).one()
             form.size.query = [size_query]
        return form `

Also, I'm using this to create action buttons to create entries for another view, with references to the previous view selected by default. If worried about non-safe values, just validate that the request arguments are in acceptable range before using them.

**Comment by rachmadaniHaryono** [comment]
another example

```python
class FilteredImageURLView(CustomModelView):
    """Custom view for Tag model."""

    def create_form(self):
        form = super().create_form()
        ImageUrl = models.ImageURL
        if ('img_id') in request.args.keys():
            img_url_m = self.session.query(ImageUrl).filter(ImageUrl.id == request.args['img_id']).one()  # NOQA
            form.img_url.data = img_url_m
        return form
```
the code form crzyhorse only limit the selection. this one set the default value on the form.

**Comment by GrenderG** [comment]
Hi all, although this is not 100% related to this issue, how can I achieve this?

![fadmin](https://user-images.githubusercontent.com/8654362/38277856-32e6f45e-379a-11e8-94b2-e55976b73964.PNG)

**Comment by petrus-jvrensburg** [comment]
Thanks @jmagnusson 

@crzyhorse & @rachmadaniHaryono Would you mind adding that to one of the existing examples? With a few comments to explain what's happening?

**Comment by jlelong** [comment]
For anyone coming here, I had to tweak https://github.com/flask-admin/flask-admin/issues/1051#issuecomment-372010195 a bit to make it work as updating the form data fails

```python
class FilteredImageURLView(CustomModelView):
    """Custom view for Tag model."""

    def create_form(self):
        ImageUrl = models.ImageURL
        if ('img_id') in request.args.keys():
            img_url_m = self.session.query(ImageUrl).filter(ImageUrl.id == request.args['img_id']).one()  # NOQA
            return super(imageURL).create_form(image_url_m)
        return super(imageURL).create_form()
```
