### ISSUE TITLE
Adding Custom Logic During row creation

### ISSUE THREAD

**Issue by okyere** [flask-admin/flask-admin#1055]
I'm new to this library so please forgive me if this is dumb. When I click 'Save' to create a new row for a model, I also want to do some custom things. In my case, I'll create a table dynamically whose name is the string entered in the form. This will be in addition to what flask-admin does for me i.e. add a new row to the model table. So where will I put the custom logic to do what I want to do? I saw this post on so: http://stackoverflow.com/questions/21140030/customize-override-flask-admins-submit-method-from-edit-view with Joe's answer about overriding on_model_change but I'll like some more explanation. From the docs, it says that on_model_change is called from update_model and create_model. When I click on the source link to the right, I get to: http://flask-admin.readthedocs.org/en/latest/_modules/flask_admin/model/base/#BaseModelView.create_model . It doesn't show the code. So I don't know how it is implemented.
Can someone please illustrate what I'm trying to in a simple sample code? Thanks.

**Comment by mrjoes** [comment]
If you need something very custom, don't use `ModelView` - start with `BaseView`, dumb form and custom logic to create tables.

Is there any reason you want to use `ModelView` for this task?

**Comment by okyere** [comment]
I have no particular reason. I'm just naive about all this and I'm trying to navigate my way through it. Do I have to define my own methods, etc if I subclass the BaseView?

**Comment by mrjoes** [comment]
Check Flask-Admin tutorial, it gives quick introduction into framework basics.

`ModelView` is used when you need CRUD interface for your models.
`BaseView` is foundation for everything and you can write your own custom stuff way you want.

Seems like `BaseView` would fit better in your case.

**Comment by okyere** [comment]
Thanks. I went through the documentation here: https://flask-admin.readthedocs.org/en/latest/ . Is that the one you're referring to? I see some information about BaseView here: https://flask-admin.readthedocs.org/en/latest/introduction/#adding-your-own-views . But in the subsection about "Overriding The Builtin Views", it subclassed ModelView.
