### ISSUE TITLE
Add picture thumnails in Select2TagsWidget

### ISSUE THREAD

**Issue by vcaen** [flask-admin/flask-admin#1058]
After numerous tries subclassing Select2TagsField and reading all the doc, I can't find a way to personalize the tags view in the Select2TagsField.

I want to display thumbnail of images in a Select2TagsWidget, but for now, the only things displayed into the tags is the String representation of my SqlAlchemy model `<app.models.Picture object at 0xXXXX>`

**Comment by petrus-jvrensburg** [comment]
Closing this now. But please re-open if it's still a problem.
