### ISSUE TITLE
How I can choose page size in model list view?

### ISSUE THREAD

**Issue by OleksandrLoboda** [flask-admin/flask-admin#1061]
What I must to do to have it?

**Comment by mrjoes** [comment]
Choose - as with dropdown?

You can change your template and pass page size as query string argument. Then add `page_size` property and return your query string argument.

**Comment by OleksandrLoboda** [comment]
I`m have own form for changing page_size and store page_size into user`s session.
But in changelogs for version 1.3.0 "Ability to choose page size in model list view"

**Comment by pawl** [comment]
@OleksandrLoboda Here's a gist with an example: https://gist.github.com/pawl/f6c0270d83241c31237a

You will need to enter a number in the form at http://127.0.0.1:5000/ to change the page size for your user. Then check out http://127.0.0.1:5000/admin/car/ to see the changes.

It looks like the pager isn't adjusting to the changes, that's a bug.

**Comment by pawl** [comment]
Just updated that gist to fix the pager. Unfortunately, it makes the example a lot longer because it requires overriding all of index_view.

Look for ```session.get('pagesize', 20)``` to see where the changes are.
