### ISSUE TITLE
Behavior of method on_model_change in InlineBaseFormAdmin is unclear

### ISSUE THREAD

**Issue by citizen-stig** [flask-admin/flask-admin#1074]
I've described the details in StackOverflow question http://stackoverflow.com/questions/33002393/flask-admin-catch-changes-on-inline-models

Briefly: this method called for all inline_models, not only for changed. 

Is it a bug, or there's way to get desired behavior

**Comment by mrjoes** [comment]
Yes, that's correct. Same as a `on_model_change` in a admin view. You can use SQLAlchemy change tracking machinery (http://stackoverflow.com/questions/28353048/determine-which-fields-are-dirty-on-an-sqlalchemy-object) if you want to track field individual changes.

**Comment by citizen-stig** [comment]
Thank you for pointing this out! I'll try it

**Comment by citizen-stig** [comment]
This solution doesn't work. all models in on_model_change looks like unchanged.

**Comment by citizen-stig** [comment]
Sorry, false alarm. Never use sqlite for db exepriments
