### ISSUE TITLE
Localization does not work for inline models

### ISSUE THREAD

**Issue by mapio** [flask-admin/flask-admin#1076]
Error messages for inline models are not translated according to the current locale.

This [gist](https://gist.github.com/b0b103c1cbbc5362d8a8) provides a slightly modified version of the [babel application](https://github.com/flask-admin/flask-admin/blob/master/examples/babel/app.py) reproducing the bug shown in the attached image where you can see french localization (menubar, buttons), but english error messages (red messages below non-validating fields).

![screen shot 2015-10-08 at 10 44 06](https://cloud.githubusercontent.com/assets/612826/10361676/ec3b9bd4-6da9-11e5-9881-4d58f82b8cf3.png)

**Comment by pawl** [comment]
I've got some ideas on how to fix this here: https://github.com/flask-admin/flask-admin/issues/1042#issuecomment-137870768

**Comment by pawl** [comment]
I got this fixed for Python 2 on my branch, but ran into some Python 3 issues: https://github.com/flask-admin/flask-admin/compare/flask-admin:master...pawl:fix_error_localization

My approach involved merging WTForms translations with Flask-Admin translations. But, Babel doesn't support merging translations in Python 3 yet: https://github.com/python-babel/babel/pull/92

Here's another approach I could try: https://github.com/lepture/flask-wtf/blob/master/flask_wtf/i18n.py

**Comment by ArthurPBressan** [comment]
Also, when adding inline models, the "New %model" isn't translated as well.

**Comment by pawl** [comment]
Looks like this is working now: 
![Example](https://i.imgur.com/8UO43nwm.png)
