### ISSUE TITLE
can_export not working for me

### ISSUE THREAD

**Issue by coreybrett** [flask-admin/flask-admin#1082]
I have code like...

```python
class Donations(ModelView):
    can_export = True

admin.add_view(
    Donations(
        m.Donation, 
        db.session,
        name = 'Donations',
        category = 'Donations'
    )
)
```

But a download button is not showing up anywhere.
I'm using Flask-Admin==1.3.0

**Comment by pawl** [comment]
The csv export hasn't made it into a release yet, you'll need to install flask-admin this way: ```pip install -e git+https://github.com/flask-admin/flask-admin.git@master#egg=flask-admin``` (or git clone from master and install it)

I think the docs page defaults to "latest" and that's what's on the master branch. We might need to make it default to the last release somehow.

**Comment by coreybrett** [comment]
Is there an ETA for the next release?

**Comment by jdejoode** [comment]
I pip installed using the link above (`pip install -e git+https://github.com/flask-admin/flask-admin.git@master#egg=flask-admin`)

but I get a 
      ~/.virtualenvs/clic/lib/python2.7/site-packages/werkzeug/routing.py", line 1678, in build
      raise BuildError(endpoint, values, method)
      BuildError: ('subset.export_csv', {}, None)

**Comment by jdejoode** [comment]
My mistake. Apparently I had to run `pip uninstall flask-admin` twice for it really clear out all of the previous files. Then ran the link above and it worked like a charm.

Great new feature.

When will it be released officially?
