### ISSUE TITLE
Use a “phrase search” in flask admin

### ISSUE THREAD

**Issue by jdejoode** [flask-admin/flask-admin#1090]
The docs show several options that can be used to search predefined fields. I want to allow my users to use quotation marks to do a phrase search. How can I do this with Flask-Admin?

**Comment by mrjoes** [comment]
Right now it is not supported, but you can override `_apply_search` method and handle quotes. https://github.com/flask-admin/flask-admin/blob/master/flask_admin/contrib/sqla/view.py#L804

**Comment by jdejoode** [comment]
@mrjoes That was what I was working on currently, but I wonder if there might be an easier solution. If I am right, it seems that the filter (when applied to a text column) does actually do a phrase search (rather than search for any of the terms). Is that possible? Or am I missing something?

**Comment by mrjoes** [comment]
No, same logic. Here's function that converts search term into `LIKE` argument: https://github.com/flask-admin/flask-admin/blob/master/flask_admin/contrib/sqla/tools.py#L10

**Comment by jdejoode** [comment]
@mrjoes At the risk of looking stupid, I disagree. That function simply handles ^ and =. The search splits that term into bits: https://github.com/flask-admin/flask-admin/blob/master/flask_admin/contrib/sqla/view.py#L808, but the filter does not, it simply takes the entire phrase without splitting it up on spaces: https://github.com/flask-admin/flask-admin/blob/master/flask_admin/contrib/sqla/filters.py#L54

This is a difference between the search and filter that could be accidental or purposeful. It helps me out in my case.

**Comment by mrjoes** [comment]
Ah, sorry. All I mean - same behavior in relation to quote and phrase handling. But filters don't break search string into words because they're more "precise" - they're filtering against single field and there's no need to handle "match model if all words present in any of the fields".

**Comment by jdejoode** [comment]
Indeed, that makes filters actually capable of phrase searches! Do you think it would be an added value for searches to include "phrase searches" as well? Could that be a useful feature?
