### ISSUE TITLE
Auto-complete filter (as with create form)

### ISSUE THREAD

**Issue by vToMy** [flask-admin/flask-admin#1091]
Suppose I have a model with a many-to-one relationship with another.
In the create form I have a choice input field in which I can select the model I want to connect.
How about adding this feature to filter? Currently I can only use filter with the relationship's columns, or id which is less helpful than having a nice choice input with indicative names like in the create form.

Since the code already exists, I wonder how difficult would it be to integrate it into the filters?

**Comment by ElvisTheKing** [comment]
+1

**Comment by petrus-jvrensburg** [comment]
I'm sure it would be useful. A PR would be welcome. Closing this in the meantime.
