### ISSUE TITLE
How can I filter on a field in a one-to-one relationship?

### ISSUE THREAD

**Issue by jdejoode** [flask-admin/flask-admin#1103]
I want to filter on Tag.owner, but I get the following exception:

     Exception: Invalid field Tag.owner: does not contains any columns.

How can I filter on a field of a one-to-one relationship?

View:

    class SubsetModelView(PhraseSearchModelView):
    column_filters = ('book', 'abbr', 'kind', 'corpus', 'text', 'notes', 'tags', Tag.owner)
    column_searchable_list = ('abbr', 'text',)
    column_list = ('book', 'kind', 'text', 'tags', 'notes')

Models: (indenting got messed up)

    class Tag(db.Model):
    __tablename__ = 'tags'
    __table_args__ = {'extend_existing': True}

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)  

    subset = db.relationship('Subset', secondary=subset_tags, backref=db.backref('tags'))
    # one to one relationship:
    owner_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    owner = db.relationship("User", backref=db.backref("tags", uselist=False))

    def __init__(self, name='', owner=None):
        self.name = name
        self.owner = owner

    def __repr__(self):
        # return 'Tag: ' + str(self.name) + '>'
        if self.owner:
            output = str(self.owner.name) + '-' + self.name
            return output
        return self.name

    class User(db.Model, UserMixin):
    __table_args__ = {'extend_existing': True}

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(35), unique=True)
    email = db.Column(db.String(255), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean())
    confirmed_at = db.Column(db.DateTime())

**Comment by mrjoes** [comment]
You can't filter on a relationship, but you can filter on related model column.

Try filtering on `tags.name`. It should detect that tags is a relationship and will create inner join between models, etc.

**Comment by jdejoode** [comment]
I can't believe I did not spot that. So for others like me: you can use 'tags.owner.name', in my example, to add a filter on a related model column. I tried that but I did not spot I needed the quotation marks.

Thanks Serge!
