### ISSUE TITLE
Accessing current_user in form?

### ISSUE THREAD

**Issue by jdejoode** [flask-admin/flask-admin#1104]
I have an app that allows users to add tags to a model. How can I add the current_user to the form so that tags are not anonymous, but are linked to the user that is logged in?

**Comment by mrjoes** [comment]
Flask-Login automatically adds `current_user` to all Jinja2 contexts. So this would work: `{% if current_user.is_authenticated() %}`.

**Comment by jdejoode** [comment]
Thanks. I am not accustomed enough with flask-admin just yet to do this. Can you give me an example of what an override of edit_form with custom choices would look like?

And the same for on_model_change?

Best

**Comment by jdejoode** [comment]
I have tried to take solve this issue, but I am running into a validation error. Any help is really welcome as I'm stuck and facing deadlines:

    class SubsetModelView(PhraseSearchModelView):
    column_filters = ('book', 'abbr', 'kind', 'corpus', 'text', 'notes', 'tags', 'tags.owner.name', 'tags.owner.email')
    column_searchable_list = ('abbr', 'text',)
    column_list = ('book', 'kind', 'text', 'tags', 'notes')
    # column_list = ('book', 'text',)
    # column_exclude_list = ['abbr','corpus']
    # column_editable_list could work with the above code included, but not great
    # column_editable_list = ['tags', 'notes']
    column_hide_backrefs = False
    named_filter_urls = True

    # editing
    edit_modal = True
    form_excluded_columns = ['book', 'abbr', 'kind', 'corpus', 'text']
    # inline_models = (Tag, Note)

    # can_view_details = True
    can_create = False
    can_delete = False  # disable model deletion
    can_edit = True  # TODO disable editable fields
    can_export = True  # FIXME
    export_max_rows = 2000

    page_size = 50  # the number of entries to display on the list view

    def is_accessible(self):
        return current_user.has_role('can_annotate')

    def edit_form(self, obj, *args, **kwargs):

        class SubsetEditForm(BaseForm):
            # from flask_admin.form.fields import Select2Field
            user_specific_tags =  [(tag.id, tag.name) for tag in Tag.query.filter_by(owner=current_user).all()]
            tags = SelectField('Tags', choices=user_specific_tags )
            # first_name = StringField('Username', current_user.name)

        form = SubsetEditForm(obj=obj)
        # return super(SubsetModelView, self).edit_form(form=form, *args, **kwargs)
        return form

**Comment by mrjoes** [comment]
Just validation error, no text message?

**Comment by mrjoes** [comment]
Try following, add `coerce=int` as an argument to `SelectField`. Or make wrap `tag.id` with `unicode`. In python '123' != 123 and your model ID is a number.

**Comment by jdejoode** [comment]
Yes only a validation error: "Not a valid choice". 

 Nor `coerce=int`, nor `unicode(tag.id)` worked. Any other suggestions?

**Comment by mrjoes** [comment]
SelectField will fail with "Not a valid choice" only if key that's set from the client does not match any of the available choices.

`coerce` forces SelectField to change type for the incoming data (just because everything that's sent by a  browser is a text).

So two options:
- different data types
- query returns different values

**Comment by jdejoode** [comment]
Makes sense. So how does my modelview now what model to look at (in this case, the Tag model)? 

When I print the tags field I get `<UnboundField(SelectField, ('Tags',), {'coerce': <type 'int'>, 'choices': [(10, u'politeness')]})>` based on the following code:

    def edit_form(self, obj, *args, **kwargs):

       class SubsetEditForm(BaseForm):
            user_specific_tags =  [(tag.id, tag.name) for tag in Tag.query.filter_by(owner=current_user).all()]
            tags = SelectField('Tags', choices=user_specific_tags, coerce=int)
            print tags

        form = SubsetEditForm(obj=obj)
        return form

I checked psql directly and I do have a tag with id `10`. So that seems correct.

**Comment by jdejoode** [comment]
Building on one of your own code snippets, this worked:


    def edit_form(self, obj):
        return self._use_filtered_tags(super(SubsetModelView, self).edit_form(obj))

    # Logic
    def _use_filtered_tags(self, form):
        form.tags.query_factory = self._get_tags_list
        return form

    def _get_tags_list(self):
        return self.session.query(Tag).filter_by(owner=current_user).all()

**Comment by mrjoes** [comment]
That's another way to do it - yes. Make sure you override `create_form` too.
