### ISSUE TITLE
Feature Inquiry - Change History

### ISSUE THREAD

**Issue by ibushong** [flask-admin/flask-admin#1113]
Since flask_admin is inspired by Django's admin, I'm wondering if there is any plan/interest in implementing Django admin's model change history, which shows the CRUD history made to models/objects? Maybe this makes more sense as an add-on. Just wondering since IMO this is a very useful feature for admin interfaces used by multiple users ("Who changed this?")

**Comment by ix5** [comment]
You would have to have another model or database to track each modification. It would be quite an overhead, going into version control territory like git.

**Comment by jirikuncar** [comment]
You can achieve a lot with https://github.com/kvesteri/sqlalchemy-continuum if you are using SQLAlchemy as your backend. Cheers!

**Comment by mrjoes** [comment]
This is currently out of the scope of the project, but good idea anyway.

**Comment by ufo911** [comment]
Is this still out of scope ?

**Comment by POD666** [comment]
Out-of-the-box integration with [sqlalchemy-continuum](https://github.com/kvesteri/sqlalchemy-continuum) would be pretty cool.
