### ISSUE TITLE
Restore peewee support after incompatible changes

### ISSUE THREAD

**Issue by rudyryk** [flask-admin/flask-admin#1117]
Flask-Admin fails to run with latest release of peewee. Moreover, extra "internal" changes are introduced 
in development version: https://github.com/coleifer/peewee/commit/50c9c1dd24b7a4c48a396a9f5e88f3ea1647859a

Here's a quick fix:
https://github.com/rudyryk/flask-admin/commit/43232f2b4df54f87bd4b507f05d492503e71db06

I'd suggest to wait for the next peewee release before adding final update to Flask-Admin.

**Comment by pawl** [comment]
That fix looks good. Feel free to submit a pull request for it.

**Comment by rudyryk** [comment]
@pawl Sure! Thank you :)

**Comment by pawl** [comment]
@rudyryk Thanks again for your help on this one!
