### ISSUE TITLE
Allow using models with fields of reserved names

### ISSUE THREAD

**Issue by tuukkamustonen** [flask-admin/flask-admin#1128]
I have `meta` field in my model. Turns out it conflicts with an internal field in wtforms:

```
File "/home/musttu/Code/virtualenvs/csm/local/lib/python2.7/site-packages/wtforms/form.py", line 119, in process
    formdata = self.meta.wrap_formdata(self, formdata)
AttributeError: 'TextAreaField' object has no attribute 'wrap_formdata'
```

I could change the field name in database, but I'd rather not. It would be nice to have a workaround on this, maybe mapping the field name as something else in wtforms/Flask-Admin.

**Comment by tuukkamustonen** [comment]
Also 'key' field seems to be simply ignored in the UI.

**Comment by maxcountryman** [comment]
At the very least it seems like this should be documented. I think a more ideal solution is to handle this gracefully in the library, i.e. Flask-Admin shouldn't make assumptions about how columns are named.

**Comment by alanhamlett** [comment]
Related to wtforms/wtforms#311.

**Comment by jalessio** [comment]
@tuukkamustonen Were you able to find a workaround to get columns named `key` to show up in the UI? Do you know if it's flask-admin or WTForms that is causing it not to display? I had initially assumed that it was WTForms, since the `meta` field issue appears to be in that code base (wtforms/wtforms#311).

But, if you look at a PR (wtforms/wtforms#312) I don't see `key` on the list of "restricted attributes":
```
_restricted_attributes = [
    'data',
    'errors',
    'meta',
    'validate',
    'populate_obj',
]
```

Anyone have an idea where `key` is being dropped and/or have a quick workaround?

**Comment by jalessio** [comment]
Also related to #1179

**Comment by tuukkamustonen** [comment]
True, seems like I cannot reproduce the issue with `key` anymore. Either something has changed or I made a mistake earlier when testing.

Raising exception on reserved field names is a good thing to have, but better would be to support the conflicting field names somehow. Is it possible to mask/map these reserved field names into something else in wtforms (e.g. 'meta' -> 'meta_' or such)?

**Comment by jalessio** [comment]
I discovered that in my case, the db column `key` was a primary key and thus wasn't being shown in the list or forms by default. This is remedied by by either setting `column_display_pk = True` or manually setting the `list_columns` and `form_columns` on the view class like this:

```
class ProjectAdminView(ModelView):
    list_columns = ['name', 'namespace', 'key']
    form_columns = ['name', 'namespace', 'key']
```

In addition, I actually had two primary keys which is a special case as documented in [docs/advanced.rst](https://github.com/flask-admin/flask-admin/blob/master/doc/advanced.rst#using-different-database-backends)

> Flask-Admin has limited support for models with multiple primary keys. It only covers specific case when all but one primary keys are foreign keys to another model. For example, model inheritance following this convention.

**Comment by petrus-jvrensburg** [comment]
Closing this now. But please re-open if it's still a problem.

**Comment by ShipraShalini** [comment]
I want to use `flask-admin` for an existing table which has a column named `meta`. Is there any way to make this work?
