### ISSUE TITLE
Hiding hidden field labels?

### ISSUE THREAD

**Issue by i-aakopian** [flask-admin/flask-admin#1129]
I am trying to have a hidden field in my form so I can validate it's value on submission.

``` python
form_overrides = {
  'my_field': HiddenField,
}
```

However, the field does not show up after inspecting the HTML.

I add it to the form_rules like so:

``` python
form_rules = [rules.Field('my_field')]
```

The hidden value is successfully in my form, but the label for the hidden value is there.
Is there an easy way to have it be hidden as well? Or do I need to manually set

``` python
column_labels = {
  'my_field': ''
}
```

**Comment by jingz** [comment]
try
```python
form_overrides = dict(my_field=HiddenField(""))
```
