### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by mrjoes** [flask-admin/flask-admin#1132]
Going to release new version. Any major fixes pending or it is good to go? @pawl

**Comment by pawl** [comment]
@mrjoes Should be good to go. I'm not currently working on any fixes.

**Comment by immon** [comment]
could you also update translations? I fixed few at crowdin.com

**Comment by pawl** [comment]
@immon Done. Thanks for helping with translations!

**Comment by mrjoes** [comment]
Will try to get release this weekend + tackle m2m search problem. There were some changes related to joins, will see if I can get it working within current architecture.
