### ISSUE TITLE
Float positions cut at 2 decimals

### ISSUE THREAD

**Issue by ThomasLecocq** [flask-admin/flask-admin#1141]
I'm using flask-admin in conjuction with sqla to handle views on my database. 

flask-admin : 1.3.0
wtforms: 2.0.2

When adding floating point values, like a latitude or a longitude, I use to have at least 4 decimals (down to 10m location quality). Inserting in the database is OK, viewing the data in "table" format is OK, but when clicking the "edit" link, the form opens with only 2 decimals.

I think this https://github.com/flask-admin/flask-admin/blob/master/flask_admin/contrib/sqla/form.py#L328 line is doing a lot of damages, since it seems sqla `Float` only accepts `decimal_return_scale` as arg now. 
Changing
```python
places = getattr(column.type, 'scale', 2)
```
for
```python
places = getattr(column.type, 'decimal_return_scale', 2)
```
solves the issue.

**Comment by pawl** [comment]
These docs say `decimal_return_scales` is new in 0.9.0: http://docs.sqlalchemy.org/en/latest/core/type_basics.html#sqlalchemy.types.Float.params.decimal_return_scale

So we probably would need to make it fail over to using `scale` for backwards compatibilty.

Can you submit the pull request?

**Comment by ThomasLecocq** [comment]
Actually, looking at their documentation, it seems that the default value is 10 for `scale`, but in flask-admin & wtforms, it's 2.

On the other hand, if the "default value" is 10, why does `getattr(column.type, 'scale')` return `None` ? I don't get it...

I can make a PR for sure, but I'm not completely sure how you see the deprecation route here ?
