### ISSUE TITLE
Using a ModelView as index_view throws error

### ISSUE THREAD

**Issue by ix5** [flask-admin/flask-admin#1143]
If I initiate my admin class like this:
`admin = Admin(app, url='/admin', name='Admin', index_view=ModelView(Entry, db.session, url='/admin', endpoint='admin))`
I get an error saying
`
werkzeug.routing.BuildError: Could not build url for endpoint 'admin.static' with values ['filename', 'v']. Did you mean 'st.static' instead?
`

Subclassing AdminIndexView in the particular ModelView won't help.

From reading the [source code](https://github.com/flask-admin/flask-admin/blob/master/flask_admin/base.py#L439) I am none the wiser as to why this problem occurs, since I am initiating the blueprint registering in the same way(?).

I do not want to move my admin interface to the url root as suggested [here](http://stackoverflow.com/questions/28006335/flask-admin-override-default-view-with-a-modelview-class)

Looking at this [issue](https://github.com/flask-admin/flask-admin/issues/943), maybe the problem lies with named endpoints, but I think I am only using the default (`admin`).

I searched around and got to [this issue](https://github.com/flask-admin/flask-admin/issues/561), but both the `Admin` and `index_view` base urls match.

It seems weird that having anything other than an `AdminIndexView`(which, according to the documentation is supposed to only render a template?) suddenly breaks routing.

**Comment by daimon99** [comment]
hey, I meet the same problem too. Have you resolved the problem?
Also I want to use a ModelView as my index_view too.

**Comment by daimon99** [comment]
Refer to #580 , I have paste my code there.

**Comment by ix5** [comment]
Thank you for pointing me in the right direction!
Using the following ModelView and admin initiation I was able to fix this.
```
class MyModelView(ModelView):
   (...)
   def __init__(self, model, session, *args, **kwargs):
        super(MyModelView, self).__init__(model, session, *args, **kwargs)
        self.static_folder = 'static'
        self.endpoint = 'admin'
        self.name = 'Admin'

admin = Admin(
    app,
    name='Admin',
    template_mode='bootstrap3',
    index_view=MyModelView(
    TheModel, db.session,
    url='/admin'
    ),
)
```
The documentation makes this seem like an edge case, whereas a lot of users would expect their admin landing page to be a ModelView and not a BaseView.

**Comment by nurockplayer** [comment]
It doesn't work for me.
I stil get an error saying :
`werkzeug.routing.BuildError: Could not build url for endpoint 'admin.index'. Did you mean 'admin.index_view' instead?`


`
class DashboardModelView(ModelView):
    def __init__(self, model, session, *args, **kwargs):
    super(DashboardModelView, self).__init__(model, session, *args, **kwargs)
        self.static_folder = 'static'
        self.endpoint = 'admin'
        self.name = 'Dashboard'

admin.init_app(
        app,
        index_view=DashboardModelView(
            DashboardModel, session=db.session, url='/admin'
        ))
`
