### ISSUE TITLE
detail_view query and show foreign key values

### ISSUE THREAD

**Issue by Gnahceg** [flask-admin/flask-admin#1161]
I want to show and query foreign key values or other table's values in the details view.

How can I do?

Thanks :)

**Comment by pawl** [comment]
Example:
```
class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user = db.relationship(User, backref='posts')

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True)

    def __unicode__(self):
        return self.username or ''
```

If you were looking at the details view for the `Post` model, the `user` row would display `username` from the `User` model.

So, it's going to show whatever is returned by `def __unicode__(self):` in the foreign key's SQLA model.

Makes sense?

**Comment by Gnahceg** [comment]
Thank you very much!

Example:

    class Post(db.Model):
        id = db.Column(db.Integer, primary_key=True)
        user = db.relationship(User, backref='posts')

    class User(db.Model):
        id = db.Column(db.Integer, primary_key=True)
        username = db.Column(db.String(80), unique=True)
        address = db.Column(db.String(80), unique=True) 

    def __unicode__(self):
        return self.username or ' '

I want to show  `address` in the details view of `Post` model.
How can I do ?

Thanks:)

**Comment by pawl** [comment]
By changing `self.username` to `self.address` in `def __unicode__(self):`

Here's the updated example:
```
class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user = db.relationship(User, backref='posts')

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True)
    address = db.Column(db.String(80), unique=True) 

    def __unicode__(self):
        return self.address or ''
```
