### ISSUE TITLE
Reverse Proxy Between 2 Identical Web Heads. Slave does not get model changes

### ISSUE THREAD

**Issue by busturdust** [flask-admin/flask-admin#1166]
Hi All,

Let me start by saying Thanks for the great project! This is the first web application I've built targeting production, and flask and provided extensions have been tremendous!

I have a working Flask application in development. I am working on Windows (unfortunately) using Python 3.4 and deploying Using WAMP Server 2.5

The architecture design is such that there will be a gateway server (Let's Call Server A), and 2 web heads (Server B, Server C) 

Server A is an Apache Reverse Proxy. The only thing configured on apache is proxy-html.conf. This server does nothing but communicate with the web heads and respond to the client.

The proxy-html.conf excerpt is as follows. 

    Header add Set-Cookie "ROUTEID=.%{BALANCER_WORKER_ROUTE}e; path=/"     env=BALANCER_ROUTE_CHANGED

    <Proxy balancer://mycluster>
       BalancerMember http://100.113.248.52:8080 route=route1
       BalancerMember http://100.113.248.51:8080 route=route2
       ProxySet stickysession=ROUTEID
    </Proxy>
    ProxyPass / balancer://mycluster/

    <Location /balancer-manager>
    SetHandler balancer-manager
    Order Deny,Allow
    Allow from all
    </Location>

The 2 web servers are independently installed copies of the same flask application. And the databases are configured with MySQL replication. All writing from BOTH flask applications is to the Master, and all reading is from the Slave. 

However, When making a change to the records on one server through Flask - Admin, The changes, deletes, or inserts are not replicated to the alternate Admin console, even though both databases have been updated.

That is to say, change a value on Server B. It is Reflected on the Database on both Server B and Server C, but Server C's admin console does not display the update.

Restarting Apache synchs everything back.
If I use Server C's admin console for antyhing after the gap has been created, it will then get pushed the changes, but the changes I've just done on Server C, are not reflected to Server B's admin console.

I apologize if this is confusing, I seem to have backed myself into a corner here, I can't figure out why the databases are up to date, but only 1 admin console gets updated. Is this a plausible scenario? Am I configuring this poorly? Should I be doing something else? 

Is there anyway to send a signal out that wlll update all admin consoles whether or not the update is handled on Server B or C?

Thanks, I will provide some excerpt code around my admin console. If any more information is required please ask and I will post it.

Excerpt Code

```python
class RoutingSession(Session):
    def get_bind(self, mapper=None, clause=None):
        if self._flushing:
            return engines['edit_leader']
        else:
            return engines['edit_follower']


session_factory = sessionmaker(class_=RoutingSession, autocommit=False)
#session_factory = sessionmaker(bind=edit_engine)
Session = scoped_session(session_factory)


@contextmanager
def session_scope():
    """Provide a transactional scope around a series of operations."""
    session = Session()
    try:
        yield session
        session.commit()
    except:
        session.rollback()
        raise
    finally:
        Session.remove()


app = Flask(__name__, static_folder=APP_STATIC, template_folder=APP_TEMPLATE)
# **
# Configure Application
app.config['SECRET_KEY'] = '34523453343230'
app.config['LOG_FILE'] = 'mmserver.log'
if not app.debug:
    import logging
    from logging import FileHandler
    file_handler = FileHandler(app.config['LOG_FILE'])
    file_handler.setLevel(logging.WARNING)
    app.logger.addHandler(file_handler)


# ~~~~~~~~~~~~~~~ ADMIN VIEW SECTION ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

class MyAdminIndexView(flask_admin.AdminIndexView):

    @expose('/')
    def index(self):
        if not current_user.is_authenticated:
            return redirect(url_for('mmserver'))
        return super(MyAdminIndexView, self).index()

# Add Admin Console Views
admin = flask_admin.Admin(app, 'Admin Center', index_view=MyAdminIndexView(),
                          base_template='admin/my_master.html')

with session_scope() as temp_session:
    admin.add_view(my_admin.ComputerAdmin(Computer, temp_session))
    admin.add_view(my_admin.DriveAdmin(Drive, temp_session))
    admin.add_view(my_admin.RoomAdmin(Room, temp_session))
    admin.add_view(my_admin.WorkgroupAdmin(Workgroup, temp_session))
    admin.add_view(my_admin.UserAdmin(User, temp_session))
    admin.add_view(my_admin.PhoneCategoryAdmin(PhoneCategory, temp_session))
    admin.add_view(my_admin.RoomExtensionAdmin(RoomPhoneNumber, temp_session))
    admin.add_view(my_admin.PhoneNumberAdmin(PhoneNumber, temp_session))
    admin.add_view(my_admin.RoomIntercomAdmin(RoomIntercomNumber, temp_session))
    admin.add_view(my_admin.StationTypeAdmin(StationType, temp_session))


# ~~~~~~~~~~~~~~~ END ADMIN VIEW SECTION ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# ~~~~~~~~~~~~~~~ Start Login SECTION ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# Login
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'login'


@app.teardown_appcontext
def shutdown_session(exception=None):
    Session.remove()

```

Left Most ID line is the Database of the Slave. 2nd Column is Admin of the slave. 3rd column is admin of the master. input ID = 19 form Master. Slave DB gets update, Slave Admin Console Does not.

![image](https://cloud.githubusercontent.com/assets/16565049/12127177/b8b6d26e-b3c3-11e5-8baa-78149fa304f0.png)

stackoverflow question : http://stackoverflow.com/questions/34615938/flask-admin-routing-session-load-balancing-data-replication-slave-does-not

**Comment by mrjoes** [comment]
Probably has something to do with MySQL and/or SQLAlchemy.

Flask-Admin runs generic query to get list of models using SQLAlchemy. There's no caching, it shows whatever is returned by the ORM. 

Try following: see if you can reproduce issue without Flask-Admin - just run a SQLAlchemy query against slave and see if data is there

**Comment by busturdust** [comment]
@mrjoes  Thanks for the Response... I tested the scenario out with python shell and standard SQLAlchemy. After entering a record in the Master. I can see it in Both Databases However SQLAlchemy from the shell Does not see the Database change until a COMMIT is issued (even though the the data is already there). After commit, the session receives the updated data.


Is there a different isolation level I should be using?. Is there a way to override Flask-Admin's get request for the Model so that I can ensure that the session receives the correct data on each request?

**Comment by mrjoes** [comment]
Flask-Admin does `commit` after model creation or change. So transaction is certainly committed to the master.

Not sure how to help, but try asking in SQAlchemy mailing list with simple SQLAlchemy-only gist (without Flask-Admin).

**Comment by busturdust** [comment]
@mrjoes  Your debugging advice appears to have guided me in a direction.

```
engines = {
    'edit_leader': create_engine(connection_string, echo=False, pool_size=20, max_overflow=100, logging_name='leader'),
    'edit_follower': create_engine('mysql+pymysql://admin:nbc5dps@100.113.248.51/nydps2', logging_name='follower',
                                   isolation_level='READ COMMITTED')
}


# Used for Managing Master - Slave MySQL Replication.
# Write to master, Read from Slave

class RoutingSession(Session):
    def get_bind(self, mapper=None, clause=None):
        if self._flushing:
            return engines['edit_leader']
        else:
            return engines['edit_follower']
```


Setting explicit isolation level of ``` READ COMMITTED ``` for the READ ONLY SLAVE. Appears to have worked. Further testing is required, but it is promising so far
