### ISSUE TITLE
Two views use one model 

### ISSUE THREAD

**Issue by Gnahceg** [flask-admin/flask-admin#1167]
Example:

    class Workflow(db.Model):
        id = db.Column(db.Integer, primary_key=True)
        service_id = db.Column(db.Integer, db.ForeignKey('service.id'))       
        service = db.relationship('Service', backref='workflow', uselist=False)

    admin.add_view(WorkFlowView(Workflow, db.session))
    admin.add_view(AdminFlowView(Workflow, db.session))

I want to add two views use one model.

`AssertionError: A blueprint's name collision occurred between <flask.blueprints.Blueprint object at 0x107e88d90> and <flask.blueprints.Blueprint object at 0x107e69b50>.  Both share the same name "workflow".  Blueprints that are created on the fly need unique names.`

What can I do to solve this?

Thanks :)

**Comment by mrjoes** [comment]
Pass `endpoint='someotherendpoint'` to the second view constructor. Change value to suit your needs.

See here:

**Comment by Gnahceg** [comment]
I can't see the `See here:` content, have you write it?

**Comment by halcyonjuly7** [comment]
@Gnahceg if you haven't solved this yet but im pretty you already have

what @mrjoes meant is:

```python
admin.add_view(WorkFlowView(Workflow, db.session, endpoint="some_endpoint"))
admin.add_view(AdminFlowView(Workflow, db.session, endpoint="some_other_endpoint"))
```

adding the `endpoint` argument creates a separate `blueprint` name other than the default name

**Comment by Gnahceg** [comment]
@halcyonjuly7 
Thanks :) 
I have solved it.
