### ISSUE TITLE
SQLA - form_columns does not allow '<relation>.<column name in related model>'

### ISSUE THREAD

**Issue by pawl** [flask-admin/flask-admin#1176]
See comment here: https://github.com/flask-admin/flask-admin/pull/1174#issuecomment-172404695

form_columns doesn't allow specifying a column in a related model in the same way as column_list, column_filters, column_sortable_list (`'<relation>.<column name in related model>'`)

It gives the following error message: `ValueError: Invalid model property name <class '__main__.Tyre'>.car.desc`

The fix might require using `rec_getattr` in tools.py.

**Comment by mrjoes** [comment]
No, can't use rec_getattr, as getting SQLAlchemy relation path is much more complicated than that.

On other hand, there's helper that you can use: https://github.com/flask-admin/flask-admin/blob/master/flask_admin/contrib/sqla/view.py#L350

Hopefully (or eventually) this helper will be able to find join path between two properties, but for now it can explicit trace path through relations.

**Comment by pawl** [comment]
Made some progress here: https://github.com/flask-admin/flask-admin/compare/master...pawl:fix_1174?expand=1

Mostly moved `get_field_with_path` into sqla/tools.py and used it in `get_form`. It's showing the field now, but it isn't getting populated.

**Comment by pawl** [comment]
I thought some more about this and realized it's more complicated when there isn't already a related record to edit (or if there are multiple related records). Hence, the reason for `inline_models`.

Maybe there a should just be an exception that tells the developer to use `inline_models`.
