### ISSUE TITLE
Import and export models data from / to JSON

### ISSUE THREAD

**Issue by rudyryk** [flask-admin/flask-admin#1178]
Didn't find a feature of importing models data from JSON, also known as fixtures. I think that would be very useful one! As import and export logic depends on specific ORM, seems like we should implement it in model view subclasses.

**Comment by jzp113** [comment]
I rewrite the base Model, but you should note the datetime type cover to the json
`    @expose('/export/json/')
    def export_json(self):
        """
            Export a CSV of records.
        """
        self.datetype = ''
        return_url = get_redirect_target() or self.get_url('.index_view')

        if not self.can_export:
            flash(gettext('Permission denied.'))
            return redirect(return_url)

        # Macros in column_formatters are not supported.
        # Macros will have a function name 'inner'
        # This causes non-macro functions named 'inner' not work.
        for col, func in iteritems(self.column_formatters):
            if func.__name__ == 'inner':
                raise NotImplementedError(
                    'Macros not implemented. Override with '
                    'column_formatters_export. Column: %s' % (col,)
                )

        # Grab parameters from URL
        view_args = self._get_list_extra_args()

        # Map column index to column name
        sort_column = self._get_column_by_idx(view_args.sort)
        if sort_column is not None:
            sort_column = sort_column[0]

        # Get count and data
        count, data = self.get_list(0, sort_column, view_args.sort_desc,
                                    view_args.search, view_args.filters,
                                    page_size=self.export_max_rows)

        # https://docs.djangoproject.com/en/1.8/howto/outputting-csv/

            # Append the column titles at the beginning

        data_json = [{c[0]: str(self.get_export_value(row, c[0])) for c in self._export_columns} for row in data]
        import json
        return json.dumps(data_json)`

**Comment by pawl** [comment]
This feature was added here (and isn't in a release yet): https://github.com/flask-admin/flask-admin/pull/1203

The implemention with tablib is a bit more flexible and allows for more than just json.
