### ISSUE TITLE
Showing primary key on view/edit (not list)

### ISSUE THREAD

**Issue by filmackay** [flask-admin/flask-admin#1182]
Thoughts on allowing an option to include primary key on view/edit? Maybe an option that allows editing it as well (shock) :)

There is a lot of work required to work-around this, with the codebase as it is. At the very least I don't see the issue with displaying primary key(s) - even by default! Many databases don't use the auto-INT-key pattern, so there is some meaning in the key.

https://www.bountysource.com/issues/7225279-feature-request-option-that-adds-a-primary-key-field-to-the-edit-and-create-forms

Thoughts? .. before I go implementing a PR to do this, feel free to make suggestions on implementation approach.

**Comment by xqliu** [comment]
I think make it a read only reference field is more reasonable for a primary key.

I have implemented similar fields using a custom read only controller as below

`class DisabledStringField(StringField):

    def __call__(self, **kwargs):
        kwargs['disabled'] = True
        return super(DisabledStringField, self).__call__(**kwargs)
`

Not sure whether that's a good idea here.

**Comment by filmackay** [comment]
There are lots of databases that don't use identity INT primary keys - eg. human readable codes. It seems that flask-admin is really not designed to cope with those, and it seems like a large exclusion. Would it not be better to make flask-admin adapt to the type: if the primary key is an identity, then leave it as is - but otherwise the primary key should be viewable/editable in CRUD? This means that if you are an INT identity database, nothing changes - but otherwise it is usable.

**Comment by mrjoes** [comment]
Nope, Flask-Admin works just fine with non-INT keys. It even works with multi-column PKs.

Here's example how make PK editable (even though it is Integer in this example): https://github.com/flask-admin/flask-admin/blob/master/examples/sqla/app2.py

**Comment by cancan101** [comment]
Is there anyway to say "all of the default fields" _and_ these? It seems as if setting `form_columns` clears out the default set.

**Comment by BackMountainDevil** [comment]
> Nope, Flask-Admin works just fine with non-INT keys. It even works with multi-column PKs.
> 
> Here's example how make PK editable (even though it is Integer in this example): https://github.com/flask-admin/flask-admin/blob/master/examples/sqla/app2.py

page 404
