### ISSUE TITLE
Using peewee, modify fails to update record, even though UI says it was successful.

### ISSUE THREAD

**Issue by kdart** [flask-admin/flask-admin#1187]
I'm attempting to use flask-admin with peewee (using contrib/peewee) for the first time. It mostly works now. However, when I edit a model row and click "save", there is a blue box that claims the update was successful. However, it is not since no update to the database is made.

As far as I can tell the the update_model method gets called, which then calls `form.populate_obj()` method. However, that method does nothing. It's just a `pass`. So how is this supposed to work? Has it ever worked?

**Comment by mrjoes** [comment]
It certainly worked. `populate_obj` is part of the wtforms - http://wtforms.simplecodes.com/docs/0.6.1/forms.html#wtforms.form.Form.populate_obj

Seems like there were some peewee changes that broke functionality or something else is happening.

**Comment by kdart** [comment]
Hm, am I supposed to subclass that and implement that method?  The code has been like that for a while. So I'm not sure what is going on. One other clue is it returns an HTTP 302, rather than a 201 as I would expect. But I'm not sure where that's coming from.

**Comment by kdart** [comment]
Never mind. I figured it out. I had autocommit=False on my database (I usually use it in a transaction).  Setting it to true makes this work.
