### ISSUE TITLE
Not showing username when accessing Post section

### ISSUE THREAD

**Issue by bithost** [flask-admin/flask-admin#1188]
Hello, 
  When i run flask-admin sqla example i cannot see user name under Post section. Only strange object name.
![image](https://cloud.githubusercontent.com/assets/4540096/12809122/139a5098-cb25-11e5-963c-ee1938c94bbc.png)

When i press edit user, Tags is also not showed:
![image](https://cloud.githubusercontent.com/assets/4540096/12809135/320138c6-cb25-11e5-81f9-26c3a3bada55.png)

I new to python still learning, so would be nice if someone could point me where to look for solution.
I am running windows 10 x64 and python 3.5x64.

Thanks, 
  Tadas

**Comment by mrjoes** [comment]
Example adds `__unicode__` to create text representation of the model. For Python 3.x you should use `__str__`.

**Comment by bithost** [comment]
hmm, very strange. I tried to change to __str__ as it was written in comments, but it didn't worked. I will give a try later again.

**Comment by bithost** [comment]
@mrjoes , i tried again and it worked. Thank you!
