### ISSUE TITLE
geoalchemy requires strict declarative_base configuration

### ISSUE THREAD

**Issue by phillip-martin** [flask-admin/flask-admin#1189]
For anyone to use the geoalchemy features, they would be required to have a very specific declarative_base configuration.

From this commit:
https://github.com/flask-admin/flask-admin/commit/6631906fc126eadc114a7ee673194da4880dc960

> It should be noted that the declarative base still has to be configured
> like this:
> 
> ``` python
> MyBase:
>     query = session.query_property()
> ```

It looks like this is a result of line 20 of that commit:

```
geojson = view.model.query.with_entities(func.ST_AsGeoJSON(value)).scalar()
```

This requires that `view.model` has a `session.query_property`. Shouldn't `view` already have a `session`? If so, the following would work while not restricting the declarative_base configuration:

```
geojson = view.session.query(view.model).with_entities(func.ST_AsGeoJSON(value)).scalar()
```

**Comment by petrus-jvrensburg** [comment]
Closing this now. But please re-open if it's still a problem.
