### ISSUE TITLE
NameError: name 'UsersAdmin' is not defined when moved all classes to another file

### ISSUE THREAD

**Issue by bithost** [flask-admin/flask-admin#1195]
Hello, 
  I wanted to move all Class to another file called model.py, but now when i run app.py i get 
NameError: name 'UserAdmin' is not defined.

Can someone take a look at my files:
app.py - http://pastebin.com/MHMxgJJZ
models.py - http://pastebin.com/WRBBC5zT

and tell me what i am doing wrong. 

Thanks, 
  Tadas

**Comment by discort** [comment]
@bithost your model is `UserAdmin`. In app.py you made a typo:
`admin.add_view(**UsersAdmin**(User, db.session))

Please, ask questions on http://stackoverflow.com/questions/tagged/flask-admin

**Comment by bithost** [comment]
@discort , it was my typo mistake, but i have same error when changed to UserAdmin, that 
NameError: name 'UserAdmin' is not defined. I really don't understand why it stops working when moved to another file. I am writing using Atom so it detects UserAdmin class from models.py so i am really confused what is wrong. 

thank you for link where i should post question. I will do that now. Sorry again for writing it in a wrong place.

Thanks, 
   Tadas
