### ISSUE TITLE
PostgreSql CITEXT column not shown/editable.

### ISSUE THREAD

**Issue by fake-name** [flask-admin/flask-admin#1196]
I have a Postgres table with a column of type CITEXT (it's a extension type, but a core extension type, Support is via this plug-in [here](https://github.com/mahmoudimus/sqlalchemy-citext)).

This column is not reflected in the create/edit dialogs of flask-admin.

It does show up in the table view.

It's probably fairly simple to do, but how can I convince flask-admin to allow editing of this column? For all functional purposes, it's basically just a column of type TEXT.

**Comment by mrjoes** [comment]
You can add custom model converter to add support for this type:

1. You need to create custom model converter: http://flask-admin.readthedocs.org/en/latest/api/mod_contrib_sqla/#flask_admin.contrib.sqla.ModelView.model_form_converter
2. Add support for CITEXT to the model converter: https://github.com/flask-admin/flask-admin/blob/master/flask_admin/contrib/sqla/form.py#L293

I recommend adding custom model converter to your base class, so new converter will be used for all model views.

Also, I don't mind getting pull request for the default SQLa model converter.

**Comment by fake-name** [comment]
I'll have a poke, and see what I can do, then.

**Comment by beenje** [comment]
@fake-name, I just bumped into the same issue. Before trying to solve it myself, do you have a solution to share?

**Comment by fake-name** [comment]
I never did get around to looking into the issue. Sorry!

**Comment by beenje** [comment]
Thanks for the quick reply! Will try to look at it.
