### ISSUE TITLE
When column length is exceeded with SQLAlchemy an error is raised.

### ISSUE THREAD

**Issue by ryanmthompson** [flask-admin/flask-admin#1197]
Flask-Admin 1.4.0
After setting the column length in my application, and then creating or updating a row that exceeds the specified length an error is thrown, as expected, but there is no obvious explanation presented to the user.  A response similar to the one generated when entering a wrong data type would be preferable, so the user would know right away that the column length was exceeded.

**Comment by pawl** [comment]
I just tried creating a new record that exceeded the max length set in the database model. It threw an error: ![error](https://i.imgur.com/g4anNgX.png)

Here's the gist: https://gist.github.com/pawl/589c3fd158557139737a78d3c73bfec0

Is there something I'm missing for reproducing this one?
