### ISSUE TITLE
404 NOT FOUND for some static files with ver. >=1.3.0

### ISSUE THREAD

**Issue by nypgand1** [flask-admin/flask-admin#1204]
Like:
* jquery-2.1.1.min.js 
* moment-2.8.4.min.js 
* filters-1.0.0.js 
* form-1.0.0.js 
* actions-1.0.0.js 

It leads me to the following issue: https://github.com/airbnb/airflow/issues/296, which says it is a problem of flask-admin with ver. >= 1.3.0

I use flask-admin as root with url='/'

Any ideas?

**Comment by mrjoes** [comment]
There are no such files in the repository: https://github.com/flask-admin/flask-admin/tree/master/flask_admin/static/admin/js

And here's how they are included: https://github.com/flask-admin/flask-admin/blob/master/flask_admin/templates/bootstrap3/admin/base.html#L75

As you can see, version is added as argument, so resulting URL should look like: jquery.min.js?v=2.1.4

This change was made in July 5, certainly before 1.3.0 release.

Maybe you're using some custom theme which hardcoded links to old files?

**Comment by nypgand1** [comment]
@mrjoes Thanks for your reply!
Yes, I use the old template accidentally, and it works now after being updated.

But I'm wondering why it doesn't work if we have the files in local folder like '/static/admin', which the url seems good to me?
