### ISSUE TITLE
Recent commits broke support for hybrid properties expressions

### ISSUE THREAD

**Issue by vToMy** [flask-admin/flask-admin#1206]
For instance:
```
@hybrid_property
def foo(self):
    return some_value

@foo.expression
    return select(...)
```

No longer works. It seems contrib/sqla/view/get_list_columns (and maybe related methods) can't handle the "select" type that is being returned by the expression. This used to work. I suggest adding a test for it.

To be more specific, it worked before: https://github.com/flask-admin/flask-admin/commit/459010b0def9da74836f1379126434c5f922ba0c

**Comment by vToMy** [comment]
Alright I think I fixed it. Will send a issue a pull request later.

**Comment by pawl** [comment]
@vToMy thanks for reporting the issue. It looks like it was a quick fix: https://github.com/flask-admin/flask-admin/issues/1206

Let me know if you have any suggestions to improve that pull request.

**Comment by vToMy** [comment]
Actually the error I got was:
`'Select' object has no attribute 'key'`
Which means it doesn't even have a key attribute, so this doesn't fully solve the issue.
I have another fix which I'll contribute soon.

**Comment by vToMy** [comment]
I added it in my active PR (https://github.com/flask-admin/flask-admin/pull/1209). It's not ideal, I know, but I kinda lost it trying to create a new one. If you'd like, you can copy over the changes to a new PR.

**Comment by vToMy** [comment]
Deleted that PR. Will contribute with small changes for the better good. I added a comment to your PR with an improvement.
