### ISSUE TITLE
select2 "multiple autocomplete" "tag" like field -- question

### ISSUE THREAD

**Issue by dgleba** [flask-admin/flask-admin#1208]
I would like to implement a (possibly non standard) "select2" field in flask-admin.

Consider a "To" field in an email. One starts typing an email address and matches show up in a select2 list.
Click on an email address and it pops in that email address - the exact text of the address, not an Id.
Next, one can start typing another email address so it can be populated into the target "To" field as well. 
This can continue as many times as the user needs.

Links that may be related:

http://stackoverflow.com/questions/26684029/select2-field-implementation-in-flask-flask-admin
I tried to implement this here: https://github.com/dgleba/flaskplayground/blob/master/28select2-test/fltg.py
No luck.

I can't say I understand this one...
https://github.com/Jaza/flasktaggingtest

I got this working, but it is a select. Also, it gets suggestions locally, not from a table.
http://stackoverflow.com/questions/31081516/how-can-i-turn-a-string-model-field-into-a-select-input-in-flask-admin

1.
Can I ask this question here?
If not, where is the suggested place to do so?

2.
Can someone point me to examples or documents that I could learn from to do this?

3.
Can someone help me with this?

History:

I have been learning Flask-admin for a couple months. 
I have been making small working examples to learn Flask-admin.
I don't ask this question lightly.
I have read many hours. I have looked for other examples I can learn from.
I haven't found something I can learn from to figure this out myself.
I learn best from examples.

Reference:

Stuff I am writing to learn Flask-admin.

My small examples:
    https://github.com/dgleba/flaskplayground
Small apps.
    https://github.com/dgleba/pdb218
    https://github.com/dgleba/cif207

Many thanks in advance.    

David Gleba

**Comment by cstrutton** [comment]
Dave.  Your problem here is with select2, not flask-admin.  Select2 always returns the id part of the data in the form.  [This post](http://tec-tonic.blogspot.ca/2014/03/select2-gotchas-and-other-useful.html) shows how to create the id in a callback letting you return whatever you need.
