### ISSUE TITLE
mongoengine upload image to s3

### ISSUE THREAD

**Issue by genxstylez** [flask-admin/flask-admin#1219]
as titled,

My document looks like this
```python
class Style(db.Document):
    created = db.DateTimeField(default=now)
    updated = db.DateTimeField(default=now)
    name = db.StringField(max_length=32, required=True)
    description = db.StringField()
    cover = db.URLField(required=True)
    published = db.BooleanField(default=False)
```

So I want to be able to change the widget of `cover` field to a `FileInputField` and then get the file upload it to **S3** then save the url to `cover`

any ideas on how to?

**Comment by mrjoes** [comment]
Use this https://github.com/flask-admin/flask-admin/blob/master/flask_admin/form/upload.py#L286 (or FileUploadField if you don't need preview) as a foundation, override `_save_file` (and, maybe, `_save_thumbnail`) to send file to S3. Initialize your `url_relative_path` to your field or override `get_url` in your field: https://github.com/flask-admin/flask-admin/blob/master/flask_admin/form/upload.py#L109

**Comment by genxstylez** [comment]
How do I validate the form and save the result (s3 endpoint) to my `cover` field?

**Comment by genxstylez** [comment]
```python
class StyleAdmin(ModelView):
    form_extra_fields = {
        'cover': form.ImageUploadField('Image', base_path='/tmp', thumbnail_size=(100, 100, True))
    }
```
When I do this, and save the model, I get `ValidationError: ValidationError (Style:None) (Invalid scheme logoicon_3.png in URL: LOGOICON_3.png: ['cover'])`
