### ISSUE TITLE
Bug with Sqlite and DateTime in pk

### ISSUE THREAD

**Issue by mistercrunch** [flask-admin/flask-admin#1226]
Getting an exception "SQLite DateTime type only accepts Python datetime" when deleting an entry and using Sqlite on a model that has a DateTime field in its primary key. 

On other backends it works because of some internal autocasting I believe.

**Comment by mrjoes** [comment]
That's weird error. It happens in `get_one` and only argument that's passed is primary key. Do you know if PK for that table is `datetime`? If yes, this might explain why it happens.

Probably Flask-Admin can guess type of the PK column and try to convert value to that type... but this would be very unreliable. I'd recommend overriding `get_one` for administrative view in question and passing converted `DateTime` object to SQLAlchemy.

**Comment by mistercrunch** [comment]
The pk is a composite set of 3 fields that contains one Datetime field. The reason it works in other databases is that there is some auto-casting going on that sqlite doesn't have. In reality SqlAlchemy expects a `datetime.datetime` but somehow lets a string through for the database to deal with it, which causes issues only in sqlite.

It's kind of an edge case but clearly a flask-admin bug. I'll try to find time to write PR and attach it to this issue.

**Comment by mrjoes** [comment]
That's the case. Flask-Admin passes primary key as a string assuming that DB backend is able to figure it out. It generally works, even with SQLite non-string PKs like Integer. But it does not work with DateTime, unfortunately. 

Detecting proper column types for composite (or even non-composite types) would take considerable amount of effort and as I wrote above, it would be significantly easier to override single method in the administrative view and do type conversion there: https://github.com/flask-admin/flask-admin/blob/master/flask_admin/contrib/sqla/view.py#L991

`iterdecode` function converts encoded multi-column primary key into list of strings. Then you can convert datetime value before passing it to the query filter.

**Comment by petrus-jvrensburg** [comment]
Closing this now. As per the comment above: use `iterdecode` for a workaround.
