### ISSUE TITLE
Can not change admin view in init_app

### ISSUE THREAD

**Issue by nycynik** [flask-admin/flask-admin#1237]
I want to change the admin view, and I am using the init.app() method, but there is no way to change the default admin view from the init_app.  Am I missing something? Is there another way? Not sure why nobody else is having this issue.

**Comment by xqliu** [comment]
Not sure what you are talking about "init.app()"

But here's how I init flask admin 

Using index_view to  pass in your default admin view.

```
admin_views = Admin(app, lazy_gettext('Brand Name'), index_view=AdminIndexView(),
                    base_template='layout.html', template_mode='bootstrap3')
admin_views.add_view(PurchaseOrderAdmin(PurchaseOrder, db_session, name="Purchase Order",
                                            category='Purchase''))

```

Here is the definition of admin index view.

```
class AdminIndexView(admin.AdminIndexView):
    @expose('/')
    def index(self):
        if not current_user.is_authenticated:
            return redirect(url_for_security('login'))
        return self.render('dashboard.html')
```

**Comment by pawl** [comment]
Looks like you fixed this one in: https://github.com/flask-admin/flask-admin/pull/1238

**Comment by nycynik** [comment]
Thank you! Sorry I should have closed it earlier.
