### ISSUE TITLE
Can't Login - Can't Logout - Auth Example

### ISSUE THREAD

**Issue by dgleba** [flask-admin/flask-admin#1239]
I ran the auth example from Flask-Admin again today. 

I cannot login. I cannot logout.

Screen shot attached.

Am I doing something wrong?

![error cantlogin cantlogout chromelegacy window_home - example_ auth](https://cloud.githubusercontent.com/assets/4622715/14028550/911b12bc-f1d3-11e5-994e-3d88fff0874d.png)

**Comment by paggel** [comment]
Could you please write your block code ?

**Comment by dgleba** [comment]
Thank you for replying.

I am not sure I understand what you mean. The code I am running is exactly the auth example.

https://github.com/flask-admin/flask-admin/tree/master/examples/auth

I want to understand what is causing this. 
I have since run pip install flask-login. It uninstalls and re-installs and it works after that -- but why?

**Comment by pawl** [comment]
I just started a new virtualenv, installed requirements from `examples/auth/requirements.txt`, and ran the app + logged in/out. It seems to be working fine.
