### ISSUE TITLE
save as new

### ISSUE THREAD

**Issue by co-dh** [flask-admin/flask-admin#1256]
Is it possible to add a save as new button as Django?
It's not that easy: you'll need to recursive "save as" contained object, and for id columns, you'll need to retrieve it from the database.

Any idea/example on how to implement it?

**Comment by rochacbruno** [comment]
In QuokkaCMS I created a "clone" action https://github.com/rochacbruno/quokka/blob/development/quokka/core/admin/models.py#L204

So you can select an entry in admin and "with selected --> clone" it copies all fields and generates a random ID.

But, It works well for MongoSB not sure for others.

**Comment by rochacbruno** [comment]
You can test it in demo http://demo.quokkaproject.org/admin (admin@example.com:admin)

Select an item and then click in "create a copy"

![quokka](http://i.imgur.com/PdBHSpO.png)

**Comment by co-dh** [comment]
@rochacbruno thanks for you help. I am wondering if there exists more general solutions that works for any object.

**Comment by rochacbruno** [comment]
@co-dh I dont think so because it depends on DB and ORM being used. Maybe we can have a general "save as a copy" action covering all of them.
