### ISSUE TITLE
options for inline_models

### ISSUE THREAD

**Issue by co-dh** [flask-admin/flask-admin#1260]
What are the options for inline_models in the form below? 

> Child model class and additional options:
> 
> class MyModelView(ModelView):
>     inline_models = [(Post, dict(form_columns=['title']))]

I figured out that form_label, form_args, form_rules, form_columns are supported, inline_models are not, but what about others?

**Comment by xqliu** [comment]
As from the source code of InlineBaseFormAdmin and InlineFormAdmin, I guess the follow is included, but not sure any other also could be used:

'form_base_class', 
'form_columns', 
'form_excluded_columns', 
'form_args', 
'form_extra_fields',
'form_rules',
