### ISSUE TITLE
can_view_details and can_export can not refer to current_user.is_authenticated

### ISSUE THREAD

**Issue by xqliu** [flask-admin/flask-admin#1263]
I found that can_view_details and can_export can not refer to current_user, if we use current_user.is_authenticated in can_view_details and can_export property method, then the follow exception will be thrown

AttributeError: 'NoneType' object has no attribute 'is_authenticated'

And this is caused by _refresh_cache in model/base.py refers to can_view_details and can_export as below:

```
        if self.can_view_details:
            self._details_columns = self.get_details_columns()

        # Export view
        if self.can_export:
            self._export_columns = self.get_export_columns()
```

Can we just set it same as _list_columns and _sortable_columns like below?

```
        # List view
        self._list_columns = self.get_list_columns()
        self._sortable_columns = self.get_sortable_columns()
```

Thanks.

**Comment by pawl** [comment]
Fixed by #1264
