### ISSUE TITLE
Object Names in Navigation Bar

### ISSUE THREAD

**Issue by Bastian-Kuhn** [flask-admin/flask-admin#1271]
With Python 3,
Flask-Admin==1.4.0,
mongoengine==0.10.6,
pymongo==3.2.2,

and the following code:
```
from flask.ext.admin import Admin
from flask_admin.contrib.mongoengine import ModelView

#more stuff

admin = Admin(app, name="Screen Admin")  
admin.add_view(ModelView(User, db ))
```
the navigation bar is getting the following linkname:

`<a href="/admin/user/">&lt;flask_mongoengine.MongoEngine object at 0x7f67461582e8&gt;</a>`

instead having a normal name like User.
I'm not sure if this is a issue with flask-admin or mongoengine.

**Comment by mrjoes** [comment]
Add `__str__` to your models for Python 3 or `__unicode__` for Python 2.

**Comment by Bastian-Kuhn** [comment]
Hi,

thanks for the response, but this is not the solution :)
I have the Problem in the Navigation bar. I already have __str/unicode__ as part of some models to have the correct names for ReferenceFields. But even without, the name of the Model is correctly shown in the Dropdown fields there (Edit Reference Fields).

**Comment by mrjoes** [comment]
Flask-Admin always uses str/unicode to get string representation for the model, be it the list or related fields. Check some of the demos - they all work properly with foreign keys.

**Comment by Bastian-Kuhn** [comment]
Hi,

sorry for my unclear expression.
I have already __str__ as part of my models:

```
    def __str__(self):
        return "User "+ self.username
```

and this works fine when i try to edit models with Reference Fields. There i can see: e.g. "User Harri Hirsch" in the dropdown.

But the Navigation bar in the top shows "flask_mongoengine.MongoEngine object at 0x7f67461582e8&gt"

For my understanding the string representation is only for one Document/ Object and not for the hole Model? Sorry for that trouble. 
Or what else do i missing?

**Comment by Bastian-Kuhn** [comment]
Ok, found the Problem.
I used documentation for the ModelView from a Cookbook who described  sqla. The second parameter for admin.addView() was db.session there. I looked into the Sourcecode for the mongo ModelView and saw that there the second parameter is name="". So my fault, sorry..
