### ISSUE TITLE
Unable to use theme from Bootswatch

### ISSUE THREAD

**Issue by scottydelta** [flask-admin/flask-admin#1286]
As per suggestion from comment: https://github.com/flask-admin/flask-admin/pull/1016#issuecomment-134437376, I made the changes but the theme doesnt get applied properly:
```
{% extends 'admin/base.html' %}

{% block head_tail %}
  {{ super() }}
    {% set bootswatch_theme = 'cyborg' %}
    {% set bootswatch_version = '3.3.6' %}
    <link href="//netdna.bootstrapcdn.com/bootswatch/{{ bootswatch_version }}/{{ bootswatch_theme }}/bootstrap.min.css" rel="stylesheet" >
{% endblock %}
```
`
admin = Admin(name='Tweet Tracker',base_template='custom_admin.html', template_mode='bootstrap3' ,url='/', index_view=ProjectView(Project, db.session, url='/admin'))`

![image](https://cloud.githubusercontent.com/assets/2242189/15447424/c2e4fbc8-1ef6-11e6-87fc-f1950ff3755a.png)

Deleting this line [admin/base.html](https://github.com/flask-admin/flask-admin/blob/master/flask_admin/templates/bootstrap3/admin/base.html#L16) solves the issue.

![image](https://cloud.githubusercontent.com/assets/2242189/15447446/73f4bbba-1ef7-11e6-846f-6e7a6f8c254f.png)

**Comment by mrjoes** [comment]
You can always override `head_css` block and get rid of the base CSS file.

**Comment by scottydelta** [comment]
```
{% extends 'admin/base.html' %}

{% block head_css %}
  {{ super() }}
    {% set bootswatch_theme = 'lumen' %}
    {% set bootswatch_version = '3.3.6' %}
    <link href="//bootswatch.com/{{ bootswatch_theme }}/bootstrap.min.css" rel="stylesheet" >
{% endblock %}
```

^ doesnt solve the issue.

**Comment by mrjoes** [comment]
```html
    {% block head_css %}
    {% set bootswatch_theme = 'lumen' %}
    {% set bootswatch_version = '3.3.6' %}
    <link href="//bootswatch.com/{{ bootswatch_theme }}/bootstrap.min.css" rel="stylesheet" >
        <link href="{{ admin_static.url(filename='admin/css/bootstrap3/admin.css', v='1.1.1') }}" rel="stylesheet">
        <style>
        body {
            padding-top: 4px;
        }
        </style>
    {% endblock %}
```

**Comment by scottydelta** [comment]
It worked nicely, thank you @mrjoes
