### ISSUE TITLE
What about 1.4.1 release with some fixes?

### ISSUE THREAD

**Issue by ei-grad** [flask-admin/flask-admin#1295]
Hi!

I'm pretty confused with some annoying issues in 1.4.0, but I'm not ready to switch to master branch or to upcoming release right now in my projects. What if we could make a 1.4.1 backward compatible release with some fixes?

Specifically for me it is:
#1207 - Allow to use empty url for AdminIndexView
#1294 - contrib.geoa: don't depend on flask-sqlalchemy

Of course some work should be done to collect the issues that annoy other people and which could be solved without breaking compatibility. I'm not aware with current status of flask-admin community, may be there could be someone who can deal with that? If no - I can try.

**Comment by mrjoes** [comment]
Current master is pretty stable, it is more of "lets get more features/fixes before doing release".

Unless there's something pending from @pawl, I'll do next release this weekend.

**Comment by pawl** [comment]
@mrjoes Nothing pending. A release this weekend sounds good.

**Comment by mrjoes** [comment]
This was completed.
