### ISSUE TITLE
Can't get examples form to work

### ISSUE THREAD

**Issue by songproducer** [flask-admin/flask-admin#1297]
Hello,

When I click File I get this:

sqlalchemy.exc.OperationalError
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: file [SQL: 'SELECT count(?) AS count_1 \nFROM file'] [parameters: ('*',)]

**Comment by petrus-jvrensburg** [comment]
This was probably due to the sample sqlite db not being created.
