### ISSUE TITLE
model sensitive can_edit and can_delete

### ISSUE THREAD

**Issue by xqliu** [flask-admin/flask-admin#1301]
Dear all,

Sometimes it's a common requirement to decide whether a record could be delete / edit based on some fields or other condition, but under current design, the can_edit, can_delete is decided and bound to an admin view, not a specific record, 

I would like to implement a can_edit, can_delete bound to the actual model object, the definition might like 

```
def can_edit(self, form, model):
    """ model parameter is the actual model object.

def can_delete(self, form, model):
    """model parameter is the actual model object
```

I know to do the check on **on_model_change** and **on_model_delete** is a solution, but still I think adjust the UI and hide the  operation button if the above can_edit / can_delete returns false could be a better way from user experience perspective.

Is there any advice on how can I implement this on a better way from you?

Thanks.

**Comment by ritchiewang** [comment]
根据我对你要求的理解，我觉得你可以在```is_accessible()```函数里，来变更can_edit和can_delete两个变量。不过，在改变一个用户的权限时，用户需要刷新界面，相应的编辑或者删除按钮才会消失

**Comment by xqliu** [comment]
@ritchiewang  that's not possible since in is_accessible(), we do not have the model data information, that's bind to a model definition, not a specific model data.

I have implemented it by change flask-admin list template to decide whether to display the delete / edit link based on a can_edit, can_delete method in the model definition.

Thanks for your help.

**Comment by petrus-jvrensburg** [comment]
I'm closing this, because there is a workaround: as you mentioned, overriding the builtin list-view template gives you the flexibility to show/hide controls for particular rows.

But if there are more users who would like to see it as a feature, please re-open.
