### ISSUE TITLE
Geographic field can't render in edit view

### ISSUE THREAD

**Issue by WillEngler** [flask-admin/flask-admin#1308]
[Minimal app to recreate](https://gist.github.com/WillEngler/82da034dbfb0b5d00fa79f6a0f770517). I'm using Python 3.5

Using the geoalchemy ModelView, I can create a model with a geographic component and see it in the list without issue. But when I go to edit a model with a geographic component, the field where the Leaflet map interface should be is blank. In the console, I see Leaflet complain about invalid GeoJSON. This is the GeoJSON being passed to Leaflet: `{\"type\":\"Point\",\"coordinates\":[-87.5926208496094,41.7930725281021]}`. Note the backslashes.

From my investigation, I'd place the root cause of this bug [here](https://github.com/flask-admin/flask-admin/blob/master/flask_admin/contrib/geoa/fields.py#L61).

``` python
return super(GeoJSONField, self)._value()
```

JSONField is the parent class. Its `_value` method expects the `data` attribute to be a dictionary. However, `data` is already a string. So when `_value` calls `json.dumps` on the string, it inserts backslashes, rendering the string unreadable by Leaflet.

By naively replacing the quoted line above with `return self.data` I solve my problem, but I assume that would break some other behavior.

Any suggestions on this? With a little guidance I'd be happy to work on a fix and get something ready to PR.

FWIW, my installed packages:

```
click==6.6
Flask==0.11.1
Flask-Admin==1.4.2
Flask-SQLAlchemy==2.1
GeoAlchemy2==0.3.0
itsdangerous==0.24
Jinja2==2.8
MarkupSafe==0.23
psycopg2==2.6.2
Shapely==1.5.16
SQLAlchemy==1.0.14
Werkzeug==0.11.10
wheel==0.24.0
WTForms==2.1
```

**Comment by mgc0re** [comment]
Hi mate!
Thanks for great finding! I noticed, that you solution breaks create view - area select widget is not shown, so I ended up with this temporal workaround:
`        if(self.data):
            return self.data
        else:
            return super(GeoJSONField, self)._value()`

But also interested in correct fix;)

**Comment by petrus-jvrensburg** [comment]
Closing this now. I don't think this is still a problem, but if so, please re-open.

**Comment by petrus-jvrensburg** [comment]
P.S. the Leaflet plugin has been updated on `master`, so you'll see that in the next Flask Admin release.
