### ISSUE TITLE
BaseView.get_url is not respected sometimes

### ISSUE THREAD

**Issue by MarSoft** [flask-admin/flask-admin#1313]
According to docstring, `BaseView.get_url` method can be used to persist query string arguments.
Here is my usecase: I have two views - `LoginView` and RegisterView`, and they both accept`next`argument. I overriden a`get_url`method for both of them to check it there is a`next`parameter in`request.values`and add it to`kwargs`. This works; but here is a problem:

When a view is referenced from the menu, it is wrapped in `MenuView` class. This class by default will cache generated URLs, with no respect to current request.
As a result, urls from the first request made after app restart are cached. After that, my custom `get_url` is never called for menu links.

Here is my (partial) solution: I have subclassed `Admin` class and overriden its `_add_view_to_menu` method, so that it checks if the view in question has a mixin which provides custom `get_url` implementation, and if so then it creates `MenuView` instance itself with `cache=False` added. Else it will just call superclass' implementation.

``` python
class MyAdmin(Admin):
    def _add_view_to_menu(self, view):
        if not isinstance(view, RetainNextParamMixin):
            return super()._add_view_to_menu(view)

        self.add_menu_item(MenuView(view.name, view, cache=False), view.category)

class RetainNextParamMixin:
    def get_url(self, endpoint, **kwargs):
        if endpoint != 'admin.static':
            kwargs.setdefault(request.values.get('next'))
        return super().get_url(endpoint, **kwargs)
```

Probably we can add some parameter like `no_cache_url` to BaseView class, to be used in such situations?

**Comment by mrjoes** [comment]
Sorry for the late response, but it should be already supported: https://github.com/flask-admin/flask-admin/blob/master/flask_admin/menu.py#L84 with `cache` argument.

Also, you can always inherit from `MenuView` class and disable caching explicitly.

**Comment by MarSoft** [comment]
@mrjoes, yes, this is already supported - I do use this support in my workaround.
The problem is that by default (without subclassing `Admin`) we cannot influence how `MenuItem` is being created in `Admin.add_view`, which class is used or which parameters are passed. So in order to pass that `cache=False`, I had to subclass `Admin`.
Your method with inheriting from `MenuView` class will not work for the same reason: default implementation of `Admin` always uses `MenuView` class itself.

What I would like to suggest is to expose that `cache` parameter for `MenuView`, e.g. in the following way:

```python
class Admin:
    def _add_view_to_menu(self, view):
        self.add_menu_item(MenuView(view.name, view, cache=view.url_cached), view.category)

class BaseView:
    url_cached = True
    """
    By default, URL returned by `get_url` will be cached in menus.
    Set this to False to force url regenerating each time.
    """
```

**Comment by MarSoft** [comment]
@mrjoes, yes, this is already supported - I do use this support in my workaround.
The problem is that by default (without subclassing `Admin`) we cannot influence how `MenuItem` is being created in `Admin.add_view`, which class is used or which parameters are passed. So in order to pass that `cache=False`, I had to subclass `Admin`.
Your method with inheriting from `MenuView` class will not work for the same reason: default implementation of `Admin` always uses `MenuView` class itself.

What I would like to suggest is to expose that `cache` parameter for `MenuView`, e.g. in the following way:

```python
class Admin:
    def _add_view_to_menu(self, view):
        self.add_menu_item(MenuView(view.name, view, cache=view.url_cached), view.category)

class BaseView:
    url_cached = True
    """
    By default, URL returned by `get_url` will be cached in menus.
    Set this to False to force url regenerating each time.
    """
```
