### ISSUE TITLE
adding custom template folder for packages (loaded via entry points)

### ISSUE THREAD

**Issue by ThomasLecocq** [flask-admin/flask-admin#1314]
Hi,

I'm using a flask-admin app as the DB frontend for https://github.com/ROBelgium/MSNoise, and I provide a way to dynamically add Views for "modules" or "plugins", i.e. packages, via entry_points.
My way of doing works very nicely for classic flask-admin views (list/edit), but if the plugin requires a custom template, I didn't find a way to pass the location of the template file. 

In the MSNoise admin loading part:
```python
    if plugins:
        plugins = plugins.split(',')
        for ep in pkg_resources.iter_entry_points(group='msnoise.plugins.admin_view'):
            module_name = ep.module_name.split(".")[0]
            if module_name in plugins:
                admin.add_view(ep.load()(db))
```

and the structure of the plugin is;

```
│   setup.py
│   __init__.py
├───msnoise_qc
│   │   compute.py
│   │   default.py
│   │   install.py
│   │   plugin_definition.py
│   │   table_def.py
│   │   __init__.py
│   │
│   └───templates
│       └───admin
│               data_qc.html
```

and the declaration is:
```python
class QCView(BaseView):
    view_title = "MSNoise QC"

    def __init__(self, session, **kwargs):
        # You can pass name and other parameters if you want to
        super(QCView, self).__init__(name="QC", category="Database", **kwargs)

    @expose('/')
    def index(self):
        tmpl_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                'templates')
        return self.render(template='admin/data_qc.html', tmpl_dir=tmpl_dir)
```

Here I tried setting ``tmpl_dir`` which doesn't seem to have an effect... Is there a way to do this properly?  Overriding the jinja2 loader ?

Best regards,

**Comment by mrjoes** [comment]
`render` is just a shortcut to Flask `render_template` function.

`render_template` uses Flask machinery (and configuration) to find a template using Jinja2 template loader.

Following options should work:

1. Custom Jinja2 loader. It knows about the plugins
2. Add `FileSystemLoader` after the app is initialized:

```python
my_loader = jinja2.ChoiceLoader([
        app.jinja_loader,
        jinja2.FileSystemLoader(['/plugin1/templates', '/plugin2/templates', ...]),
    ])
```

There's one catch - Flask does not have namespaces for templates. This means if you have following directory structure and try to render `file.html`, last file will be rendered:

/plugin1/templates/file.html
/plugin2/templates/file.html

So, you'll have to make sure that plugin folders have plugin name subfolder:

/plugin1/templates/plugin1/file.html
/plugin2/templates/plugin2/file.html

**Comment by ThomasLecocq** [comment]
Brilliant!  Thanks @mrjoes !

for further reference, this is working smoothly:

```python
    app = Flask(__name__)
    admin = Admin(app)
    app.jinja_loader = jinja2.ChoiceLoader([
        app.jinja_loader,
        jinja2.FileSystemLoader(template_folders),
        ])
```

and the template_folders list is generated from the entry point defined in the plugin's setup.py

```python
    entry_points = {
        'msnoise.plugins.templates': [
            'templates = msnoise_qc.plugin_definition:register_template_folders',
        ],
    },
```

and the corresponding function in plugin_definition.py:

```python
def register_template_folders():
    folders = []
    tmpl_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            'templates')
    folders.append(tmpl_dir)
    return folders
```
