### ISSUE TITLE
The "brand" on the navbar should be linked to `/`

### ISSUE THREAD

**Issue by kaime** [flask-admin/flask-admin#1317]
The `.navbar-brand` element of the navbar, which displays the name of the app, has a link to `#`.

I think this should better point to `/`. That way, the `Home` entry could be removed to save some space on the navbar.

**Comment by ArthurPBressan** [comment]
Maybe not `/` specifically, but yeah, we should be able to customize that.

**Comment by mrjoes** [comment]
Sure, I don't mind the change. Feel free to submit the pull request.
