### ISSUE TITLE
Feature Request: pony.orm integration

### ISSUE THREAD

**Issue by nielsbuwen** [flask-admin/flask-admin#1321]
Are there any plans on integrating pony.orm? [github](https://github.com/ponyorm/pony), [homepage](https://ponyorm.com/). 

I did some rudimentary testing and was able to generate forms based on easy mappings including
nullable (optional) and not nullable (required) fields (scalar and one-to-one/many-to-one relationships). Until now it suits my needs but an official integration would be nicer.

**Comment by nadermx** [comment]
I think ponyorm also is working on migrations currently

**Comment by luckydonald** [comment]
@nielsbuwen could you share your work so far?

**Comment by nielsbuwen** [comment]
@luckydonald unfortunately, i don't have the original code base anymore. I'm working on it again, but I have some problems with one-to-many mappings.

I have no idea whether I will be able to finish it, but you can find my attempts [here](https://github.com/nielsbuwen/flask-admin/tree/pony-orm-integration).

**Comment by luckydonald** [comment]
Please tell me what problems you face.

**Comment by nielsbuwen** [comment]
There are two models I use for testing: `List` and `Item`. Currently I can assign a `List` object to an `Item`. When doing it the other way round the `List` "loses" the `Item` when saving the form.

I think it becomes clear when you play around with the example app in `examples/pony/`. Try adding a `List` and then create some `Item`s.

Feel free to open issues at my repo, fork it, PR etc. Perhaps we can finish this together.

**Comment by petrus-jvrensburg** [comment]
I'm closing this now. But feel free to re-open if any of you are still working on it.

**Comment by luckydonald** [comment]
I'm not sure why you closed that now? The feature is not really there?
Also only contributors can reopen issues, but no nobody of us.

**Comment by luckydonald** [comment]
@petrus-jvrensburg 
I'm not sure why you closed that now? The feature is not really there?
Also only contributors can reopen issues, but no nobody of us.
