### ISSUE TITLE
flask_wtf.Form Already exists and SecureForm Bad Request

### ISSUE THREAD

**Issue by honmaple** [flask-admin/flask-admin#1324]
I have two or more unique column.
The model is like 
```
class User(db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(49), unique=True)
    email = db.Column(db.String(81), unique=True)
```

When I use `form_base_class = Form`  and edit one column,I always got  error **Already exists** with another column,

but I set only one column ` form_columns = ['username']`,it works well.

I  changed `form_base_class = SecureForm` and if I have set
```
    csrf = CsrfProtect()
    csrf.init_app(app)
```
it couldn't work well include create and edit.When I commented **csrf**,it all work well,but I need **csrf**  in other ways.

So how  can I edit two unique column  with csrf?

**Comment by pawl** [comment]
https://github.com/flask-admin/flask-admin/issues/1007#issuecomment-206671837

**Comment by honmaple** [comment]
answer [#486](https://github.com/flask-admin/flask-admin/issues/486#issuecomment-38859637)
