### ISSUE TITLE
Date range picker, start week on Monday?

### ISSUE THREAD

**Issue by xim** [flask-admin/flask-admin#1326]
I'm using flask-admin for a small project, and I want to localize the calendar week start. I don't want to localize the rest of the page, I just want to make the week start on Monday. Is there any easy way of doing this?

![datepicker](https://cloud.githubusercontent.com/assets/169057/17434891/5c14afc6-5b0d-11e6-9140-d560efd2c591.png)

**Comment by xim** [comment]
I made a workaround: created this __templates/admin/master_override.html__

```
{% extends 'admin/base.html' %}

{% block tail %}
<script type="text/javascript">
$('.form-control').data({locale:{firstDay:1}});
</script>
{{ super() }}
{% endblock %}
```

**Comment by petrus-jvrensburg** [comment]
You could get the same effect by using the `form_widget_args` parameter: https://flask-admin.readthedocs.io/en/latest/api/mod_model/#flask_admin.model.BaseModelView.form_widget_args
