### ISSUE TITLE
Editing cells directly

### ISSUE THREAD

**Issue by kovasap** [flask-admin/flask-admin#1335]
Is there a way to make it possible to edit a cell directly using flask-admin?  I'm looking for something like [this](http://www.editablegrid.net/en/).  Thanks!

**Comment by rochacbruno** [comment]
```python
class MyModelView(BaseModelView):
    column_editable_list = ('name', 'last_name')
```

and then, name and last_name will be text fields editable in the list view

**Comment by kovasap** [comment]
thanks!
