### ISSUE TITLE
example sqla not work for saving item with  M2M field value input 

### ISSUE THREAD

**Issue by 8dspaces** [flask-admin/flask-admin#1339]
i want to try the example M2M case as below link provided by flask-admin
http://examples.flask-admin.org/sqla/simple/admin/post/new/

when i create new item with tag input, it not work 
User: Jack
Tags: Yellow (if not give a tag, save can work)
....

Error like below 
_Integrity error. (IntegrityError) NOT NULL constraint failed: post.text u'INSERT INTO post (title, text, date, user_id) VALUES (?, ?, ?, ?)' (None, None, None, 4)_

**Comment by vToMy** [comment]
This is the source code for this example:
https://github.com/flask-admin/flask-admin/blob/master/examples/sqla/app.py

Changing:
`db = SQLAlchemy(app)`
to:
`db = SQLAlchemy(app, session_options=dict(autoflush=False))`
solves the problem.

I've created a PR: #1351
