### ISSUE TITLE
Wrong assumptions behind MAPBOX_FIX_COORDINATES_ORDER

### ISSUE THREAD

**Issue by ei-grad** [flask-admin/flask-admin#1341]
@pawl @jmagnusson 

I just faced a MAPBOX_FIX_COORDINATES_ORDER warning, introduced by #1231. And there is a problem with it.

> current Leaflet implementation expects coordinates in latitude-longitude order but GeoJSON

Waaat?.. Leaflet don't know how to deal with GeoJSON? Seriously? Any sources / links / docs / confirmations? I'm absolutely sure that someone just has wrong coordinate order in his data. With current implementation (with MAPBOX_FIX_COORDINATES_ORDER=True) I getting wrong coordinate values in database:

```
[ ei-grad@ei-grad ~ ]
→ psql -t discharges -c 'select st_asgeojson(geom) from campaign_geo_limits'
 {"type":"Polygon","coordinates":[[[55.7462457665516,37.5826299190521],[55.7636337005308,37.5884664058685],[55.7715523006922,37.5997960567474],[55.7738696355073,37.626918554306],[55.7690416991694,37.6492345333099],[55.7632473862086,37.6554143428802],[55.7431537667293,37.6550710201263],[55.7319432132944,37.6406514644623],[55.7302033560511,37.6121556758881],[55.7383220264735,37.5877797603607],[55.7462457665516,37.5826299190521]]]}
```

I just draw this polygon near Moscow in flask-admin edit view. Moscow lat/lon are 55/37, so the coordinate order stored in database is wrong.

Btw, is it really worth to execute a spatial database query to flip two numbers?

I suggest to remove all that wrong coordinate flipping logic and handle somehow coordinate projection without that database jerking, maybe using ``pyproj`` or bring the proper projection handling to leaflet (it is able to deal with projections too, but I'd prefer to stick with python instead of javascript in flask application). PR will follow.

**Comment by ei-grad** [comment]
Started work in https://github.com/ei-grad/flask-admin/tree/geoa_refactoring, it already works, but I'm not sure if it should be so compatibility breaking.

**Comment by jmagnusson** [comment]
I felt pretty bad when I sent in the PR about introducing the fix as an opt-in, just wanted a fix for it right there and then. I would love to see a proper clean fix for this instead, keep up the good work!

**Comment by jmagnusson** [comment]
@ei-grad How'd it go with your refactor? I'm thinking to do a revert PR for now... The warning is pretty annoying!

**Comment by ei-grad** [comment]
Sorry, I'm a bit busy with things far from flask-admin during last weeks, but I'm pretty sure I'll be able to redo my refactor soon, keeping the GeoJSON format in place (in current version GeoJSON is replaced with WKT, which is used by geoalchemy2, because it looked good and quick fix for me, and I was needed to launch a service quickly with it, but it looks like WKT transformation in browser is a kind of slow operation... though this fact needs more research, but still it is not a good idea to change format in forms, because I know at least one man who is relying on it to be GeoJSON in default flask-admin's-generated forms).
I hope I will come with pull-request this weekend.

**Comment by ei-grad** [comment]
Btw, revert it is not a bad idea, I'd rebase with it after revert, it is not a problem.

**Comment by jmagnusson** [comment]
Pushed a revert. PR #1361 might also be relevant for your refactor.
