### ISSUE TITLE
sqla/app2.py is broken with python3.5.2

### ISSUE THREAD

**Issue by romeojulietthotel** [flask-admin/flask-admin#1364]
This is under python3.5.2

1) python examples/sqla/app2.py
2) Go to localhost:5000
3) Create new car record
4) Save
5) Select Tyre tab
6) Create new tyre record
7) Note that the Car field is populated with <__main__.Car object at 0x7fe2bef98438>

The same 7 steps work fine on python2.7.12.

Using my rudimentary debugging skills I found that the value is stored in the _view.

**Comment by mrjoes** [comment]
It was not converted to python 3.x - you need to change `__unicode__` to `__str__` in the model definition.

**Comment by romeojulietthotel** [comment]
I see, thanks for this, I will try to send a PR.
