### ISSUE TITLE
Is it possible to show wtform validation error on modal?

### ISSUE THREAD

**Issue by connermo** [flask-admin/flask-admin#1366]
When form validation has errors, the normal template will be rendered instead of the modal template. Is it possible to keep the validation error on modal? Thanks.

**Comment by petrus-jvrensburg** [comment]
Which modal is this? Can you give a bit more information so the issue can be reproduced?

I'm closing the issue in the meantime.

**Comment by waylonwang** [comment]
@petrus-jvrensburg As shown in the picture, the form changes back to the normal template when a validation error occurs.
<img width="845" alt="1" src="https://user-images.githubusercontent.com/7424276/59496246-9f117880-8ec3-11e9-86af-023b7d8a1064.png">
<img width="922" alt="2" src="https://user-images.githubusercontent.com/7424276/59496259-a46ec300-8ec3-11e9-8c1f-d727a477884f.png">
<img width="1159" alt="3" src="https://user-images.githubusercontent.com/7424276/59496279-aa64a400-8ec3-11e9-9edc-49e85cbddceb.png">
