### ISSUE TITLE
Question: how to customise @expose

### ISSUE THREAD

**Issue by LotosikRa** [flask-admin/flask-admin#1383]
I want to storage all views' endpoints in one class to make them easy to customise. 

But in this library `expose` decorator is every where but it hasn't all the functionality of `Flask`'s `App` method `add_url_rule` , that can take `endpoint` and `view_func` arguments, that are useful. Also, `expose` doesn't have any reference to `add_url_rule` inside, so I don't know how to enhance it.

Can you help me?

**Comment by LotosikRa** [comment]
I have found some interesting code inside `AdminViewMeta.__init__` and `BaseView.create_blueprint` methods, but It seems to be hard to change them: all View classes inherit from them.

**Comment by LotosikRa** [comment]
[PR](https://github.com/flask-admin/flask-admin/pull/1384)

**Comment by jeanphilippegoldman** [comment]
is this PR to be able to tune the default '/admin' endpoint to stg else ? i have another plugin using 'admin' blueprint and therefore have a blueprint collision. or did i misunderstand your point.  thanks for you answer.

**Comment by petrus-jvrensburg** [comment]
@jeanphilippegoldman You can change the endpoint by specifying a value for the `url` parameter when initialising, like: `admin = admin.Admin(app, url="/stuff", name='Example App')`
