### ISSUE TITLE
Admin Exception while using translations

### ISSUE THREAD

**Issue by Keeper82** [flask-admin/flask-admin#1389]
When using `flask_babelex` for translations there is an error in the wtforms validators.
This is a minimum example to reproduce the error:
```python
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView

# ensure this installed to trigger the error
import flask_babelex

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite://'
app.config['SECRET_KEY'] = 'secret'
db = SQLAlchemy(app)

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(10), unique=True)

@app.before_first_request
def initdb():
        db.create_all()

admin = Admin(app, name='admin', template_mode='bootstrap3')
admin.add_view(ModelView(User, db.session))
app.run(debug=True)
```
Now try adding a User with 11 or more characters in the name field: it will raise a `KeyError u'max'`

I think this is because default translations in python (ie. `gettext`) just return the string without any kind of interpolation but for single/plural `wtforms` expects `min` and `max` args (or any kind of parameters) to be interpolated in the translation string.

**Comment by mrjoes** [comment]
Yes, that's a known issue, was fixed and will be in the next release.

Just in case, Flask-BabelEx is keeping backward compatibility with Flask-Babel which does exactly the same: https://github.com/python-babel/flask-babel/blob/master/flask_babel/__init__.py#L530

**Comment by Keeper82** [comment]
I think the problem lies here: https://github.com/python-babel/flask-babel/blob/master/flask_babel/__init__.py#L559
In this case the if/else on line 566 is useless because the dictionary will always have at least one value.
I'm going to edit my issue on flask-babelex reflecting this.

**Comment by mrjoes** [comment]
This was fixed in Flask-Admin explicitly. WTForms will now get compatible API without **kwargs.

**Comment by Keeper82** [comment]
You're right, I tried cloning the repo and it does work. Should we close this issue then since it's solved?

**Comment by mrjoes** [comment]
I hope to do a release by end of this week.
