### ISSUE TITLE
Select2TagsField fails if no data sent

### ISSUE THREAD

**Issue by fchennouf** [flask-admin/flask-admin#1399]
Hello,

I Have a problem with the Select2TagsField. I have a non required filled in a form represented by a Select2TagsField, and if I don't send any data for this field, the process_formdata raise an exception because valuelist is used without previous check, is it possible to check the valuelist before using it, this way:

```
if valuelist:
            if self.save_as_list:
                self.data = [self.coerce(v.strip()) for v in valuelist[0].split(',') if v.strip()]
            else:
                self.data = self.coerce(valuelist[0])
```

**Comment by ix5** [comment]
Looks good, why don't you make a pull request?
Maybe on top of #1285.
