### ISSUE TITLE
Need help on how to create custom_list.html for below scenario

### ISSUE THREAD

**Issue by malleshm** [flask-admin/flask-admin#1402]
In my project I have created one to many relation ship between 'Project(model)' and 'Slice(model)'.
First I will list out all the projects from Project model through projectmodelview.
projectmodelview/list
When I will click on any of the particular project, I want to list out slices which belongs that project.
projectmodelview/list/{}

I am not getting any proper approach as I am very new to flask.

Please help on this.

**Comment by pawl** [comment]
It might be helpful to check out the SQLAlchemy examples: https://github.com/flask-admin/flask-admin/tree/master/examples/sqla
