### ISSUE TITLE
For auth-flask-login example my_master.html extends missing file = admin/base.html

### ISSUE THREAD

**Issue by JoeCodeswell** [flask-admin/flask-admin#1403]
Hi folks,
This example seems to work for  d1191c2  8 days ago. However the my_master.html template extends a missing file = admin/base.html.

Is this bad?
Thanks for the beautiful code.
Love and peace,
Joe

**Comment by pawl** [comment]
`admin/base.html` is a template file that's part of flask-admin, so you won't see it in the example folder.
