### ISSUE TITLE
Sort column always 0

### ISSUE THREAD

**Issue by grihabor** [flask-admin/flask-admin#1414]
When html page is generated, all hrefs have sort=0 (sort column) 
So each time I try to order any table by any column, I sort it by column 0
What shall I do?

**Comment by grihabor** [comment]
![screenshot from 2017-01-18 16 34 11](https://cloud.githubusercontent.com/assets/13349050/22066073/a1545d74-dda4-11e6-9848-ada2411e8e09.png)

**Comment by grihabor** [comment]
I found the solution: jinja2 version 2.9.4 bug (feature) is in the loop
{% set y = 0 %}
{% for i in range(5) %}
        {{ y }}<br>
        {{ i }}<br><br>
        {% set y = y + 1 %}
{% endfor %}
The output: 
0 0
0 1
0 2
0 3
0 4

**Comment by grihabor** [comment]
So this causes the bug in [admin/model/list.html](https://github.com/mrjoes/flask-admin/blob/master/flask_admin/templates/bootstrap3/admin/model/list.html) lines 62-89

**Comment by lucidfrontier45** [comment]
I have same problem and already made a PR.
#1413 
waiting for being merged.

**Comment by lucidfrontier45** [comment]
@grihabor 

meanwhile, you can create a patched template extending the original list.html and use it in you app.

```py
class MyBaseModelView(BaseModelView):
    list_template = "list.html"
```

`yourapp/templates/list.html`
```html
{% extends 'admin/model/list.html' %}

{% block list_header scoped %}
{% if actions %}
<th class="list-checkbox-column">
    <input type="checkbox" name="rowtoggle" class="action-rowtoggle" title="{{ _gettext('Select all records') }}" />
</th>
{% endif %}
{% block list_row_actions_header %}
    {% if admin_view.column_display_actions %}
    <th class="col-md-1">&nbsp;</th>
    {% endif %}
{% endblock %}
{% for c, name in list_columns %}
{% set column = loop.index0 %}
<th class="column-header col-{{c}}">
    {% if admin_view.is_sortable(c) %}
        {% if sort_column == column %}
            <a href="{{ sort_url(column, True) }}" title="{{ _gettext('Sort by %(name)s', name=name) }}">
                {{ name }}
                {% if sort_desc %}
                    <span class="fa fa-chevron-up glyphicon glyphicon-chevron-up"></span>
                {% else %}
                    <span class="fa fa-chevron-down glyphicon glyphicon-chevron-down"></span>
                {% endif %}
            </a>
        {% else %}
            <a href="{{ sort_url(column) }}" title="{{ _gettext('Sort by %(name)s', name=name) }}">{{ name }}</a>
        {% endif %}
    {% else %}
        {{ name }}
    {% endif %}
    {% if admin_view.column_descriptions.get(c) %}
        <a class="fa fa-question-circle glyphicon glyphicon-question-sign"
            title="{{ admin_view.column_descriptions[c] }}"
            href="javascript:void(0)" data-role="tooltip"
        ></a>
    {% endif %}
</th>
{% endfor %}
{% endblock %}
```

**Comment by grihabor** [comment]
@lucidfrontier45
Yes, I know about that, but then I would have to put ```list_template = "path/list.html"``` in each view, which doesn't look like a good idea.
I tried overriding admin/model/list.html instead, but then all the flask admin filters stoped working :/

So now I just use Jinja2 version 2.8

**Comment by mrjoes** [comment]
Pull request was accepted, closing this one. Thank you.

**Comment by citizen-stig** [comment]
This issue is pretty serious, so I installed Flask-Admin from this repo latest master commit.

@mrjoes , could you please provide information, when new version will be released?
