### ISSUE TITLE
Access view definition in template?

### ISSUE THREAD

**Issue by steinsag** [flask-admin/flask-admin#1426]
I got a very simple requirement. The search field should show a tooltip listing all columns it searches in. However, I found no way to access the definition of the view (like column_searchable_list) in the admin/model/list.html template.

If I understand the code correctly, model/base::index_view(...) determines what is present in a template and what not. There seems to be no extension mechanism in place to add additional information to a template. Or am I missing something?

**Comment by pawl** [comment]
There's an open PR that sounds similar to this: https://github.com/flask-admin/flask-admin/pull/1278

You might be able to use some code from there?

**Comment by steinsag** [comment]
Well, it needs a core change. But I'm interested in a way to access view definition without altering core.

**Comment by xqliu** [comment]
I have been used the variable *admin_view* in list.html / lib.html / edit.html / list.html / create.html / details.html to refer to the view definition, and attributes like *column_searchable_list* is available via this *admin_view* variable in template.

Is that what you want?

**Comment by petrus-jvrensburg** [comment]
closed in #1278
