### ISSUE TITLE
Regenerate form based on request

### ISSUE THREAD

**Issue by thestick613** [flask-admin/flask-admin#1431]
I'm using the pymongo backend. I have to display a form which has several select fields. I've done it so:

```
class CustomerFieldForm(form.Form):
    # ...
    __customer_groups_choices = [(doc["customer_group"], doc["customer_group"]) for doc in db.customer_groups.find({}, {"customer_group": 1})]
    customer_groups = fields.SelectMultipleField(choices=__customer_groups_choices)
    # ...

class CustomerView(AuthModelView):
    form = CustomerFieldForm

```

Trouble is, if i delete a customer group, or create a new one, the choices on the customer_groups field remain the ones that were in the database when i first ran the application. I've found the following [hack](http://stackoverflow.com/questions/32125567/flask-admin-form-scaffolding-per-request), but i wanted to ask if there was a different, better way. It sure doesn't seem so, because i will also need to create some forms which get prefilled with choices depending on the currently logged in user. Is there another way? Thank you!

**Comment by mrjoes** [comment]
If you want to change your form dynamically, override two methods `get_create_form()` and `get_edit_form()` as they're called by the `create` and `edit` methods to get a form object instance. Then you can remove and add fields to the returned object.
