### ISSUE TITLE
Error when get_query() contains a join and you're filtering by a field from that table

### ISSUE THREAD

**Issue by benhoyt** [flask-admin/flask-admin#1432]
I have a peewee `ModelView` with an overridden `get_query()` method that contains a join, and it's causing Flask-Admin to raise a "ValueError: A join condition must be specified" exception when I filter by a field that joins to that same table.

I have two tables, `Gift` and `Registry` (many to one), and what's happening is that my `Gift.get_query()` is doing `.join(Registry)` to return a few fields from that table. But a couple of my filters are based on `Registry` fields, and for each filter, Flask-Admin's peewee [`View.get_list()`](https://github.com/flask-admin/flask-admin/blob/8d2904aa91feae2db3dd3ca07879f8c61be11eea/flask_admin/contrib/peewee/view.py#L384) calls the private [`View._handle_join()`](https://github.com/flask-admin/flask-admin/blob/8d2904aa91feae2db3dd3ca07879f8c61be11eea/flask_admin/contrib/peewee/view.py#L309) method, which adds a join for each filter that's joining to a field in another table.

But because my `get_query()` override has already done `.join(Registry)`, Flask-Admin's `get_list()` is trying to join to `Registry` again, and that's why it's complaining.

To work around this, I had to override the private `_handle_join` method. My `ModelView` subclass looks something like this:

    class GiftAdmin(peewee.ModelView):
        column_filters = (
            FilterByRegistryField(Registry.id, 'Registry ID'),
            FilterByRegistryField(Registry.slug, 'Registry Slug'),
            'time_added',
            'category',
            'name',
        )

        # I pull in some Registry fields (used by str(Gift)) to avoid N+1 queries
        def get_query(self):
            registry_fields = [Registry.slug]
            return Gift.select(Gift, *registry_fields).join(Registry)

        # Overriding this is the simplest way I could find to work around
        # the "ValueError: A join condition must be specified." problem,
        # which happens due to Flask-Admin adding the join for the
        # registry column filters even though we've already joined to
        # Registry in our get_query()
        def _handle_join(self, query, field, joins):
            return query

For reference, my `FilterByRegistryField` class allows me to filter `Gift` by a field in the joined `Registry` row, and is defined as follows:

    # This is needed because for some reason you can't add `Registry.id` directly
    # to column_filters -- it complains with:
    # Unsupported filter type <peewee.PrimaryKeyField object at 0x...>
    class FilterByRegistryField(BasePeeweeFilter):
        def apply(self, query, value):
            try:
                registry = Registry.get(self.column == value)
            except peewee.DoesNotExist:
                registry = None
            return query.where(Gift.registry == registry)

        def operation(self):
            return 'equals'

        def clean(self, value):
            return self.column.coerce(value)

Is there a better way to do this? Either way, I think `_handle_join` needs to be fixed to not re-add existing joins if they're already there (the join to `Registry` in my case).

**Comment by benhoyt** [comment]
I've fixed this in a better way now by using peewee's `.alias()` and `.switch()`. My `get_query()` now looks like this, and I can avoid the `_handle_join` hack:

    def get_query(self):
        R = Registry.alias()
        registry_fields = [R.slug]
        return Gift.select(Gift, *registry_fields).join(R).switch(Gift)

I still think it's a bit unintuitive how this works in flask-admin/peewee (and it does add an extra join to the same Registry table), but I'm not hacking `_handle_join` anymore.

**Comment by rammie** [comment]
This is still broken. It breaks when specifying filters from different related models. This leads to a ```ValueError('A join condition must be specified.')```. I think the current behavior is broken since "nests" joins with the last joined table and relies on the order of the filter fields being sensible so that the joins are nested correctly. The fix is quite straight forward. The _handle_join function in peewee contrib needs to call ```switch(self.model)``` after each call to ```join(...)```. So:

```python
    def _handle_join(self, query, field, joins):
        if field.model_class != self.model:
            model_name = field.model_class.__name__

            if model_name not in joins:
                query = query.join(field.model_class).switch(self.model)  # This is the only change
                joins.add(model_name)

        return query
```

I can submit a pull request if this makes sense.
