### ISSUE TITLE
customised properties in list view?

### ISSUE THREAD

**Issue by lambdaq** [flask-admin/flask-admin#1434]
Hi,

Is it possible to make this happen?

    class MyAdmin(ModelView):
        column_list = ['field1', 'my_admin_method', 'field3', '']

        def my_admin_method(self, obj):
            return 'obj id is %s' % obj.id

so that flask-admin will display three fields in list view template, with calculated results from `my_admin_method` ?

We can do this in Django, it's pretty convenient to make internal model field values into more human readable representations in *list view*

**Comment by pawl** [comment]
Check out the hybrid property example: https://github.com/flask-admin/flask-admin/blob/master/examples/sqla-hybrid_property/app.py#L32-L34

**Comment by lambdaq** [comment]
@pawl Thanks. it works. we can also use  `column_formatters`
