### ISSUE TITLE
Save array value as null

### ISSUE THREAD

**Issue by kaselis** [flask-admin/flask-admin#1436]
I have a constraint on the database table for array value either to be null or contain some values. However, when trying to save a form, I get integrity error, because it tries to insert empty array instead of null (None), even if I have field defined with nullable=True option. Maybe I'm just missing some option?

In my case, problem is on line [#173](https://github.com/flask-admin/flask-admin/blob/master/flask_admin/form/fields.py#L173), creates an empty list to insert, even if there are no values provided. I've managed to fix my with addition of this line, but not sure if that would be a correct solution:

`self.data = self.data if self.data else None
`

**Comment by vToMy** [comment]
I think you should handle it in the ORM. If you're using sqlalchemy you could use validators.

**Comment by kaselis** [comment]
I'm using sqlalchemy, and I would love to handle it myself, unfortunately I can't find a way (yet).

**Comment by kaselis** [comment]
Issue [#1003](https://github.com/flask-admin/flask-admin/issues/1003) seems to be very similar. I've solved mine with before_{update|insert} events.
