### ISSUE TITLE
Python 3.5 str vs bytes issue

### ISSUE THREAD

**Issue by ThaWeatherman** [flask-admin/flask-admin#1437]
I'm just using the basic ModelView and one of the columns is a sqlalchemy db.String, where db is SQLAlchemy from the flask-sqlalchemy plugin. When I edit this value in my admin view, I get the following exception: `2017-02-08 12:58:50,141 :sqlalchemy.exc.StatementError: (builtins.TypeError) memoryview: a bytes-like object is required, not 'str' [SQL: 'UPDATE item SET name=?, price=?, weight=?, picture=? WHERE item.id = ?'] [parameters: [{'picture': '', 'name': '$20 Double Eagle MS62', 'price': Decimal('1428.08'), 'weight': Decimal('0.9675'), 'item_id': 13}]]`

It would appear that the value gets passed as a string from flask-admin to sqlalchemy when sqlalchemy expects bytes. Is there a work-around for this? I can't be the first person to have this problem.

**Comment by vToMy** [comment]
I think the picture is the problem? Is it defined as a bytes type?

**Comment by ThaWeatherman** [comment]
It's a LargeBinary, yeah.

**Comment by mrjoes** [comment]
Your SQLAlchemy column definition does not match actual column type in the database. Flask-Admin does not support LargeBinary type and won't show the textbox for it.

If you really want to edit value of your LargeBinary - you can override `on_model_change` and manually convert `str` to `bytes` for the field.

**Comment by cheevahagadog** [comment]
Had the same problem. Here's how I got it to work:

```python
# utils.py
from flask_admin.contrib.sqla import ModelView

class MyModelAdmin(ModelView):

    def on_model_change(self, form, model, is_created=False):
        model.password = bytes(model.password, 'utf-8')
        pass
```

```python
# app.py
from .utils import MyModelAdmin
# ....
admin.add_view(MyModelAdmin(models.User, db.session))

```
