### ISSUE TITLE
Adding batch actions on a Model Edit form?

### ISSUE THREAD

**Issue by ye** [flask-admin/flask-admin#1448]
I've gone through quite a bit of search in length for implementing batch actions (in my case adding many-to-many relationships) to be embedded in Model's Edit form.

I am aware of the [Customizing Batch Actions](http://flask-admin.readthedocs.io/en/latest/advanced/#customizing-batch-actions) on a Model List view but is there a quick way to do this in the model's Edit form view? If not, can someone provide some insights as to how to do it canonically? Thanks.

**Comment by petrus-jvrensburg** [comment]
No, there's no simple way. 

If I'm understanding correctly, then you're trying to do batch actions on the related models. One workaround may be to rather add a link to a filtered list-view showing only those records. And then handle the batch actions in that filtered list view.

Please let us know if you came up with an solution.
