### ISSUE TITLE
Enter custom value in QuerySelectField

### ISSUE THREAD

**Issue by kmagonski** [flask-admin/flask-admin#1458]
Hi, 
I have problem to create editable select. 
The user should choose to pick from the list or add a new value. 
I read many help for select2, flask-admin and nothing..
I use ```QuerySelectField```.
Can You help me?

**Comment by petrus-jvrensburg** [comment]
I can't think of a simple way to do this. 

My approach would be to have two fields: a select and a text input field. Add a "new item" option to the select, and in your javascript, show/hide the text field depending on the select field's state.
