### ISSUE TITLE
AttributeError: 'Mapper' object has no attribute 'x' on longer column filter chains longer

### ISSUE THREAD

**Issue by jonozzz** [flask-admin/flask-admin#1466]
This seems to be a new behavior in 1.5.0, and a regression from 1.4.2.
I have an admin view that has a column filter that looks like this "order.product.sku":

```
class ItemView(AuthenticatedModelView):
    column_filters = ('order.userid', 'order.email', 'order.product.sku')
```

Tracestack:
```
[..]
  File "/home/pi/.virtualenvs/myenv/lib/python3.4/site-packages/flask_admin/contrib/sqla/view.py", line 329, in __init__
    menu_icon_value=menu_icon_value)
  File "/home/pi/.virtualenvs/myenv/lib/python3.4/site-packages/flask_admin/model/base.py", line 782, in __init__
    self._refresh_cache()
  File "/home/pi/.virtualenvs/myenv/lib/python3.4/site-packages/flask_admin/model/base.py", line 903, in _refresh_cache
    self._refresh_filters_cache()
  File "/home/pi/.virtualenvs/myenv/lib/python3.4/site-packages/flask_admin/model/base.py", line 811, in _refresh_filters_cache
    self._filters = self.get_filters()
  File "/home/pi/.virtualenvs/myenv/lib/python3.4/site-packages/flask_admin/model/base.py", line 1113, in get_filters
    flt = self.scaffold_filters(n)
  File "/home/pi/.virtualenvs/myenv/lib/python3.4/site-packages/flask_admin/contrib/sqla/view.py", line 617, in scaffold_filters
    is_hybrid_property = tools.is_hybrid_property(self.model, name)
  File "/home/pi/.virtualenvs/myenv/lib/python3.4/site-packages/flask_admin/contrib/sqla/tools.py", line 200, in is_hybrid_property
    attr = getattr(last_model, names[i])
AttributeError: 'Mapper' object has no attribute 'product' 

```

**Comment by vToMy** [comment]
Can you show me how the `Item` and `Order` models is defined?

**Comment by jonozzz** [comment]
Sorry for the delay, here's a stripped down model:

> class Item(db.Model):
>     id = db.Column(db.Integer, primary_key=True)
>     created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow)
> 
>     order_id = db.Column(db.Integer, db.ForeignKey('order.id',
>                                                    onupdate="CASCADE",
>                                                    ondelete="CASCADE"),
>                          nullable=False)
>     
> class Product(db.Model):
>     id = db.Column(db.Integer, primary_key=True)
>     name = db.Column(db.String(128), nullable=False)
>     sku = db.Column(db.String(128), nullable=False)
> 
> class Order(db.Model):
>     id = db.Column(db.Integer, primary_key=True)
>     timestamp = db.Column(db.DateTime, nullable=False,
>                           default=datetime.datetime.utcnow)
>     product_id = db.Column(db.Integer, db.ForeignKey('product.id',
>                                                      onupdate="RESTRICT",
>                                                      ondelete="RESTRICT"),
>                            nullable=False)
>     product = db.relationship('Product', backref='orders', )
>

**Comment by vToMy** [comment]
Can't seem to reproduce the problem...
Can you provide a complete minimal example that isn't working for you?

**Comment by jonozzz** [comment]
Ok, I dug down a little bit and narrowed it to the way the relationship is defined between models:

```python
#works
class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)

class Order(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    #items = db.relationship('Item', backref='order', passive_deletes="all")

class Item(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    order_id = db.Column(db.Integer, db.ForeignKey('order.id', onupdate="CASCADE", ondelete="CASCADE"),
                         nullable=False)
    order = db.relationship('Order', backref='items')


#no longer works:
class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)

class Order(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    items = db.relationship('Item', backref='order', passive_deletes="all")

class Item(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    order_id = db.Column(db.Integer, db.ForeignKey('order.id', onupdate="CASCADE", ondelete="CASCADE"),
                         nullable=False)
    #order = db.relationship('Order', backref='items')


# the view with the filter that's causing the exception
class ItemModelView(AuthenticatedModelView):
    column_filters = ('order.product.sku', )
```

I might also be doing something wrong, and it just happened to work before 1.5.0. Please advise.

**Comment by vToMy** [comment]
The example is not complete - order has no `product` member, product has no `sku` member...
When I tried to configure it myself last time, it just worked.
So I'm gonna have to ask to you to provide a complete example. Something I can copy and run.

**Comment by jonozzz** [comment]
Nevermind, I'll just work around the issue.

Thanks!

**Comment by bepetersn** [comment]
Here's a working example of this error which I saw: https://github.com/bepetersn/flask-admin-example1. Not sure what the error means, maybe you want to look into it. However, on further playing with this, I discovered how to do what I needed to do. I had this:

```AdminJobView(AdminModelView):
    model = Job
    column_display_pk = True
    # Including this filter breaks
    column_filters = ('order_id', 'order.location.name', ) 
```

I changed to this:

```AdminJobView(AdminModelView):
    model = Job
    column_display_pk = True
    # Including this filter breaks
    column_filters = ('order_id', 'order.location', ) 
```

and `order.location.name` became an available filter.
