### ISSUE TITLE
select2 version bump?

### ISSUE THREAD

**Issue by SophiaAP** [flask-admin/flask-admin#1467]
Hello! First of all, thank you to @mrjoes, @pawl, and all the other contributors. This is such an awesome and easy to use extension. Python is not my main language but I've been using it at work recently and Flask Admin is making me look like a way better developer than I actually am :) 

Anyway, I noticed some slowness on one of my select/autocomplete dropdowns (~30,000 rows of data) and tracked it down to this issue: [Select2 is slow on opening #781](https://github.com/select2/select2/issues/781), which appears to have been resolved as of 3.5.3 (Flask Admin is on 3.5.2). 

I'm not sure if you guys have considered bumping to a newer version of Select2 so I just wanted to check. I played around with bumping the dependency to 3.5.3 and 4.0.3 (latest release) and the newest version is much faster for dropdowns with large data sets. I'm unfamiliar with this space and not confident that it didn't break other areas of your app, though, so I'm a little hesitant to submit a pull request. 

Anyway, just something to consider. Thanks again for all your work on this!

(Possibly relates to [sqla relationship select2widget fails with many items selected #1075](https://github.com/flask-admin/flask-admin/issues/1075))

**Comment by mrjoes** [comment]
That would only mask the issue. Try enabling AJAX lookups if Select2 is used for the foreign key management.

**Comment by SophiaAP** [comment]
Ok cool. Thank you.

**Comment by jsmolina** [comment]
it's more about rendering, if there's a huge amount of one to many relationship items

I also vote for updating the select2 library
