### ISSUE TITLE
About include hybrid_property in QueryAjaxModelLoader fields parameter

### ISSUE THREAD

**Issue by xqliu** [flask-admin/flask-admin#1471]
Dear,

I found that it's not possible to  include hybrid_property in QueryAjaxModelLoader fields parameter,

Is there any way that I could do an AJAX look up based on hybrid property using the out of the box QueryAjaxModelLoader?

Thanks.

**Comment by vToMy** [comment]
I could look into it. Can you provide and example that you would expect to work?

**Comment by xqliu** [comment]
Thanks for your help @vToMy 

For example, I have a model: Customer, it has two fields: first_name and last_name.

Then a hybrid properties name is created as first_name + last name.

For example in Chinese, one person's first name is 张，and last name is 三，then the hybrid property name will be 张三

Ideally it's good if we could filter by "张三" when do Ajax searching, because search by "张" or "三" is both too wide and there will be too many results return back.

While on current version, when we search by 张三, no record will be returned because does not match "张" or "三".

Thanks.

**Comment by vToMy** [comment]
I meant like a sample code I could run.
I've added general support for hybrid properties in flask-admin, but I'm not familiar with `QueryAjaxModelLoader` or how to use it.

**Comment by vToMy** [comment]
Actually I just tried this and it works with hybrid_properties, so if something's not working for you I'd need an example.
