### ISSUE TITLE
Nested inline models

### ISSUE THREAD

**Issue by ikkev** [flask-admin/flask-admin#1472]
Given the following situation: We have a supplier that has products, and we have translations of the product. 
I want to be able to add or edit these all in one form using nested inline models.
Supplier, Product and ProductTranslation all have their own models.

I'm able to create nested inline models using the following (simplified) code:
```
class ProductView(ModelView):
    form_columns = ['id', 'internal_name']

    inline_models = [
        (ProductTranslation, dict(form_columns=['id', 'lang', 'name', 'description']), ),
    ]

class SupplierView(ModelView):
    inline_models = [
        ProductView(Product, db.session),
    ]
```
I'm required to pass the id in the form_columns for the ProductView, else I will get an "object has no attribute 'id'" error during save.
But this will also show id as a field in the form. But people should not fill in the id field, it should be automatically generated by the database when saving.

If I use an InlineFormAdmin instead of an ModelView for ProductView I can't use the inline_models property.
If I just disable the id field it will throw required errors.

How can I hide the id field without getting an error during save?
Or is there a better way to have nested inline models?

**Comment by ikkev** [comment]
Kind of fixed it by doing this:

```
class ProductView(ModelView):
    form_columns = ['id', 'internal_name']
    form_widget_args = {
        'id': {'placeholder': 'new id will be automatically created', 'readonly': True},
    }

    inline_models = [
        (ProductTranslation, dict(form_columns=['id', 'lang', 'name', 'description']), ),
    ]

class SupplierView(ModelView):
    inline_models = [
        ProductView(Product, db.session),
    ]
```

And I set the id property in the Product model to nullable=True, so that I won't get a required error.
Not really happy that I had to set the primary key to nullable=True.

```
class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True, nullable=True)
    internal_name = db.Column(db.String(200))
```

**Comment by KyleXie** [comment]
Hi @ikkev , I tried you solution here, it works well until I edit the one Supplier, after I click the save button and check it again, I found the Products turns double, say the Supplier had 2 Products before I edit it, after I save it without change any thing, it duplicated 2 more Products for that Supplier. Do you have any solution for this issue? Thanks very much.

**Comment by ikkev** [comment]
@KyleXie 
I'm not getting that situation. So I can't reproduce it.
When you check the 2 products, do they show a value in the readonly id fields?
Are you sure there is no other code duplicating these products?

**Comment by KyleXie** [comment]
Hi @ikkev,

Thanks very much for you reply. It turns out to be an issue of flask-admin. You can see it from here: https://github.com/flask-admin/flask-admin/issues/1536. I also made a simple fix for this issue: https://github.com/flask-admin/flask-admin/pull/1535.

**Comment by The-EDev** [comment]
7 years later for anyone interested in this:

The way to prevent the nullable pk is to override the view's `scaffold_form()` function and add `hidden_pk=True` to `form.get_form()` call. here's the full code that needs to be added to the nesting view:

```python
    def scaffold_form(self):
        """
            Create form from the model.
        """
        converter = self.model_form_converter(self.session, self)
        form_class = form.get_form(self.model, converter,
                                   base_class=self.form_base_class,
                                   only=self.form_columns,
                                   exclude=self.form_excluded_columns,
                                   field_args=self.form_args,
                                   hidden_pk=True,
                                   ignore_hidden=self.ignore_hidden,
                                   extra_fields=self.form_extra_fields)

        if self.inline_models:
            form_class = self.scaffold_inline_form_models(form_class)

        return form_class
```
The function was copied from flask-admin's sqla source code
