### ISSUE TITLE
Blueprint name collisions

### ISSUE THREAD

**Issue by brianbaquiran** [flask-admin/flask-admin#1474]
Would it be possible to specify a blueprint name in `add_view` to help avoid name collisions with preexisting blueprints?

I am adding flask-admin to an existing app with several blueprints and keep getting this:
`AssertionError: A blueprint's name collision occurred between <flask.blueprints.Blueprint object at 0x7f88203280b8> and <flask.blueprints.Blueprint object at 0x7f88205bf080>.  Both share the same name "escalation".  Blueprints that are created on the fly need unique names.`

Right now my workaround is to rename the existing blueprint.

**Comment by mrjoes** [comment]
You can pass `endpoint` argument to your admin view class to specify a different name and avoid the collision.

**Comment by K-7** [comment]
Even after changing the endpoint, still the issue persists. 

**_Package Verison_**
Flask-Admin==1.5.2
Flask == 1.0.2

**_Initialisation code_**
admin_control = Admin(name='Saiva', endpoint='bp_admin')
admin_control.init_app(app, index_view=admin.AdminView())

Here Iam overriding the Admin view 

Kindly help me out
