### ISSUE TITLE
Conditionally disable 'can_create'

### ISSUE THREAD

**Issue by macfire** [flask-admin/flask-admin#1480]
I need to limit a table to max of 1 record. So I would like to conditionally enable/disable the 'can_create' action accordingly.

Where would this condition be specified?
Can this condition be set in the ModelView (for example, like when using `on_model_change()`)?
For example, `is_accessible()` can be caledl in the ModelView to determine whether to show to user.

I first thought `is_action_allowed(name)` would accomplish my goal, but realized it gets a value, not sets.

**Comment by vToMy** [comment]
I think you can override it with a property so you could insert logic.

**Comment by macfire** [comment]
Thank you. That works.

Example:
```python
    @property
    def can_create(self):
        val = 1
        if val >= 1:
           return False
        elif val < 1:
           return True
```

**Comment by cswkim** [comment]
In the property override can you have conditional logic based on a row's (list object) attribute value? `self.model` returns just the model class. How could I conditionally show an action, like edit, based on the row's `is_active` attribute for example.
