### ISSUE TITLE
column_formatters formatting details view as well? 

### ISSUE THREAD

**Issue by vincentwhales** [flask-admin/flask-admin#1487]
According to the docs, `column_formatters` is supposed to be formatting just the list views. 

> Dictionary of list view column formatters.

However, I realized that column_formatters is applies to details_view as well. 

Is this a feature or a bug? 

What can I do if I want to format a few specific columns in ONLY the list_view?

**Comment by amoyiki** [comment]
You can see [details_view](https://github.com/flask-admin/flask-admin/blob/master/flask_admin/model/base.py#L2106)
and [get_list_value](https://github.com/flask-admin/flask-admin/blob/master/flask_admin/model/base.py#L1802)

**Comment by tiktuk** [comment]
I was also surprised to discover this. Did you find a solution, @vincentwhales?
