### ISSUE TITLE
RTL Support?

### ISSUE THREAD

**Issue by galvinograd** [flask-admin/flask-admin#1489]
Hey,

I'm working on a project that requires full Hebrew support. Because there is currently no right-to-left in flask-admin, I had to fork the project and add it myself.

I used [bootstrap-rtl](https://github.com/morteza/bootstrap-rtl), and all I had to do is add two css files, and a .flip class for pull-left or pull-right kind of situations. The feature flag resided in flask config, which made the wiring way easier. I tested it against various examples, so select2 and inline models works well. Unfortunately I didn't add support for bootstrap 2 as the library is only compatible with bootstrap 3.x. 

I think it would be an excellent addition to the project, as many languages such as Hebrew and Arabic must have rtl in order to be useful.

What do you think?

**Comment by petrus-jvrensburg** [comment]
Thanks @galvinograd. 

There doesn't seem to be a lot of interest, so let me close this issue. But help on any of the other open issues would be appreciated.
