### ISSUE TITLE
Database not created after app.run()

### ISSUE THREAD

**Issue by zave** [flask-admin/flask-admin#1498]
Is there something missing from app.py in the auth-flask-login example project that prevents it from creating the database when the application is started? I have done 'flask run' and I have included every single file in that project line by line and yet I keep getting the error telling me that there is no user table. This happens when I try to login as the test user. 

The README says that the first time you run the app, the database will be created, but that does not appear to be the case. I must be doing something wrong, or app.py is incomplete, and/or there's something i'm supposed to know, but don't.

So again, to be clear, is there something missing from app.py that prevents it from being able to create the database, that maybe I'm supposed to add?

**Comment by AdamGS** [comment]
Have you tried running it with just the "python" command (like in the README)?

**Comment by zave** [comment]
@AdamGS You're probably right...I ended up doing something different, as I needed to deploy it with nginx/uwsgi.
