### ISSUE TITLE
Reflected XSS

### ISSUE THREAD

**Issue by dmchell** [flask-admin/flask-admin#1503]
We're using this framework internally within a flask app and a colleague noted a reflected XSS issue:

Example:
https://10.0.0.1/admin/user/edit/?url=%20javascript%3aalert(document.domain)&id=8

User interaction is required, when clicking the "List" link the javascript is executed.

**Comment by dmchell** [comment]
The affected file appears to be https://github.com/flask-admin/flask-admin/blob/d57048b041c737f8f4b61f9a2260fc0607dff2aa/flask_admin/helpers.py

**Comment by pawl** [comment]
It looks like we're going to need a more robust version of `is_safe_url`.

It looks like django's handles it correctly:
```
>>> from django.utils.http import is_safe_url
>>> is_safe_url('/admin/car/')
True
>>> is_safe_url(' javascript:alert(document.domain)')
False
```

Their version of is_safe_url is pretty complex and I'm sure which line is causing it to return false yet. Here's a link to the file it's in: https://github.com/django/django/blob/550cb3a365dee4edfdd1563224d5304de2a57fda/django/utils/http.py

**Comment by lbhsot** [comment]
any progress?
