### ISSUE TITLE
URL build error bug in /templates/bootstrap3/admin/static.html

### ISSUE THREAD

**Issue by leon0707** [flask-admin/flask-admin#1530]
https://github.com/flask-admin/flask-admin/blob/master/flask_admin/templates/bootstrap3/admin/static.html

```
{{ get_url('admin.static', *varargs, **kwargs) }}
```

`admin.static` would produce build error if there is an existing 'admin' blueprint.

    sys_admin = Admin(name='Conferency', template_mode='bootstrap3',
                      endpoint='administration', url='/admin/dbop')

It should be a variable instead of `admin.static`

**Comment by Shookit** [comment]
I run into this same issue on bootstrap2; it doesn't seem to be an issue on flask-admin 1.4.0, just on 1.5.0

**Comment by Shookit** [comment]
https://github.com/flask-admin/flask-admin/issues/1530

**Comment by alex1007** [comment]
@Shookit https://github.com/flask-admin/flask-admin/blob/4ff21f1223c3235e858834513de4417ce44363fa/flask_admin/templates/bootstrap3/admin/static.html

url_for will generate the same exception.
