### ISSUE TITLE
`ignore_hidden` doesn't work

### ISSUE THREAD

**Issue by antoine-lizee** [flask-admin/flask-admin#1541]
When using the class attribute `ignore_hidden`of the `sqla.ModelView`, the create and edit forms are still missing the attributes that start with and underscore.

What it does in flask-admin: it alters the behavior of the form scaffolding at init of the model (in `_refresh_forms_cache`) by including the hidden columns in the form classes for `self._create_form_class` and `self._edit_form_class`.

But, when the forms get actually instantiated in the `create_view` and `edit_view`, it defers to the `Form` class of `WTForms`. This class does skip the hidden columns automatically when creating the list of fields that should be bound to the form (see `FormMeta.__call__`). Actually their documentation states:

>Field names can be any valid python identifier, with the following restrictions:
>
>[...]
>Field names may not begin with “_” (underscore)

1. Have I missed something?
2. Is there a potential fix for it? I see only renaming the hidden attribute and remove the underscore at form scaffolding.
3. Or should we remove the misleading `ignore_hidden` field?

**Comment by mrjoes** [comment]
That's a limitation of the underlying forms library WTForms: http://wtforms.simplecodes.com/docs/0.6.1/forms.html#defining-forms

Unfortunately there's no way to fix it without moving away from WTForms.
