### ISSUE TITLE
Different create_form and edit_form with @property in model class

### ISSUE THREAD

**Issue by vincentwhales** [flask-admin/flask-admin#1550]
This is my goal: 

```
create_form: 
- new_file: FileUploadField which allows my users to upload files to my webserver

edit_form:
- new_file: FileUploadField which allows users to upload a new file to replace the existing file
- current_file: anchor link to download the file or text which says "No file to download"

```
I've decided to add a custom property to my model Instruction:

```
class Instruction(DBModel):
  gdrive_id = db.Column(db.String(64))

  @property
  def current_file(self):
    if self.gdrive_id:
      return Markup("<a href='%s'>Click here to download</a>" % \
                    url_for("instruction.download_and_send", gdrive_id=self.gdrive_id))
    else:
      return "No file uploaded."
```

And i've decided to implement this in my ModelView:

```
  form_extra_fields = {
    'new_file': form.FileUploadField(label='Instruction File',
                                     base_path=BASE_PATH, allowed_extensions=None),
  }

  form_create_rules = [
    rules.Field('new_file'),
  ]

  form_edit_rules = [
    rules.Field('new_file'),
    rules.Field('current_file'),
  ]
```

Unfortunately when I visit my edit view page I am getting the following error: 

> ValueError: Form <flask_admin.contrib.sqla.form.InstructionForm object at 0x10d234110> does not have field current_file

It seems like Flask-admin is not mapping the `current_file` property to the form to be rendered as HTML for the edit_form. 

##How can I fix this? 

**Note**
I've tried adding current_file into form_extra_fields but this does not seem to work as I have no access to the model instance at the scope of form_extra_fields

**Comment by lrhhhhhh** [comment]
Hello, I'm having a similar problem. Are there any solutions?
