### ISSUE TITLE
[Broken] Examples site `http://examples.flask-admin.org/` is broken

### ISSUE THREAD

**Issue by s-chand** [flask-admin/flask-admin#1564]
The examples site as well as the main website http://flask-admin.org is broken.

**Comment by jxltom** [comment]
It looks like it woks fine now.

**Comment by Jenselme** [comment]
It looks broken today.

**Comment by petrus-jvrensburg** [comment]
Fixed. Thanks!

**Comment by Jenselme** [comment]
Thanks for the quick fix!
