### ISSUE TITLE
Use flask-s3

### ISSUE THREAD

**Issue by SBillion** [flask-admin/flask-admin#1566]
How can I configure flask-admin to work with flask-s3? get_url() is used insted of url_for() so flask-s3 can't override the domain name when accessing to static files and files still served in local which make me :cry:

**Comment by SBillion** [comment]
Up

**Comment by mrjoes** [comment]
`get_url` uses `url_for` internally. You can override `get_url` in your base admin class if you want to customize the behavior and/or support S3 links.

**Comment by SBillion** [comment]
Yes, it was really easy in fact. I just didn't think to override get_url() to user flask_s3.url_for() instead of flask.url_for(). Thank you. Maybe I could add this exemple of get_url overriding to flask-admin documentation or you think this is not the place for it?
