### ISSUE TITLE
DATETIME field missing years with column_editable_list

### ISSUE THREAD

**Issue by mrhaoji** [flask-admin/flask-admin#1568]
<img width="607" alt="flask_issue" src="https://user-images.githubusercontent.com/483419/33476266-5729b82c-d6bc-11e7-8671-94b7e6acd644.png">

I have set one of the fields, which is DATETIME type in the sqlite, into the column_editable_list, like this:

column_editable_list = ['finish_time']

However, where trying to edit it inline the year number only goes to 2015.
Any way to fix this?

**Comment by adamrt** [comment]
Check in #1543 to see if that solves your problem

**Comment by mrhaoji** [comment]
I have already check that.

I'm using the Flask-Admin 1.5.0, and the version of bootstrap.min.js file is 3.3.5, which I think is not the problem. But the year number still goes up to 2015.

**Comment by mrhaoji** [comment]
https://github.com/flask-admin/flask-admin/commit/5fff53bc95466317cdff3c68a1b4d748666bf8b7

I have followed this commit above to make a change to the file: /flask_admin/static/admin/js/form.js

Everything goes well now!
