### ISSUE TITLE
[BUG]year can not can be set larger than 2016 for db.DateTime type of SQLAlchemy when using as column_editable_list

### ISSUE THREAD

**Issue by jxltom** [flask-admin/flask-admin#1569]
![image](https://user-images.githubusercontent.com/1401630/33477954-9342e8a0-d6c2-11e7-9795-854c5d5ad236.png)

I am using flask-admin==1.5.0 with python3.6.2 and ```FLASK_ADMIN_SWATCH = 'simplex'```, ```template_mode = 'bootstrap3'```

**Comment by adamrt** [comment]
@jxltom Is this a duplicate of #1568

**Comment by adamrt** [comment]
Check in #1543 to see if that solves your problem

**Comment by jxltom** [comment]
Thanks. This is a duplicate. Besides, 5fff53bc95466317cdff3c68a1b4d748666bf8b7 fixed this problem.
