### ISSUE TITLE
get_url() aways return to the first page

### ISSUE THREAD

**Issue by mrhaoji** [flask-admin/flask-admin#1574]
Maybe not a issue, but I haven't figure it out...

    @expose('/remove/', methods=('GET',))
    def remove(self):
        return_url = self.get_url('.index_view')
        ...
        ...
        return redirect(return_url)

As shown above, this remove() function works well if user is user the url http://127.0.0.1:5000/admin/show/.

However, when user is browsing other pages, like http://127.0.0.1:5050/admin/show/?page=5, it will go back to http://127.0.0.1:5050/admin/show/ after he/she click the remove button.

Any solution? Or more info. abt the get_url() function?

**Comment by SBillion** [comment]
get_url() works like url_for. You have to specify the query parameters or url_for won't add them in the generated url.
This what you could do
`        return redirect(self.get_url('.index_view', **request.args))
`

**Comment by mrhaoji** [comment]
return_url = request.referrer

code above fixed my problem
