### ISSUE TITLE
select2 filter selection fails

### ISSUE THREAD

**Issue by slint** [flask-admin/flask-admin#1576]
The handler in [`filters.js`](https://github.com/flask-admin/flask-admin/blob/master/flask_admin/static/admin/js/filters.js#L38), is accessing the selected items in a wrong fashion (or maybe the `select2` API changed at some newer version?)

The correct way to [retrieve the selection from a select2 dropdown](https://select2.org/programmatic-control/retrieving-selections#using-the-data-method) should be:

```javascript
$select.select2('data')[0].element.index
```

**Comment by mrjoes** [comment]
Pull request is welcome.
