### ISSUE TITLE
Python 2.6 build is failing

### ISSUE THREAD

**Issue by jbochi** [flask-admin/flask-admin#1591]
SQLAlchemy 1.2 now requires Python 2.7 or higher: http://docs.sqlalchemy.org/en/latest/intro.html#supported-platforms, so the build is now failing.

For example: https://travis-ci.org/flask-admin/flask-admin/jobs/330586924#L733

What should we do? Use SQLAlchemy 1.1.x or drop Python 2.6 support too?

**Comment by hugovk** [comment]
Here's the pip installs for flask-admin from PyPI for last month, showing low numbers for 2.6 (and 3.3, which are both EOL and no longer receiving security updates from the core team):

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |   54.9% |         28,273 |
| 3.6            |   25.3% |         13,043 |
| 3.5            |   13.3% |          6,869 |
| 3.4            |    6.2% |          3,185 |
| 3.7            |    0.1% |             38 |
| 2.6            |    0.1% |             27 |
| 3.3            |    0.0% |             21 |
| None           |    0.0% |              1 |

Source: `pypinfo --start-date -49 --end-date -19 --percent --pip --markdown flask-admin pyversion`
