### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by bolkedebruin** [flask-admin/flask-admin#1603]
Hi,

It would be awesome if you guys could release a new version of Flask-Admin. I'm interested specifically in this to allow upgrading to SQLAlchemy 1.2 in our projects, which isn't possible at the moment.

Can you consider this please?

Cheers

**Comment by mrjoes** [comment]
Sorry for neglecting this project, but new release with all latest fixes is going live a little later this week.

**Comment by mrjoes** [comment]
This was actually complete.
