### ISSUE TITLE
Flask-Admin and React/React-Router

### ISSUE THREAD

**Issue by cinjon** [flask-admin/flask-admin#1605]
I have a setup with ReactJS where the routing is handled client sided by React-Router.

Flask-Admin sets up routes prefixed by '/admin'. However, when trying to use these together, the React-Router is clobbering the calls to Flask-Admin.

Is there a way to use Flask-Admin as a REST service and then I could call it from the client to yield the entire template?

**Comment by mrjoes** [comment]
Unfortunately no - Flask-Admin is not a REST framework and probably won't work great with single-page apps. Closing this for now.
