### ISSUE TITLE
contrib peewee form.py

### ISSUE THREAD

**Issue by jefmud** [flask-admin/flask-admin#1606]
We need to change the imports in contrib.peewee 'form.py' to accomodate Charles Leifer's 3.0 release of Peewee ORM that has a slight modificaion to the metaclass. Charles says: "peewee.BaseModel (and latterly peewee.ModelBase) is the metaclass that is used to create Model classes."  Replacing the definition of the BaseModel will make this compatible with both the 2.x and 3.x releases of Peewee.

This modification below will ensure compatibility.  Thanks for all your great work on Flask-Admin!!

```python
from peewee import (CharField, DateTimeField, DateField, TimeField,
                    PrimaryKeyField, ForeignKeyField)
try:
    from peewee import BaseModel
except ImportError:
    from peewee import ModelBase as BaseModel
```

**Comment by mrjoes** [comment]
I just accepted a pull request and this was fixed.
