### ISSUE TITLE
Peewee example not working anymore

### ISSUE THREAD

**Issue by albatros69** [flask-admin/flask-admin#1639]
Hello,
I'm trying to use Flask-Admin with Peewee in a fresh virtualenv with the latest versions of the requirements. I get weird errors, even on the provided example:

    AttributeError: <ForeignKeyField: "userinfo"."user"> has no attribute related_name, nor is it a valid field on <class '__main__.User'>.

Is there any know issues with the last version of Flask or peewee, or strange interactions between all of them?

Below the versions I'm using:

    Flask==1.0
    Flask-Admin==1.5.1
    peewee==3.3.1
    wtf-peewee==3.0.0

Thanks in advance for your help,

**Comment by albatros69** [comment]
After some digging, it seems related to changes introduced in Peewee 3.0. See https://peewee.readthedocs.io/en/latest/peewee/changes.html.

After replacing `related_name` with `backref` and `model_class` with `model`, it seems to work again properly. Please review and merge already existing PR #1612 to solve this.

**Comment by ngomile** [comment]
Oh okay I understand, thank you.

**Comment by alfonsodg** [comment]
Hi, a warning: the package flask-admin is outdated and doesn't includes this fixes... I need to uninstall the pip package, clone the repo and install to the old way: python setup.py install

**Comment by petrus-jvrensburg** [comment]
fixed in #1612
