### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by stringfellow** [flask-admin/flask-admin#1663]
As per issue #712 

There has been no release in over a year and there are 92 commits in master that are not in v1.5.0

There's nothing particularly that I need in master, but it does seem like a long time to go without releasing when so much has been added to master.

**Comment by TimotheeJeannin** [comment]
I would love to see a new release too. Especially for this PR : https://github.com/flask-admin/flask-admin/pull/1620

**Comment by cpaulik** [comment]
There actually was a release on the 6th of March but it is not reflected in the Github releases. See https://pypi.org/project/Flask-Admin/#history

**Comment by ufo911** [comment]
There are many feature requests or issues

**Comment by tuukkamustonen** [comment]
Also would like to get new release (for peewee 3 support).

**Comment by tuukkamustonen** [comment]
Seems like 1.5.2 was just released so I assume this ticket can be closed. Thank you @mrjoes!
