### ISSUE TITLE
Ability to change the variable start string

### ISSUE THREAD

**Issue by callkalpa** [flask-admin/flask-admin#1665]
I am using flask, flask-admin with Vue JS in an application. Since Vue JS has the variable replacement string as `{{` I have done the following changes in my flask application to avoid any conflicts between flask templates and Vue JS,

```
jinja_options = Flask.jinja_options.copy()
    jinja_options.update(dict(
        variable_start_string='[[',
        variable_end_string=']]',
        block_start_string='[%',
        block_end_string='%]'
    ))
```
Now, when I try to access flask-admin, I get the following,
```
{% extends 'admin/master.html' %} {% block body %} {% endblock %}
```

Is there anyway (a configuration may be) I can change the variable start/end strings in flask-admin?

**Comment by mrjoes** [comment]
Unfortunately, the only way to do it is to override all Flask-Admin templates.

Alternatively, you can reverse it - create your own Jinja2 context for your templates and inject necessary variables (`request`, `g`, etc) when you render your Vue templates.

**Comment by callkalpa** [comment]
For now I managed to overcome the issue by changing the delimeter in Vue as follows. Since I am using a number of flask extensions, I think this way would be a better approach.

`delimiters: ['[[', ']]']`
