### ISSUE TITLE
Mixed content error

### ISSUE THREAD

**Issue by rtgnx** [flask-admin/flask-admin#1696]
My app is behind nginx proxy with ssl enabled.
When I try to edit any row in model view it makes XHR request
which uses http instead of https.

![screenshot-1535797247](https://user-images.githubusercontent.com/6417350/44945143-8d4e6100-adda-11e8-89ba-1792c7f7186f.png)

Would it be possible to make request using scheme from`window.location.protocol` ?

**Comment by SBillion** [comment]
This is not a Flask-Admin bug. You didn't set the [PREFERRED_URL_SCHEME](http://flask.pocoo.org/docs/1.0/config/#PREFERRED_URL_SCHEME) constant in your config.py file.

**Comment by rtgnx** [comment]
I did set that constant but it doesn't seem to do anything.

**Comment by SBillion** [comment]
Did you try to apply ProxyFix on you wsgi_app 

```
from werkzeug.contrib.fixers import ProxyFix

application = create_app(os.environ.get("FLASK_CONFIG") or "default")
application.wsgi_app = ProxyFix(application.wsgi_app)

```

**Comment by rtgnx** [comment]
That solved the problem. Thank you !

**Comment by SBillion** [comment]
Cool :)

Can you close the ticket?
