### ISSUE TITLE
FileAdmin Inline Remove Button The CSRF token is missing.

### ISSUE THREAD

**Issue by ufo911** [flask-admin/flask-admin#1697]
When pressing Inline X (remove) button page says 

> The CSRF token is missing

 in FileAdmin

**Comment by PeterKharchenko** [comment]
same issue here - all other operations with files/folders work ok, but inline remove is causing "400 BAD REQUEST The CSRF token is missing". CSRF is enabled via flask_wtf.csrf CSRFProtect
