### ISSUE TITLE
"This field is required" shown for disabled fields

### ISSUE THREAD

**Issue by cancan101** [flask-admin/flask-admin#1701]
I have marked some fields as disabled. However when I try to submit the edit form I get "This field is required". I suggest either the required check is omitted (especially since there are actual values in the field) and / or if there is a work around the docs be updated.
![image](https://user-images.githubusercontent.com/51059/45232637-14e61500-b29e-11e8-9765-21c6a3ed892e.png)

**Comment by petrus-jvrensburg** [comment]
How are you marking this as disabled? 

I'm struggling to reproduce this.

**Comment by petrus-jvrensburg** [comment]
P.S. I'm disabling the field by setting the 'readonly' attribute that's passed to the form field widget, e.g:

```
form_widget_args = {
    'id':{
        'readonly':True
    },
    'email':{
        'readonly':True
    },
}
```

**Comment by cancan101** [comment]
I am using ``disabled`: True`.
