### ISSUE TITLE
What is the license of the auth example?

### ISSUE THREAD

**Issue by moar55** [flask-admin/flask-admin#1702]

**Comment by alanhamlett** [comment]
https://github.com/flask-admin/flask-admin/blob/master/LICENSE

**Comment by moar55** [comment]
so i basically need to add the license to my project?
I am using it for commercial purpose

**Comment by alanhamlett** [comment]
No, the license is BSD or MIT not sure but both only require you to include the license when re-distributing a copy of the Flask-Admin source code.
