### ISSUE TITLE
"examples" package erroneously installed

### ISSUE THREAD

**Issue by pganssle** [flask-admin/flask-admin#1706]
Because there's an `examples/__init__.py` file in the repo, [this line of setup.py](https://github.com/flask-admin/flask-admin/blob/08bdcdea27fed6dcef7627bf7d2ac0625c4c2a9c/setup.py#L54) is erroneously deciding to install two packages, `flask-admin` and `examples`. I suspect other packages make this same mistake, which can lead to some file conflicts during installation.

It would be best to either change your `find_packages` invocation to blacklist `exclude`:

```python
find_packages(exclude=['examples', 'examples.*'])
```

Or (and this is how I would do it to avoid this problem in the future) or to whitelist `flask_admin`:

```python
find_packages(include=['flask_admin'])
```

I would also go further and also blacklist `flask_admin.tests`, since I think tests should not be part of the installation:

```python
find_packages(include=['flask_admin'], exclude=['flask_admin.tests.*'])
```

But I think just not shipping the `examples` package is a good start.

**Comment by mrjoes** [comment]
Sounds good. The `include` option won't work as all "batteries" are shipped as `flask_admin.contrib` sub-packages.

But sure, examples and tests can be safely removed.

**Comment by pganssle** [comment]
@mrjoes I always get these `find_packages` things confused. I think the "include" version is actually:

```python
find_packages(include=['flask_admin', 'flask_admin.*'])
```

Though for some reason adding `exclude=['flask_admin.tests.*']` doesn't remove the `flask_admin.tests` module. Not entirely sure what's up with that.

Another, more radical perspective to consider might be using the `src` layout, which [Hynek Schlawack compellingly argues for here](https://hynek.me/articles/testing-packaging/). A less radical version of that is moving `flask_admin/tests` into a `tests` directory alongside `flask_admin`, though that would still probably entail quite a bit of refactoring (haven't looked at the code myself to check this).

Probably the easy thing to do is start by blacklisting and then revisit a whitelist later.

**Comment by elvijs** [comment]
This is a substantial issue for a project I'm working on. The `examples` package installed alongside `flask-admin` is overwriting our project's `examples` package.

Is there any way I could speed up the fix? Happy to do a PR if that would help.

**Comment by elvijs** [comment]
Added a proposed super-lightweight fix, see the PR above

**Comment by pganssle** [comment]
I think this probably still needs a more long-term fix, like adding a test that *only* things under the correct namespace are built, or using one of the `find_packages`-based approaches.

**Comment by elvijs** [comment]
Good point.

For what it's worth, I think that explicitly whitelisting `flask-admin` is the cleanest solution (as long as tests are moved out of `flask-admin`).
