### ISSUE TITLE
Decorated function instead is_accessible ?

### ISSUE THREAD

**Issue by ufo911** [flask-admin/flask-admin#1709]
Can I use decorated for each admin view to permit only special access level users on each view ? now I am using standard is_accessible and don't know how to convert them as user roles. In addition is there better solution ? Can I have decorated for multiple logical cases or multiple decorated  ?

**Comment by alanhamlett** [comment]
Here's an example of using a decorator for access control:

https://gist.github.com/alanhamlett/f9c8d6414cdd81502442fb5631b41fd9

However, questions should be asked on StackOverflow in the future. Please limit GitHub issues to bug reports or feature suggestions.

**Comment by ufo911** [comment]
I understand about scopes but Can I have several roles collection in flask admin and grant access users with specific permission on specific views ?

**Comment by alanhamlett** [comment]
Flask-Admin let's Flask-Login handle authentication and permissions. You can always make your own decorator function and use it however you want. To decorate an admin route, add the decorator to the url method handling an admin page:
https://flask-admin.readthedocs.io/en/latest/introduction/#standalone-views

Just like `@expose('/')` from the link above, you can also add `@mycustomdecorator`.

**Comment by ufo911** [comment]
I managed to get roles by [this way ](https://stackoverflow.com/questions/52468540/flask-admin-roles-adding-roles-accapted-to-add-view) but problem now I have is that flask admin does not have option to add roles_accapted for mongoengine admin.add_view ? that is the last point and I will get it worked :)

**Comment by ufo911** [comment]
Solution
https://stackoverflow.com/questions/52468540/flask-admin-roles-adding-roles-accapted-to-add-view
