### ISSUE TITLE
is bug? ModelView  column_laels not Dictionary where key is column name and value is string to display.

### ISSUE THREAD

**Issue by jackadam1981** [flask-admin/flask-admin#1711]
class Users(Base,BaseMixin):
    username = Column(String(24))
    jobs_id = Column(Integer, ForeignKey('user_jobs.id'))
    Jobs_Name = relationship('User_Jobs')
    groups_id = Column(Integer, ForeignKey('user_groups.id'))
    Groups_Name = relationship('User_Groups')
    quarters_id = Column(Integer, ForeignKey('user_quarters.id'))
    Quarters_Name = relationship('User_Quarters')

class users_view(ModelView):
    column_display_actions = True
    can_view_details = True
    column_details_list = ('username', 'Groups_Name', 'Jobs_Name', 'Quarters_Name')
    can_export = True
    export_types = ['xls']
    column_export_list = ['username','Jobs_Name','Groups_Name','Quarters_Name']
    column_list = ('username','Jobs_Name','Groups_Name','Quarters_Name')
    column_labels = dict(
        id='序号',
        username='姓名',
        Groups_Name='班组名称',
        Jobs_Name='职务名称',
        Quarters_Name='职名名称',
    )
    form_columns = ('username', 'Groups_Name', 'Jobs_Name', 'Quarters_Name')
    column_filters=('username', 'Groups_Name', 'Jobs_Name', 'Quarters_Name')

column_labls not change filters display name.(the relationship column.)

**Comment by SBillion** [comment]
Try to use lowercase for your variable in Python. So Groups_Name should be renamed in groups_name. Replace everywhere and let me know if the label is redefined as you want. I guess there is a piece of code waiting for lowercase variable in the label filter process
