### ISSUE TITLE
Documentation for contrib.sqla.ModelView.get_query should mention overriding get_one

### ISSUE THREAD

**Issue by lapseofreason** [flask-admin/flask-admin#1739]
The documentation for [contrib.sqla.ModelView.get_query](https://flask-admin.readthedocs.io/en/latest/api/mod_contrib_sqla/#flask_admin.contrib.sqla.ModelView.get_query) reminds the user to override `get_count_query` as well. It should also mention to override `get_one` as well, for example like this:

```python
def get_one(self, id):
    """Return an element with limited to the elements returned by get_query."""
    query = self.get_query()
    return query.filter(self.model.id == id).first()
```

If it is not done this way, some elements might be filtered in the list view, but can still be accessed in the edit view by simply changing the id in the url. This potentially allows users to see/edit elements they should not be allowed to see/edit.

**Comment by petrus-jvrensburg** [comment]
Thanks @lapseofreason. Could you make a pull request?

**Comment by lapseofreason** [comment]
Unfortunately it took a bit, but here you go ;)
