### ISSUE TITLE
Inline model with multiple relationships uses an arbitrary one

### ISSUE THREAD

**Issue by lapseofreason** [flask-admin/flask-admin#1740]
If two sqlalchemy database models have multiple relationships, and inline models are used, then the form for the inline models will select a relationship arbitrarily.

Since it is arbitrary, this should at least be mentioned in the documentation or better even allow the user to select the correct relationship and throw an exception if there is no unique relationship.

As a workaround, a relationship can be selected by overriding `_calculate_mapping_key_pair` in `contrib.sqla.form.InlineModelConverter` and setting it as `inline_model_form_converter`.

**Comment by jubafourali** [comment]
for the newest version of flask-admin,  `_calculate_mapping_key_pair`  is not used seen that the `_calculate_mapping_key_pair`'s treatments has been moved to  `contribute` method in the same file .

**Comment by jubafourali** [comment]
The correction is in my flask-admin fork 
[https://github.com/jubafourali/flask-admin/commit/0ccea121a42fc367760c1d246b4689a399dfffbe](url) 
I will create a pull request for the original repository.

**Comment by cancan101** [comment]
@jubafourali any desire to PR this?

**Comment by jubafourali** [comment]
@cancan101 I will try to find some times for that ?

**Comment by jubafourali** [comment]
> @jubafourali any desire to PR this?

@cancan101 PR created https://github.com/flask-admin/flask-admin/pull/1773, thank's
