### ISSUE TITLE
[Features] QR Code support

### ISSUE THREAD

**Issue by DataDrug** [flask-admin/flask-admin#1741]
Hi,

Let's say that I have a Model with:

Product
Serial Number
Model Number

And I would like to add a new Column that would generate a QR Code based on Product+Serial+Model Number.

Can someone point me to the right direction?

Thank you

**Comment by alanhamlett** [comment]
Sure, this is the place for your question:
https://stackoverflow.com/search?q=sqlalchemy

**Comment by DataDrug** [comment]
Been there, done that, 0 answers, have googled a ton, but nothing specific (to the point I was able to understand).

Thank's.
