### ISSUE TITLE
Writing form.js script element after filters.js on admin/model/list.html throws js error

### ISSUE THREAD

**Issue by danax** [flask-admin/flask-admin#1787]
which also prevents rendering of the form to modify and submit again.

error is:
```
Uncaught ReferenceError: faForm is not defined
    at styleFilterInput (filters.js?v=1.0.0:94)
    at addFilter (filters.js?v=1.0.0:145)
    at Array.<anonymous> (filters.js?v=1.0.0:164)
    at Function.each (jquery.min.js?v=2.1.4:2)
    at new AdminFilters (filters.js?v=1.0.0:160)
    at filters.js?v=1.0.0:189
    at filters.js?v=1.0.0:195
```

change was:
https://github.com/flask-admin/flask-admin/commit/b94874f2efacb8c0cb718df2a8549712305c1d0a#diff-e16c5aee92083ed155e7f012093dbbd5

`filters.js` wants the `faForm` variable here:
https://github.com/flask-admin/flask-admin/blob/master/flask_admin/static/admin/js/filters.js#L94

**Comment by anka-sirota** [comment]
https://github.com/flask-admin/flask-admin/pull/1784 might be related

**Comment by danax** [comment]
for sure. guess I didn't search PRs before posting.
