### ISSUE TITLE
Delete confirmation no longer shows in list view

### ISSUE THREAD

**Issue by fwiersVANAD** [flask-admin/flask-admin#1789]
With version 1.5.2 clicking the trash-icon in the list-view to delete a record would show a confirmation dialog. This no longer happens in version 1.5.3.

I fixed it locally by adding the "safeConfirm" Javascript code back into templates/admin/model/list.html that was deleted with this commit:
https://github.com/flask-admin/flask-admin/pull/1521/commits/b94874f2efacb8c0cb718df2a8549712305c1d0a

**Comment by joshua-s** [comment]
Could we release this change?

**Comment by cancan101** [comment]
Any update on getting a new release with these changes?

**Comment by napafundi** [comment]
Any news on releasing these changes?

**Comment by gordol** [comment]
wheeeeeeeeee

**Comment by ozamani9** [comment]
This is still not working and we are using 1.5.6, do i need to add any code to activate this, or is the confirmation box the default action for clicking delete (trash_can)

**Comment by lemurchik** [comment]
> This is still not working and we are using 1.5.6, do i need to add any code to activate this, or is the confirmation box the default action for clicking delete (trash_can)

If you have overridden templates, check "safeConfirm" JS function usage, now it is "faHelpers.safeConfirm"
