### ISSUE TITLE
index_view menu item isn't active when using app factory pattern

### ISSUE THREAD

**Issue by nk9** [flask-admin/flask-admin#1830]
When you use the app factory pattern and pass the `index_view` parameter to `init_app`, the resulting menu item ("Home" here) doesn't activate as it should:

<img width="224" alt="Screen Shot 2019-03-21 at 14 15 03" src="https://user-images.githubusercontent.com/3646730/54758282-c4a02600-4be3-11e9-9732-5c3312b8bd4b.png">

There is a one-line PR to address this, #1554, but it's 18 months old now. It fixes the problem, although I don't know enough about flask_admin's internals to know if it's done in the right way.

**Comment by petrus-jvrensburg** [comment]
fixed in 2681a15ca7e2e4642a69b41936cf006749b05aca
