### ISSUE TITLE
Flask-Admin behind Nginx 

### ISSUE THREAD

**Issue by bjorn-bakken** [flask-admin/flask-admin#1842]
Hello,

I have two flask apps running behind nginx. One flask app is running on port 5000 and the other (api) is running on 5001. I have two location blocks in nginx.conf. The api-app is served on server_name/api.

I can access Flask-Admin on "server_name/api/admin" but the problem is that Flask-Admin looks for static files at "server_name/admin/static", but they are available at "server_name/api/admin/static".

Is there a simple way to *prefix* the static_url_path with "api"?

**Comment by bjorn-bakken** [comment]
I see now that my issue is much the same as #1837

**Comment by mrjoes** [comment]
That's how per-blueprint static urls are routed in Flask.

There are a few ways to fix it:
1. You can add an nginx rule to map `/admin/static/` to a static directory where flask-admin is installed
2. Try flask-collectstatic (I never tried it myself) that would allow you to have a single folder with all collected static files to be shared through nginx

Also, there's a similar discussion: https://stackoverflow.com/questions/41853436/flask-raises-404-for-blueprint-static-files-when-using-blueprint-static-route

**Comment by bjorn-bakken** [comment]
Thank you @mrjoes for pointing me in the right direction!

Adding another location block to nginx fixed things.

I would also like to give you thumbs up for not mocking a newbie asking simple/silly questions :+1:
