### ISSUE TITLE
filter styling in list view breaks after application in 1.5.3

### ISSUE THREAD

**Issue by paularcoleo** [flask-admin/flask-admin#1850]
After recently updating flask-admin from 1.5.1 to 1.5.3 (updating no other packages), I've noticed several issues with filter styling in list views after you initially apply the filter. 

For example, in [this image](https://abyssal.s-ul.eu/TC67z5ww), I've applied a filter, and then changed the value in the dropdown. In 1.5.1,  this works as expected. However, in 1.5.3, the dropdown styling has changed. Additionally, after changing the value in the dropdown, the "Apply" button does not appear. Checking the console in Chrome shows a javascript error: 

`Uncaught ReferenceError: faForm is not defined
    at styleFilterInput (filters.js?v=1.0.0:97)`

Reverting flask-admin to 1.5.1 fixes this issue. I imagine that this has to do with WTForms 3 support?

Full list of packages, for reference: https://gist.github.com/paularcoleo/a007160b09ce14f9f00748eb604b6650

**Comment by julien66** [comment]
+1 I can confirm this bug.
Adding a filters works fine here as well. The problem occurs after validating the filter or if you try to check a page with field enabled /flt... It just looks like faForm is still not defined at the time styleFilterInput is triggered on this filter! Is Form.js just late maybe?

**Comment by julien66** [comment]
`Now I'm willing to find a better way to solve this issue.`
Suggestion are welcomed. What would be the best way to overcome this issue? 
AdminFilters are getting defined BEFORE AdminForm and are trying to access global faForm for styling which doesn't exist yet. I'm not super experienced, in this situation I would use an event dispatcher / listener to fix this problem with more flexibility than the brute code above. 
I also feel there are betters ways.
