### ISSUE TITLE
How I can add one more than url with expose?

### ISSUE THREAD

**Issue by alibaraneser** [flask-admin/flask-admin#1872]
Hey,

I want to add one more than url with expose, my samples code above.

```
@expose('/', ["GET","POST"])
    def index(self):
        if flask.request.method == 'POST':
            pass
        else:
            pass

    admin.add_view(IntentView(name="Intent", endpoint='intent'))

```

abc.com/admin/intent

But I want to improve this shape, abc.com/admin/intent/edit/1 etc.

How can I do?

**Comment by caffeinatedMike** [comment]
@mrjoes can be closed, solution has been proposed and no follow-up seems to indicate issue is resolved and stale.
