### ISSUE TITLE
Order_by for relationship ?

### ISSUE THREAD

**Issue by nMustaki** [flask-admin/flask-admin#190]
Hi,
I have two tables, link by a relationship :

``` python
class News(db.Model):
   #[...]
    venue_id = db.Column(db.Integer(), db.ForeignKey(Venue.id))
    venue = db.relationship(Venue, backref='news')
```

When creating a News item, venue objects are displayed in a select, but there are not ordered, how could I do that ?

Thanks you !

**Comment by mistercrunch** [comment]
This seems to affect what is sortable in the list view. What about managing the sort order in the <select> (dropdown) on the edit view? I can't get those sorted.

**Comment by sampart** [comment]
@mistercrunch (and others who find this via Google like me), you could update the `query_factory` property on the form field.  Something like this:

```python
    def edit_form(self, obj=None):
        form = super().edit_form(obj)

        # apply a sort to the relation
        form.venue.query_factory = lambda: models.Venue.query.order_by(models.Venue.name)

        return form
```
