### ISSUE TITLE
Can't import Admin

### ISSUE THREAD

**Issue by anang42429** [flask-admin/flask-admin#1920]
I have a problem when importing flask_admin, an error says `ModuleNotFoundError: No module named 'flask.ext'`

This is a screenshot of a web application that I made
![](https://i.imgur.com/k7K84YZ.png)

This is the initiation code that I wrote at __init__.py
```
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from config import Config
from flask_login import LoginManager
from flask_bootstrap import Bootstrap
from flask_admin import Admin
import flask_excel as excel

app = Flask(__name__)
app.config.from_object(Config)
db = SQLAlchemy(app)
migrate = Migrate(app, db)
login = LoginManager(app)
login.login_view = 'login'
bootstrap = Bootstrap(app)
admin = Admin(app, name='LocalNote', template_mode='bootstrap4')
excel.init_excel(app)

from app import routes, models
```

I even tried importing flask_admin via python terminal, here's a screenshot
![](https://i.imgur.com/DEldcMi.png)

I have tried to find a solution on Google, but it seems like only I have this error.
 Is there a way to fix this error? Or the way I imported is wrong?

**Comment by david672orford** [comment]
It looks to me like you are trying to import an old version of Flask admin as if it were the current version. In the current version it is imported from flask_admin. I believe a few years ago it was imported from flask.ext.admin.

**Comment by anang42429** [comment]
@david672orford Thanks, I installed it manually and the error disappeared

**Comment by TailaneBrito** [comment]
> @david672orford Thanks, I installed it manually and the error disappeared

I'm trying to use it now but I don't have too much experience setting up it manually. Do you have an article to follow up with? Thanks!

**Comment by sisayie** [comment]
In case someone gets here, the following worked for me with **Flask-Admin-1.5.6**
First install flask admin: `pip3 install Flask-Admin`
Then import: `from flask_admin import Admin` instead of ~from flask.ext.admin import Admin~
