### ISSUE TITLE
AttributeError: 'str' object has no attribute 'strftime' when click Create

### ISSUE THREAD

**Issue by VitalySvyatyuk** [flask-admin/flask-admin#1956]
<img width="970" alt="Screen Shot 2020-02-18 at 14 39 38" src="https://user-images.githubusercontent.com/10582918/74733095-b8da3b00-525c-11ea-87db-6749f375e989.png">

**Comment by VitalySvyatyuk** [comment]
sorry, it's my local issue, not flask-admin

**Comment by myounus96** [comment]
> sorry, it's my local issue, not flask-admin

I am getting the same issue, can please help, what might be the issue...?

**Comment by myounus96** [comment]
@VitalySvyatyuk

**Comment by VitalySvyatyuk** [comment]
Hi @myounus96 , in my case an error was in models.py. I tried to put time string to DateTime column like that:
`def get_datetime():
    now = datetime.utcnow()
    return now.strftime("%Y-%m-%d %H:%M:%S")

class User(db.Model):
# fields
    created_at = db.Column(db.DateTime, default=get_datetime)
`
So my fix was:
`created_at = db.Column(db.DateTime, default=datetime.utcnow)`

**Comment by myounus96** [comment]
Thanks @VitalySvyatyuk , my issue was
```
class Entity(Model):
    created_at = Column(
        DateTime,
        default=lambda _: datetime.datetime.utcnow().isoformat()
    )

```
and fix is, removed the `.isoformat()`

```
class Entity(Model):
    created_at = Column(
        DateTime,
        default=lambda _: datetime.datetime.utcnow()
    )

```
