### ISSUE TITLE
Merge Bootstrap4 support

### ISSUE THREAD

**Issue by DandyDev** [flask-admin/flask-admin#1977]
@mrjoes there are [multiple](https://github.com/flask-admin/flask-admin/pull/1879) [PRs](https://github.com/flask-admin/flask-admin/pull/1903) [open](https://github.com/flask-admin/flask-admin/pull/1926) that add Bootstrap4 support. Bootstrap4 has been out for ages now.
I realize you're supporting flask-admin in your free time and I'm not entitled to anything. But is there a reason why you're not merging any of those PRs?

Is there any way in which I can help so we can get Bootstrap 4 support sooner? I'm willing to work on this!

**Comment by mrjoes** [comment]
I would love to merge them, but they all are unfinished and need additional work. I checked them at the end of 2019 when some of the changes were committed.

If someone would like to volunteer, create a single MR with all necessary changes and test it - I'll definitely merge it.

**Comment by DandyDev** [comment]
I can volunteer. But can you give me a pointer on:
- Which of the existing PRs is the most complete and should I use as basis
- What you feel is still missing from that PR.

Then I will make sure to add the relevant functionality, either by getting it from the other PRs, or by writing it myself.

**Comment by mrjoes** [comment]
This is the main WIP PR: https://github.com/flask-admin/flask-admin/pull/1879

I merged one of the outstanding PRs into it, other one can not be merged, but I think duplicates the changes from the other one anyway.

The PR needs testing: look and feel, forms functionality, inline editing, etc.

**Comment by mkschulze** [comment]
Could be checked for Bootstrap5 support now.

**Comment by TitaniumHocker** [comment]
Is there any updates?

**Comment by r3da-hash** [comment]
Any updates ?

**Comment by Seluj78** [comment]
Bootstrap 4 has been merged. You can already use it
