### ISSUE TITLE
Running sqla example.  email_validator dependency for sqlalchemy-utils missing

### ISSUE THREAD

**Issue by daniel-butler** [flask-admin/flask-admin#2001]
Topic.

Created pull request for this #2000

**Comment by BigBaaadBob** [comment]
I just ran into the same issue.  Any chance this PR can be merged?

**Comment by dwreeves** [comment]
+1 to this. Looking at some old logs it looks like `email-validator` was causing some tests to fail and it was added to `./requirements-dev.txt`, but strictly speaking following the README for the sqla example it fails by not being in `./examples/sqla/requirements.txt`.

**Comment by alanhamlett** [comment]
Fixed with #2094.
