### ISSUE TITLE
[Not a bug] Question on how to do this (details inside)

### ISSUE THREAD

**Issue by JunkyardCat** [flask-admin/flask-admin#2007]
1. is there a way to show or use my own navbar at the top? then on the bottom show the usual model view?
2. is there a easier or neat way to declare a common behavior between views? 
ex. 
i have studentview, professorview, notesview and classroomview
for all that view i dont want to show the column "updated" which can easily be acheived by using form_excluded_columns = ['updated']. is there a way to just declare it once and not have to declare it on all 4 of those view? 
3. is the project on halt?
4. is there a way or a platform to communicate with you guys like ask these kind of question? maybe irc or discord

**Comment by TitaniumHocker** [comment]
Hello!

I am not a maintainer of this project, but I have experience with it and can try to answer.

> is there a way to show or use my own navbar at the top? then on the bottom show the usual model view?

It seems to me that to implement something like this, you need to overwrite the standard [base.html](https://github.com/flask-admin/flask-admin/blob/master/flask_admin/templates/bootstrap3/admin/base.html) or [layout.html](https://github.com/flask-admin/flask-admin/blob/master/flask_admin/templates/bootstrap3/admin/layout.html) template.

> is there a easier or neat way to declare a common behavior between views?

You can implement your `MyBaseView` class to declare common attributes/
Here is an example:

```python
from flask_admin.contrib.sqla import ModelView
from flask_admin import Admin
from myproject.models import db, Student, Professor, ClassRoom

admin = Admin(name='My Project', template_mode='bootstrap3')

class MyBaseView:
    form_excluded_columns = ['updated']

class StudentView(MyBaseView, ModelView):
    # Your code for Student model view

class ProfessorView(MyBaseView, ModelView):
    # Your code for Professor model view

class ClassRoomView(MyBaseView, ModelView):
    # Your code for ClassRoom view

admin.add_view(StudentView(Student, db.session, name='Students'))
admin.add_view(ProfessorView(Professor, db.session, name='Professors'))
admin.add_view(ClassRoomView(ClassRoom, db.session, name='Class rooms'))
```

> is the project on halt?

As far as I see the project is supported, but there is no particular development of new features.

> is there a way or a platform to communicate with you guys like ask these kind of question? maybe irc or discord

I am not aware of such platforms. Most likely, I just don't know about them.

**Comment by JunkyardCat** [comment]
@titaniumhocker

Is there a way to add a field and a label . The value will be derived by the sum of the 2 field already in the ui. This new field and label is not from a column. Itll be just there to display data

**Comment by TitaniumHocker** [comment]
You can define a property of you model and display it in your `ModelView`.
Here is an example:
```python
from os import path
from random import randint

from flask import Flask, redirect, url_for
from flask_sqlalchemy import SQLAlchemy
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView

db_path = path.join(path.dirname(__file__), 'db.sqlite3')

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{db_path}'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['SECRET_KEY'] = 'qwerty' # not secure

@app.route('/')
def index():
    return redirect(url_for('admin.index'))

db = SQLAlchemy(app)
admin = Admin(app)

class SampleModel(db.Model):
    __tablename__ = 'samples'
    id = db.Column(db.Integer, primary_key=True)
    one = db.Column(db.Integer)
    two = db.Column(db.Integer)

    @property
    def three(self):
        return self.one + self.two

class SampleModelView(ModelView):
    column_list = ('one', 'two', 'three')
    column_labels = {
        'three': 'Magic'
    }

admin.add_view(SampleModelView(SampleModel, db.session, name='Something'))

def build_db():
    db.drop_all()
    db.create_all()
    for _ in range(5):
        db.session.add(SampleModel(one=randint(1, 100), two=randint(1, 100)))
    db.session.commit()

if __name__ == '__main__':
    # build sample database
    build_db()
    app.run()
```

List page for this example will look like this:

![изображение](https://user-images.githubusercontent.com/37049574/90060290-25566400-dced-11ea-9e4d-c7c164c6d6b6.png)

You can find some examples of using `Flask-Admin` extension in the [examples](https://github.com/flask-admin/flask-admin/tree/master/examples) directory of the repository.
Also this extension has great [documentation](https://flask-admin.readthedocs.io/en/latest/).

**Comment by TitaniumHocker** [comment]
@JunkyardCat, if you don't have any more questions - can you close the issue pls?
