### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: admin/master.html.

### ISSUE THREAD

**Issue by rrad0812** [flask-admin/flask-admin#2020]
Hi,
I am absolutely beginner in Flask-Admin.
When I try examples, i got exception:
jinja2.exceptions.TemplateNotFound: admin/master.html.

As jinja doesn't see master template in site-packages/flask_admin/templates???

Any hint, please?

**Comment by ademaro** [comment]
`flask-admin` is not the latest version in pypi the repository, you can update with the following command:
`pip install git+git://github.com/flask-admin/flask-admin`

**Comment by ybenitezf** [comment]
i keep getting the same exception with this example

**Comment by psaniko** [comment]
In the meantime you can checkout an older version, e.g. `git checkout tags/v1.5.5`
