### ISSUE TITLE
Werkzeug imports outdated

### ISSUE THREAD

**Issue by IsaiasDimitri** [flask-admin/flask-admin#2037]
Seems like some functions in werkzeug, used by flask-admin was moved to other places. I got this errors today:

`
ImportError: cannot import name 'secure_filename' from 'werkzeug' (/home/dimitri/LargeProjects/red_watcher/003-arquitetura-flask-new/env/lib/python3.8/site-packages/werkzeug/__init__.py)
`

Now, secure_filename is in werkzeug.utils, and others may have changed too.

**Comment by TitaniumHocker** [comment]
Unfortunately, I was unable to find a piece of code that uses incorrect imports.
```bash
th@x240 ~/D/W/flask-admin (master)> rg 'import secure_filename' .
./examples/sqla-custom-inline-forms/app.py
4:from werkzeug.utils import secure_filename

./flask_admin/contrib/fileadmin/__init__.py
11:from werkzeug.utils import secure_filename

./flask_admin/form/upload.py
4:from werkzeug.utils import secure_filename

./flask_admin/model/base.py
8:from werkzeug.utils import secure_filename
```

Please provide a full traceback and specify which version of the `flask-admin` you are using.

**Comment by IsaiasDimitri** [comment]
> Unfortunately, I was unable to find a piece of code that uses incorrect imports.
> 
> ```shell
> th@x240 ~/D/W/flask-admin (master)> rg 'import secure_filename' .
> ./examples/sqla-custom-inline-forms/app.py
> 4:from werkzeug.utils import secure_filename
> 
> ./flask_admin/contrib/fileadmin/__init__.py
> 11:from werkzeug.utils import secure_filename
> 
> ./flask_admin/form/upload.py
> 4:from werkzeug.utils import secure_filename
> 
> ./flask_admin/model/base.py
> 8:from werkzeug.utils import secure_filename
> ```
> 
> Please provide a full traceback and specify which version of the `flask-admin` you are using.

Sorry, was my fault. I'm using an old version of flask-admin.
