### ISSUE TITLE
Another Release?

### ISSUE THREAD

**Issue by AlecRosenbaum** [flask-admin/flask-admin#2043]
Just a question -- is there any timeline for putting out another release?

I'm asking mainly because one of my projects is stuck with `v1.5.3` until the fix for https://github.com/flask-admin/flask-admin/issues/1927 makes its way into a release. The older version  of `flask-admin` doesn't support Werkzeug 1.0, and is blocking a whole bunch of other stuff in the mean time.

**Comment by mrjoes** [comment]
Yes, around this weekend - I'm finishing testing Bootstrap 4 branch and pulling a trigger.

**Comment by bekab95** [comment]
> Yes, around this weekend - I'm finishing testing Bootstrap 4 branch and pulling a trigger.

Please also review this #2036 PR

**Comment by AlecRosenbaum** [comment]
@mrjoes https://github.com/flask-admin/flask-admin/releases/tag/v1.5.7 Thank you!
