### ISSUE TITLE
Release 1.5.8 

### ISSUE THREAD

**Issue by ihortanchyn-da** [flask-admin/flask-admin#2061]
Hi, just a small question - what is the approximate release date for a new version (1.5.8)?
Realy waiting for [this](https://github.com/flask-admin/flask-admin/pull/2058) fix.

**Comment by vsvirsky** [comment]
Hey everyone, actually we are also waiting for rediscli fix.

**Comment by alanhamlett** [comment]
Releases are handled by @mrjoes.

**Comment by gyermolenko** [comment]
https://pypi.org/project/Flask-Admin/1.5.8/

**Comment by mrjoes** [comment]
Thank you, forgot to close this one.
