### ISSUE TITLE
bootstrap4 checkbox not properly rendered

### ISSUE THREAD

**Issue by Demetriex** [flask-admin/flask-admin#2064]
currently it looks like this
![image](https://user-images.githubusercontent.com/41515495/101570134-c1c91280-3a10-11eb-8fa6-3c8ef7cebabd.png)

it should look like this
![image](https://user-images.githubusercontent.com/41515495/101570433-57fd3880-3a11-11eb-9740-aa6209bab2fd.png)

https://github.com/flask-admin/flask-admin/blob/ebfb2ec1ac4329f8a4fb08c3e1c58fbcf5541dfc/flask_admin/templates/bootstrap4/admin/lib.html#L138-L139

maybe change the class to `form-control form-control-lg` or `form-control`

**Comment by TitaniumHocker** [comment]
Big checkbox in the middle of the row is terrible, current layout looks better.
