### ISSUE TITLE
flask-babelex out-of-date

### ISSUE THREAD

**Issue by fagcinsk** [flask-admin/flask-admin#2077]
https://github.com/flask-admin/flask-admin/blob/43acc41ff8b392ad59907acdb7e1fa81dfd5ba6c/flask_admin/babel.py#L2

**Comment by mrjoes** [comment]
Flask-Babel merged most of the Flask-BabelEx changes, but no one spent any time updating Flask-Admin to use mainline Flask-Babel.

That being said - pull requests are welcome!
