### ISSUE TITLE
[Suggestion]  Integrate password protection into Flask-Admin

### ISSUE THREAD

**Issue by codinghedgehog-python** [flask-admin/flask-admin#2095]
I'd like to suggest to make Flask-Admin password protected **out of the box** just like it works in Django.
There is simply no reason for not doing that. Nobody wants admin interface to be exposed to the wide web in production.
I suggest to do it with next major release.

In can be as a integration of two extensions, Flask-Admin + Flask-BasicAuth.

**Comment by TitaniumHocker** [comment]
There is really no reason for doing this. Flask-Admin is just admin site generator and nothing more. If you need to secure this part of your site you can use the same thing that you used for rest part of the site.
