### ISSUE TITLE
Question: How do I extend my own base template so flask-admin is shown within it?

### ISSUE THREAD

**Issue by aquatic7** [flask-admin/flask-admin#2097]
I have tried adding: base_template='base.html' to admin = Admin(app, index_view=MyAdminIndexView(), name='ADMIN', template_mode='bootstrap3')

But it doesn't show the flask-admin menubar or data.

How can I extend my own base template so flask-admin is using it?

I've read the documentation and posts on stackoverflow and on here, but I can't seem to find the solution.

Also I've read: https://flask-admin.readthedocs.io/en/latest/introduction/#working-with-the-built-in-templates

But I just can't figure out how to use:
    admin/model/list.html
    admin/model/create.html
    admin/model/edit.html

I don't know which way to go or how to do it, so any hint or solution is welcome!

**Comment by alanhamlett** [comment]
```
from my_flask_app import app
from flask_admin import Admin

admin = Admin(app, base_template='admin/custom_base.html')
```

Please keep questions on StackOverflow so others can find them. GH Issues is only for bugs.
