### ISSUE TITLE
DeprecationWarning for contextfunction

### ISSUE THREAD

**Issue by austinbutler** [flask-admin/flask-admin#2126]
DeprecationWarning: 'contextfunction' is renamed to 'pass_context', the old name will be removed in Jinja 3.1

**Comment by malan88** [comment]
There's a PR but it's still sitting open. https://github.com/flask-admin/flask-admin/pull/2110

**Comment by malan88** [comment]
Correction, the changes are already made even though that PR is open. https://github.com/flask-admin/flask-admin/blob/43ee2c0c907ef5effaa2945f0f67f8f8ae12b082/flask_admin/_compat.py#L94-L97

I suppose the changes just haven't been deployed yet. Can always just install from main!

**Comment by malan88** [comment]
Oh, haha, no he just merged it. Thanks @mrjoes !

**Comment by caffeinatedMike** [comment]
@mrjoes according to the comments this can be closed
