### ISSUE TITLE
How to hide menu links for no access roles?

### ISSUE THREAD

**Issue by t00mis** [flask-admin/flask-admin#2155]
Hello dear!)
i want split a view a roles and I'm not doing it very well. pls help me.

I set the access level with example:
```
class MyAdminAuth(ModelView):
    def is_accessible(self):
        if current_user.has_role('Admin'):
            return current_user.is_authenticated

    def _handle_view(self, name, **kwargs):
        if not self.is_accessible():
            return redirect(url_for('admin.login'))
```
            
            
         
and this works great, but links in the menu remain for other roles. 
How to hide menu links for no access roles?

**Comment by briancappello** [comment]
I'm not sure if this is documented or not but if you [dive into the source code](https://github.com/flask-admin/flask-admin/blob/master/flask_admin/base.py#L319-L339) you'll see there's a method named `is_visible` which controls menu link visibility.
