### ISSUE TITLE
Is it possible to filter relationship select field?

### ISSUE THREAD

**Issue by notbenj** [flask-admin/flask-admin#219]
Hi,

Is it possible to filter the content of a select field that was automatically created by flask-admin from a relationship() method?

I spent a long time searching for a solution and I couldn't find one.

Among other things, my application contains 2 tables:
![relationship](https://f.cloud.github.com/assets/801848/463522/a4b6ea5a-b570-11e2-877f-1acfa690e822.png)
The relationship is timelines.spot_id = spots.id

I want a user to be able to select a spot when he is creating a timeline, so here is my code:
![timeline_model](https://f.cloud.github.com/assets/801848/463523/ca28f774-b570-11e2-9369-9fe86baf9121.png)

It's almost perfect, flask-admin displays a select field when creating a timeline, so that the user can choose a spot.
The problem is that I want this select field to display only some spots, not all of them.
I have my list of spots, but I don't know how to alter this field.

I tried without success to:
- use form_override
- play with primary_join of SQLAlchemy
- google for a solution
- browse through this github issues tab

![timeline_creation](https://f.cloud.github.com/assets/801848/463531/3af69e3e-b571-11e2-9882-43a1baf372a1.png)

Thanks a lot if anyone has time to help.

Cheers,
Benjamin

**Comment by gordol** [comment]
So I had a similar need, except I'm using Mongoengine...

This is what I came up with by overriding create_form and edit_form.

```python
class SiteView(AdminGenericView):

    def _filter_inspectors(self, form):
        form.inspectors.queryset = form.inspectors.queryset.filter(roles=models.Role.objects(name='Inspector').get())
        return form

    def create_form(self):
        return self._filter_inspectors(super(SiteView, self).create_form())

    def edit_form(self, obj):
        return self._filter_inspectors(super(SiteView, self).edit_form(obj))

```

Just thought I'd leave it here for anyone who comes looking for ideas.

**Comment by xqliu** [comment]
Any method is to just modify the dynamic query property of the field as below

```
    def edit_form(self, obj=None):
        form = super(ModelView, self).edit_form(obj)
        po_id = obj.transient_po.id
        line_entries = form.lines.entries
        po_lines = PurchaseOrderLine.header_filter(po_id).all()
        for sub_line in line_entries:
            sub_line.form.purchase_order_line.query = po_lines
        return form
```

The code above is trying to filter field po_lines in a inline admin form, based on field transient_po in the header.
