### ISSUE TITLE
[Question]: When is the next release planned?

### ISSUE THREAD

**Issue by Zianor** [flask-admin/flask-admin#2215]
First of all: thanks for the work here!

Now my Question: Since most of the Issues with Wtforms 3.0 seems to be fixed, when is the next release planned? It would be great to receive the fixes and features you implemented since April

**Comment by abstractOwl** [comment]
+1, really looking forward to pulling in the new one-to-one inline models form!

**Comment by killian-dunne** [comment]
+1, very excited for this!

**Comment by mrjoes** [comment]
This weekend. I think we're stable enough for a release.

**Comment by kanhebei** [comment]
看来更新要等过年了
