### ISSUE TITLE
Loose Coupling

### ISSUE THREAD

**Issue by JarriqTheTechie** [flask-admin/flask-admin#2223]
Can flask admin be used without SQLAchemy? I'm really not a fan of the project and would prefer to use a different ORM such as masonite-orm.

**Comment by mrjoes** [comment]
This was a goal of Flask-Admin. SQLAlchemy support is just an extension that's built on top of Flask-Admin core. See here: https://github.com/flask-admin/flask-admin/blob/master/examples/simple/app.py

If you want to get fancy and support your ORM, check this doc: https://flask-admin.readthedocs.io/en/latest/advanced/#using-different-database-backends
