### ISSUE TITLE
error with multiple admin sites and factory pattern

### ISSUE THREAD

**Issue by mariofix** [flask-admin/flask-admin#2307]
Hello, I'm trying to create a second admin site to use with less privileged users, but I get the error **ValueError: The name 'admin' is already registered for a different blueprint. Use 'name=' to provide a unique name.** when I load up the second site

###  __init__.py
```python
from flask import Flask
from .database import db
from .admin import admin_site
from .second_site import sec_site
from .models import User, Role

def create_app():
    app = Flask(__name__, instance_relative_config=True)
    db.init_app(app)
    admin_site.init_app(app)
    sec_site.init_app(app) # it fails here
    user_datastore = SQLAlchemyUserDatastore(db, User, Role)
    security = Security(app, user_datastore)


    @security.context_processor
    def security_context_processor():
        return dict(
            admin_base_template=admin_site.base_template,
            admin_view=admin_site.index_view,
            h=admin_helpers,
            get_url=url_for,
            app=app,
        )
``` 
###  admin.py
```python
from flask_admin import Admin
from flask_admin.base import MenuLink

admin_site = Admin(
    name="Admin Ops",
    template_mode="bootstrap4",
    url="/admin.site",
    base_template="myadmin3/my_master.html",
)
admin_site.add_link(MenuLink(name=_("Logout"), url="/logout"))
```

### second_site.py
```python
from flask_admin import Admin
from flask_admin.base import MenuLink

sec_site = Admin(
    name="Customers",
    template_mode="bootstrap4",
    url="/custsite",
    base_template="myadmin3/my_master.html",
    endpoint="customers",
)
sec_site.add_link(MenuLink(name=_("Logout"), url="/logout"))
``` 

The only way it seems to work, it's if I break factory pattern, and the the sec_site instruction and put it in __init__.py, where the call to sec_site.init_app(app) is
I've already tried putting the endpoint in the init_app call (as it is in the source code https://github.com/flask-admin/flask-admin/blob/master/flask_admin/base.py#L699) with the same result

```
File "/home/mariofix/proyectos/flask-admin-docsite/__init__.py", line 26, in create_app
    sec_site.init_app(app, endpoint="customers")
```

Am I missing something?
Any help is appreciated.

**Comment by BenjaminLECHA** [comment]
Hello,

I'm not an expert but i think you couldn't init admin instance more than once.

If you look inside the exemple : `examples/multiple-admin-instances` the init_app is not use and according to the getting start the init_app method is an alternative : https://flask-admin.readthedocs.io/en/latest/introduction/#getting-started

It's look unecessary in your exemple

**Comment by mariofix** [comment]
Thanks for your reply @BenjaminLECHA 
I did tried the example, but it requires me to put the initialisation of both admin sites and all the views for both admin site in the same file/place (inside create_app). This has many-many issues and should only be used as testing and examples, and i'm not going to change the structure of my app just because of one extension.

Factory pattern has become a defacto standard in flask and there is no reason not to have it properly implemented https://flask.palletsprojects.com/en/2.2.x/patterns/appfactories/ 

I haven't investigated at depth as to why this happens but I believe it has something to do with #513

**Comment by BenjaminLECHA** [comment]
After some test, I succesfull implements multiple admin instance with init_app() based on your simple exemple above and i don't have your error message. 

The error message is for blueprint and add_link() don't register one. You probably have some add_view() with the same name. If you put a class like : `admin_site.add_view(MyClass())` the Class (to be exact the generate name of that class) could be use only one time in general and not one time in each instance. For your sec_site you will have to use a diiferent class (to get a different name) even if inside they are identical.

Hope it will help you.
