### ISSUE TITLE
FileAdmin files don't showing

### ISSUE THREAD

**Issue by Fundi1330** [flask-admin/flask-admin#2366]
When I click on the file it sends me 404. Console output: "GET /static/images\\roamxwifiwhite_1024x1024.webp HTTP/1.1" 404 -
Url is http://127.0.0.1:5000/static/images%5Croamxwifiwhite_1024x1024.webp

**Comment by Meetesh-Saini** [comment]
Can you show the code, I can't reproduce the issue?
