### ISSUE TITLE
Vendored Moment.js is vulnerable to directory traversal and redos attacks

### ISSUE THREAD

**Issue by jamesliu4c** [flask-admin/flask-admin#2386]
Here is a summary of the vulnerabilities: https://security.snyk.io/package/npm/moment/2.22.2

The [Changelog](https://github.com/moment/moment/blob/develop/CHANGELOG.md) for Moment looks like it does not introduce breaking changes betwen 2.22.2 and 2.29.4.

My suggestion is to update replace the vendored Moment in all of the template versions: 2, 3, and 4, and then update the templates.

Also, I can PR this change if that is acceptable.

**Comment by Shookit** [comment]
Moment.js appears to be specified at the following locations:

https://github.com/flask-admin/flask-admin/blob/master/flask_admin/templates/bootstrap2/admin/base.html#L71
https://github.com/flask-admin/flask-admin/blob/master/flask_admin/templates/bootstrap3/admin/base.html#L85
https://github.com/flask-admin/flask-admin/blob/master/flask_admin/templates/bootstrap4/admin/base.html#L84

**Comment by jamesliu4c** [comment]
https://github.com/flask-admin/flask-admin/pull/2387
