### ISSUE TITLE
set favicon

### ISSUE THREAD

**Issue by ElLorans** [flask-admin/flask-admin#2389]
Does the API allow to set up the favicon? Or should I copy the jinja template, add the favicon, and override the default?

**Comment by laiyonghao** [comment]
Create your template file in project's `templates` directory.

file: admin/my_index.html
```
{% extends 'admin/index.html' %}

{% block head_tail %}
<link rel="icon" href="{{ url_for("static", filename='image/favicon_io/favicon.ico') }}">
{% endblock %}
```

Initial `AdminIndexView` with it.

```
index_view = AdminIndexView(url=url, template='admin/my_index.html')
admin = Admin(app, name=name, index_view=index_view, template_mode='bootstrap4')
```

**Comment by ElLorans** [comment]
solved: flask-admin sends a request to /favicon.ico, so you just need to add this url
`
@app.route("/favicon.ico")
def favicon() -> Response:
    """
    Prevent GET /favicon.ico 404 from flask-admin.
    :return:
    """
    # redirect to your favicon
`
