### ISSUE TITLE
Intercepting and executing custom code on object creation/update in flask-admin

### ISSUE THREAD

**Issue by jalvarezz13** [flask-admin/flask-admin#2408]
Hi all!

Is there a way in Flask-Admin to intercept and execute custom code before or after a create or update operation on an object within the database?

I've been exploring SQLAlchemy events and Flask-Admin functions, but I haven't found a direct way to achieve this.
Does anyone have experience handling these specific events in Flask-Admin and could provide guidance or examples on how to implement it?

Thanks in advance!

**Comment by Acrofil** [comment]
Hi. 

I was able to achieve the result  you describe with `@listens_for` event listener decorator.

```
@listens_for(YourModel, 'after_insert')
def create_something_method(mapper, connection, current_model):
    # Your code

@listens_for(YourModel, 'after_update')
def update_something_method(mapper, connection, current_model):
    # Your code
 
```

More information can be found here https://docs.sqlalchemy.org/en/20/core/event.html

Hope this helps you and anyone looking for this kind of behavior.

**Comment by jalvarezz13** [comment]
I finally reached my goal using the native _on_model_change_ and _on_model_delete_ handlers ;)
I will close the issue, then. Thanks!

![image](https://github.com/flask-admin/flask-admin/assets/64201633/42820166-4160-48fc-b159-40a55f5d31d8)
