### ISSUE TITLE
Multiple requests caused by 'create_modal'

### ISSUE THREAD

**Issue by ljh740** [flask-admin/flask-admin#2431]
<img width="338" alt="截屏2024-05-19 21 52 44" src="https://github.com/flask-admin/flask-admin/assets/9330229/082b7ab9-96c9-4cb4-9a1c-f73c538e8509">

Set any view to 'create_modal', click the create button multiple times, and close it. Requests are incremented concurrently.

**Comment by hasansezertasan** [comment]
Duplicate of #2406

**Comment by ljh740** [comment]
> Duplicate of #2406
I want to override this create.html

<img width="312" alt="截屏2024-05-19 23 23 09" src="https://github.com/flask-admin/flask-admin/assets/9330229/cbbc9235-a195-459d-a05f-4ca62961ac36">

but it not work. can you help me?

**Comment by hasansezertasan** [comment]
So you want to override `model/modals/create.html`, am I right?

If that is so, just create this directory: `templates/admin/model/modals/create.html` and do it with Jinja blocks.

**Comment by ljh740** [comment]
> So you want to override `model/modals/create.html`, am I right?
> 
> If that is so, just create this directory: `templates/admin/model/modals/create.html` and do it with Jinja blocks.


nice!Thanks a lot!
