### ISSUE TITLE
ImageUpload endpoint problem + path should accept a callable.

### ISSUE THREAD

**Issue by rochacbruno** [flask-admin/flask-admin#269]
in form/upload.py line 84 the use of **endpoint** is wrong.

take this example

``` python
    form_extra_fields = {
        'path': form.ImageUploadField(
            'Image',
            path=os.path.join(settings.MEDIA_ROOT, 'images'),  # I used settings because **current_app.config** does not works inside admin view __init__ method
            thumbnail_size=(100, 100, True),
            # endpoint="media"
        )
    }
```

On the above example, my image is uploaded to `/media/images/filename.extension` I already have mapped **media** as a send_from_directory url.

I do not know how to pass the endpoint because if I pass `endpoint='media'` it creates wrong url `/media/filename.extension`  and I need `/media/images/filename.extension`. if I pass endpoint = 'media/images' it gives me werkzeug build error.

Also, I think **path** should accept a callable, maybe it is useful to calculate some things to build a path, I can build a path based on datetime or maybe based on current_user.

**Comment by ufo911** [comment]
@rochacbruno 
Can you add full example for mongoengine ? I am having additional stringfield and pre_saving image from the model with @classmethod in directory and updating stringfield with path, i need better solution
