### ISSUE TITLE
Failed to create model. Incompatible collection type: list is not set-like error

### ISSUE THREAD

**Issue by joejean** [flask-admin/flask-admin#275]
Hi, 
I have the following model: 
class Professor(db.Model):
    id = db.Column(db.Integer, primary_key = True )
    professor_name = db.Column (db.String(80), unique= True, nullable = False,\ index = True)
    courses = db.relationship('Course', secondary = course_professors , \ backref='professor', collection_class=set)

When I try to add a professor in flask-admin, I get the error: "Failed to create model. Incompatible collection type: list is not set-like error"

Note the "collection_class = set " on the relationship. I guess that's the reason for the error. How do I fix this without removing the set in my model? Thanks

**Comment by prowler0305** [comment]
> Can you try following:
> 
> ```python
> form_args = {
>   'courses': {
>       'query_factory': lambda: db.session.query(Course)
>   }
> }
> ```

I still had to do this in order to get the query_factory() to work to override the list of values for my form field.
