### ISSUE TITLE
Fix M2M relations in SQLA admin (search, etc)

### ISSUE THREAD

**Issue by mrjoes** [flask-admin/flask-admin#279]
Verify relations

**Comment by mvd7793** [comment]
Spent a while looking around for this. +1 for usefulness. :)

**Comment by tyler274** [comment]
+1

**Comment by ix5** [comment]
Mainly, I just want tagging to work without having to go through all the hopes from some blog posts.
I have posted a bounty of 20 USD, and I'll throw in some home-baked cookies for anyone who can get sqla m2m relationships to "just work" inline.

**Comment by jmagnusson** [comment]
I added another $20. Properly fixing M2M for searches and filters would be a great improvement to Flask-Admin.

**Comment by mrjoes** [comment]
This was already fixed with this https://github.com/flask-admin/flask-admin/commit/db3ee4b01944359f9839c0e3d99fdba640d4d25d

I updated example to show how to use them - https://github.com/flask-admin/flask-admin/commit/ae75c20cc4267909a2f44c1291ec69554d1e3b1e

Catch is in filter/search/etc declaration - you have to use strings for Flask-Admin to trace path between relations. Just in case, you can do deeply-nested relations too and Flask-Admin will automatically add INNER JOIN.

**Comment by ix5** [comment]
Can confirm search and filtering works. Great job @mrjoes !
If only adding m2m(not parent-child) models inline via ajax would be as easy...

**Comment by SBillion** [comment]
It doesn't work for me. If I have a manytomany between Place and User, when I want to find all users who modified places by filtering with city_name contains, I get the number of entry in the association table and not the number of distinct user. Moreover, pager is broken in that case.
If I add a filter on users.slug (unique) and I keep the filter on places.city_name, I don't get 1 as count result and I have a lot of pages with only 1 entry each time.
Maybe I'm just doing something wrong and I'll be really greateful to know the good way

**Comment by johnsonc** [comment]
@SBillion Can you put up a snippet of the code?
