### ISSUE TITLE
Read-Only detail page for model admin

### ISSUE THREAD

**Issue by Cosmius** [flask-admin/flask-admin#334]
Is there a plan for a read-only detail page support for model admin? some time i want to enable detail view but not editing. I reject all POST requests for some location, but I think it's not a good idea since the form exists and just produces 405 :(

**Comment by xqliu** [comment]
read only view +1, this is a common requirement for some backend CRUD operations.

**Comment by peteristhegreat** [comment]
The details view covers this Read Only feature really well.  It looks like the authors merged in a big portion of the proposed pull request.  It isn't a modal, but it works really well.

Add to your subclass of `sqla.ModelView`... (probably right next to where you have `is_accessible`) and add in: 

    can_view_details = True

This adds a little eye-ball next to the pencil and the trash-can icons.

If you combine this with 

    can_delete = False
    can_edit = False

you end up with a Read Only view.

Below are some snippets of a way to use it:
```
# views/restricted_views.py
from flask_admin.contrib import sqla

class AuthorizedReadOnlyModelView(sqla.ModelView):
    can_view_details = True
    can_delete = False
    can_edit = False

    def __init__(self, model, session):
        # Just call parent class with predefined model.
        super(AuthorizedReadOnlyModelView, self).__init__(model, db.session)

    def is_accessible(self):
        return _isSuperAdmin()

class RestrictedAdminIndexView(admin.AdminIndexView):
    def is_accessible(self):
        return _isSuperAdmin()
```

```
# views/__init__.py
import flask_admin as admin
from restricted_views import RestrictedAdminIndexView, AuthorizedReadOnlyModelView

admin_routes = admin.Admin(name='Read-Only Admin Pages', template_mode='bootstrap3',
    index_view=RestrictedAdminIndexView())

def init_app(app):
    admin_routes.add_view(AuthorizedReadOnlyModelView(User, db.session))
    admin_routes.init_app(app)
```
