### ISSUE TITLE
embedding ModelViews

### ISSUE THREAD

**Issue by sdementen** [flask-admin/flask-admin#337]
Hello,

In SQLAlchemy, I have tree like structure of models like
  Company --> Department --> Service --> Role          (--> = has 1 to many)
with each model having its own attributes.

I would like to define an Admin class (ie a ModelView) for each model (CompanyAdmin, DepartmentAdmin, etc) and be able to embed the form from a ModelView within the form of the "parent" ModelView.
For instance, in the CompanyAdmin, embed the DeparmentAdmin form that itself has the ServiceAdmin form embedded and etc., something like

``` python
class CompanyAdmin(ModelView):
    """name and legal_form are attributes of a Company model
    departments is the backref for the Deparmtment model instances linked to the Company"""
    column_list  = ('name', 'legal_form')
    form_columns  = ('name', 'legal_form', 'departments')
    # the reference to departments will embed the DepartmentAdmin form within the CompanyAdmin form (a bit like the inline_models

class DepartmentAdmin(ModelView):
    column_list  = ('name', 'is_profit_center')
    form_columns  = ('name', 'localisation', 'is_profit_center', 'services')
    # and in the DepartmentAdmin form, we will find the ServiceAdmin forms also embedded

class ServiceAdmin(ModelView):
    column_list  = ('name', 'purpose')
    form_columns  = ('name', 'purpose', 'roles')
    # and this down to the roles

class RoleAdmin(ModelView):
    column_list  = ('name', )
    form_columns  = ('name', 'description')
```

I do not know if there is a (easy) way to do this with flask-admin within the sqlalchemy modelview (i have the impression that with mongoengine, they can have subdocuments embedded in documents).
If I can also switch from embedding form_view to embedding list_view, that would be great !

Sebastien

**Comment by jmagnusson** [comment]
Have you thought any more about nested inline models, @mrjoes? Should we have an open ticket for it?

**Comment by mrjoes** [comment]
Well, I thought about it and I think it should be possible to do, but I'm not sure it create efficient UI and there's no other way to do same thing.

**Comment by jmagnusson** [comment]
I think we could have at least one more level without it looking too fucked up. Below I played some with the dom to see how it would look. We could perhaps allow deeper levels by putting them in a modal window. See the third image.

_2 levels_
![screen shot 2015-03-09 at 09 07 24](https://cloud.githubusercontent.com/assets/190835/6551644/228ff998-c63c-11e4-9309-a7f5f79afdfa.png)

_3 levels_
![screen shot 2015-03-09 at 09 13 32](https://cloud.githubusercontent.com/assets/190835/6551694/0647c5ee-c63d-11e4-8099-b881a7cbb5e5.png)

_4 levels modal button_
![screen shot 2015-03-09 at 09 15 50](https://cloud.githubusercontent.com/assets/190835/6551699/2246b890-c63d-11e4-80ec-dbb7661e66c1.png)

**Comment by harveyslash** [comment]
Is there any way to link to the nested item instead of doing multi nesting? 

I have a table of `Parent -> child -> grandchild -> great_grand_child ` 
I can do inline of `parent-> child`  and the forms show up as child #1 , child #2 , etc. , which is great. 

How can I override this child #1 , 2 etc to point to the edit link of child #1 itself so that I may then edit grand child , and so on. 

Is there a better way to do this than what I suggested ?

**Comment by toniree** [comment]
Is this supported now? Rendering embedded objects' fields in its parents view

**Comment by Antoine-Falquerho** [comment]
@jmagnusson how were you able to do that? can you share the code? I would like to have more than 1 level as well.

**Comment by toniree** [comment]
@Antoine-Falquerho He is in the Edit or Create View. Flask automatically does that for you if you use a an EmbeddedField. I don't think embedding in Read view (top level) is supported.

**Comment by Antoine-Falquerho** [comment]
Thanks, @toniree 
I have been using `inline_models`
```
    inline_models = [
        (
            Sku,
            dict(
                form_columns=[
                    "id",
                    "color",
                ]
            ),
        ),
    ]
```

Sku also have images, how can I add images to the form on the edit view?

**Comment by Antoine-Falquerho** [comment]
@toniree @jmagnusson any chance you can share the code to be able to add/edit/delete grandchild in the form?
I have 3 models,
Parent > child > grand child:
I would like to edit the parent, then add/edit child and for each child, add/edit grandchild.

I have been struggling with that part for a while.
Thanks
