### ISSUE TITLE
Support Themes

### ISSUE THREAD

**Issue by jniltinho** [flask-admin/flask-admin#342]
Support change default themes in local app.

Change css, img, js to -> http://bootstrapmaster.com/live/simpliq2/ on local app

**Comment by harishkashyap** [comment]
This will be super useful! is there an example of how to make a custom bootstrap theme work easily without much editing of css, js and other html components?

**Comment by pawl** [comment]
@harishkashyap There's some talk about how to implement bootstrap themes here: https://github.com/flask-admin/flask-admin/pull/1016#issuecomment-134437376

**Comment by harishkashyap** [comment]
Thanks @pawl. I will try it. I found that theming the release version is quite painful also because of my partial knowledge working with css, javascript and boostrap.

**Comment by harishkashyap** [comment]
The theme works wonderfully locally but when deployed behind nginx, they don't get rendered properly. any ideas? @pawl, @rochacbruno

**Comment by harishkashyap** [comment]
This works great! thanks.
