### ISSUE TITLE
Trying to add form_widget_args to sub document form in mongoengine modelview

### ISSUE THREAD

**Issue by bool-dev** [flask-admin/flask-admin#361]
I have been trying to add form_widget_args to a field in a mongonengine EmbeddedDocument, using:

```
form_subdocuments = {
    'author': {
        'form_widget_args': {
            'name': {'disabled': True}
        }
    }
}
```

but it does not work. Is this not yet supported?
p.s. - For main document fields widget_args work perfectly.

Edit:
Also tried, without any luck:

```
form_widget_args = {
    'author.name': {'disabled': True}
}
```

**Comment by SophiaAP** [comment]
One workaround for this is to add a read-only flag to subdocuments at the database level. To do this, add SQLAlchemy's `viewonly=True` configuration to the relationship in your model definition.

`children = relationship('Category', backref=db.backref('parent', remote_side=[id]), viewonly=True)`

See [SQLAlchemy Relationship Parameters](http://docs.sqlalchemy.org/en/latest/orm/relationship_api.html#sqlalchemy.orm.relationship.params.viewonly).

**Comment by ufo911** [comment]
@cybertoast 
Can you tell me how to get worked Ckeditor widget for name in EmbeddedDocument

class EmbeddedService(EmbeddedDocument):
    name = StringField()

class Service(Document):
...
    services = ListField(EmbeddedDocumentField(EmbeddedService))
...

**Comment by ufo911** [comment]
I just did it :D 

`    form_subdocuments = {
        'sections': {
            'form_subdocuments' : {
                None : {
                    'form_subdocuments': {
                        'procedures': {
                            'form_subdocuments': {
                                None: {
                                'form_overrides' : dict(desc_ka=CKTextAreaField,desc_en=CKTextAreaField,desc_ru=CKTextAreaField)
                                }
                            }
                        }
                    }
                }
            }
        }
    }`

**Comment by suckmybigdick** [comment]
@ufo911 thanks!
