### ISSUE TITLE
One to one relationship breaks admin

### ISSUE THREAD

**Issue by iurisilvio** [flask-admin/flask-admin#376]
A small example of my model:

``` python
class XXX(db.Model):
    id = db.Column(db.Integer, primary_key=True)


class YYY(db.Model):
    id = db.Column(db.Integer, db.ForeignKey('xxx.id'), primary_key=True)

    xxx = db.relationship(XXX, lazy='subquery',
        backref=db.backref('yyy', uselist=False, lazy='subquery'))
```

The edit view expect a list (one-to-many?). If I have the instance `XXX.yyy`, I receive a `TypeError: argument of type 'YYY' is not iterable`. If `XXX.yyy is None`, I receive a `TypeError: argument of type 'NoneType' is not iterable`.

Looks like flask-admin is expecting a list instead of a one-to-one relationship.

I'm using flask-admin 1.0.7 with SQLAlchemy. What I'm doing wrong?

**Comment by MarcusMann** [comment]
@hongquan  and @iurisilvio 

Instead of use `inline_models` use `inline_model_form_converter`

e.g:

`inline_model_form_converter = OwnerPermission`
