### ISSUE TITLE
MongoEngine: filtering on ReferenceFields, EmailFields etc.

### ISSUE THREAD

**Issue by bhanuvrat** [flask-admin/flask-admin#400]
I am trying to add column_filter for ReferenceFields and Email fields:

```
class UserView(ModelView):
    can_delete = False
    column_filters = ('email',)
admin.add_view(UserView(models.User))
```

but I get the error:

```
Exception: Unsupported filter type email
```

Am I missing something trivial or is it not supported yet?

**Comment by Thx3r** [comment]
Hello, may be it will help https://github.com/Thx3r/flask-admin-mongoengine-filter-referencefield

**Comment by ufo911** [comment]
@gordol Your Solution helped !! Thanks
