### ISSUE TITLE
Multiple actions in lists

### ISSUE THREAD

**Issue by evidens** [flask-admin/flask-admin#44]
For a project of mine, I need to select multiple items to carry out an action (in my case consolidate duplicate records).

I've started implementing a generalised format so other actions can be added by individuals (inspired by actions in Django with some implementation details cribbed from flask-peewee's admin module).

I've started with delete selected. I plan on cleaning it up for more general use but wanted to open it up to feedback before I go completely down the path.

https://github.com/beyondwords/flask-admin/commit/c7a3ba94fa425610b41df8b3fd59d6128bf7a744

Please contribute any comments on architecture.
- An action is called with the `BaseModelView` sub-class, `request`, and `id_list`
- The action **must** have `label` specified for the drop-down list
- The action must check for permissions `is_accessible`, `can_delete` etc.
- The action can either return a redirect/rendered page or `None` and use a flash message to return to the list
- The action can be a simple function or a class instance with `__call__` implemented

**Comment by emve-dev** [comment]
I wish this was included in docs and not just in API section. Spent much time to figure this out reading the source code.

**Comment by petrus-jvrensburg** [comment]
@emve-dev Yes definitely! 

Would you mind adding a couple of paragraphs and code snippet to https://github.com/flask-admin/flask-admin/blob/master/doc/advanced.rst?

**Comment by emve-dev** [comment]
My pleasure. https://github.com/flask-admin/flask-admin/pull/970

**Comment by petrus-jvrensburg** [comment]
Thanks, that's perfect!

**Comment by boolbag** [comment]
@emve-dev 
Wondering if you would happen to have thoughts on [this related functionality](https://github.com/flask-admin/flask-admin/issues/998) (custom actions in list view)?

Thanks in advance to anyone who might share insights.

**Comment by R2calex** [comment]
> Hi,
> 
> I pushed my changes. You can see how mass delete action was implemented
> for SQLA models here:
> 
> https://github.com/mrjoes/flask-admin/blob/master/flask_admin/contrib/sqlamodel/view.py#L553
> 
> So, if you want to add your custom action:
> 
> 1. Create method which accepts list of ids
> 2. Decorate it with @action
> 3. Change is_action_allowed to do some fancy logic
> 
> Checkboxes won't be displayed if no actions are visible (drop down element
> won't be displayed either).
> I also separated actions library into separate file, so file admin is now
> using it and can mass-delete files too.
> 
> Hope it helps.
> 
> Serge.
> 
> On Sun, Aug 19, 2012 at 6:02 AM, F. Gabriel Gosselin <
> [notifications@github.com](mailto:notifications@github.com)> wrote:
> 
> > I agree that Flask-Peewee's approach is not ideal (the delete and export
> > are hard coded).
> > Please do look at the code I contributed. It does have the potential to be
> > flexible. Actions can be added to self._actions through a setter instead
> > to make it more flexible on a per-AdminModel basis.
> > In particular I'm curious how you would handle universal actions
> > (available to all Admin lists).
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/[mrjoes/flask-admin/issues/44](https://github.com/mrjoes/flask-admin/issues/44)#issuecomment-7850159.

Page not found :(, could you make it post it again please?
