### ISSUE TITLE
Validation should be omitted on disabled fields

### ISSUE THREAD

**Issue by fdellavedova-zz** [flask-admin/flask-admin#441]
I have a model view like this

class MyView(ModelView):
    form_columns = ('id', 'name', 'active')
    form_widget_args = {
        'name': {'disabled': True},
        'id': {'disabled': True},
    }

Basically I want to show the primary key and the name, but I don't want people to be able to modify them.
What happens though, is that after editing the field 'active', the user gets a validation error "field is required" on the 'id'.
I think validation on disabled fields should be disabled as well by default?

**Comment by Atala** [comment]
Hi,

I just applied this trick (widget with a disabled input field for display + an hidden field for submission). Is this the cleanest way?

I didn't manage to have access to the model field values in my widget without including these fields in 'form_columns', did I miss something?

Thanks,

Alois
