### ISSUE TITLE
Integrating with flask-pagedown

### ISSUE THREAD

**Issue by kepbod** [flask-admin/flask-admin#443]
I am new to flask and I love this extension. Because I store some texts with markdown syntax in the database, and I want to have a markdown previewer in flask admin. I found [flask-pagedown](https://github.com/miguelgrinberg/flask-pagedown/) have these functions, but I don't know how to integrate it with flask-admin. Could you offer some examples? Thanks!

**Comment by duolaaa** [comment]
hi mrjoes, i am now using flask-admin to build my blog background, i have seen the example of  wysiwyg, but i want to use pagedown like [google pagedown](https://code.google.com/archive/p/pagedown/) to edit my blog's articles. the markdown editor like stackoverflow or github . can i hava some way to achieve this function, can you give me some advice ? thank you very much, I greatly appreciate your can reply to me.

**Comment by automoto** [comment]
FYI the link in @mrjoes reply now 404's, the current wysiwyg example can be found here:
https://github.com/flask-admin/flask-admin/tree/master/examples/wysiwyg
