### ISSUE TITLE
how to set readonly fields for the edit_form?

### ISSUE THREAD

**Issue by istommao** [flask-admin/flask-admin#446]
how to setter readonly fields for the edit_form?

**Comment by pawl** [comment]
Added an example of this to the docs here: https://github.com/flask-admin/flask-admin/pull/1251

**Comment by william-tu** [comment]
but set the field disabled to true ,the field can not be created 
for example:

    form_widget_args = {
        'pic_url': {
            'disabled': True,
        }
    }
when i want to create ,i got this
![default](https://user-images.githubusercontent.com/20549680/30854914-b64be81c-a2e5-11e7-8645-adde21d346fc.png)

and there is still a delete button when i enter the edit view
![default](https://user-images.githubusercontent.com/20549680/30855036-18515132-a2e6-11e7-889e-f3c7538e4dc5.png)
