### ISSUE TITLE
Unique validator does not work for Flask-WTF forms

### ISSUE THREAD

**Issue by lingthio** [flask-admin/flask-admin#486]
This is about the Unique validator when saving an EXISTING object.

When using WTForms directly (wtforms.Form), the Unique validator, works by excluding the current object from the SQLAlchemy query because of this line:

```
if not hasattr(form, '_obj') or not form._obj == obj:
```

When using Flask-WTF however (flask.ext.wtf.Form), the Unique validator no longer excludes the current object because form._obj does not exist.

Possibly because of this issue:
https://github.com/wtforms/wtforms/pull/29

With the following workaround:
https://bitbucket.org/mscully/datamart/commits/aac37c2c6298f0e5cbf75d325fad14c6b9f39296

Simplest app to reproduce:

```
from flask import Flask
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.admin import Admin
from flask.ext.admin.contrib.sqla import ModelView
from flask.ext.wtf import Form

class ConfigClass(object):
    # Configure Flask
    SECRET_KEY = 'THIS IS AN INSECURE SECRET'                        # Change this for production!!!
    SQLALCHEMY_DATABASE_URI = 'sqlite:///admin.sqlite'  # Use Sqlite file db
    CSRF_ENABLED = True

app = Flask(__name__)
app.config.from_object(__name__+'.ConfigClass')
db = SQLAlchemy(app)

class MyModelView(ModelView):
    # Make Flask-Admin use Flask-WTF
    form_base_class = Form

class TestObject(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    code = db.Column(db.String(30), nullable=False, server_default='', unique=True)

if __name__ == '__main__':
    admin = Admin(app)
    admin.add_view(MyModelView(TestObject, db.session))

    db.create_all()
    app.run('0.0.0.0', 5001, debug=True)    
```

**Comment by ryrithgithub** [comment]
Try this code
`validators=[Unique(model= Product, get_session=lambda : db)]`
check out the following link for more code at http://developer.e-power.com.kh/unique-validation-for-wtforms/
