### ISSUE TITLE
Per Blueprint Admin

### ISSUE THREAD

**Issue by italomaia** [flask-admin/flask-admin#491]
When trying out flask-admin, I missed a feature where I could "link" a set of view/modelviews/etc in a per blueprint bases. I'm thinking on creating my own integration using flask-empty skeleton, but a integrated solution would be more awesome.

**Comment by tevino** [comment]
@mrjoes Do you have any plans to address this issue?

I'm asking because the previous assumption has now changed:
> That's not possible - internally Flask-Admin creates blueprint and Flask does not support nested blueprints.

Flask now supports nesting blueprints: https://flask.palletsprojects.com/en/2.3.x/blueprints/#nesting-blueprints
