### ISSUE TITLE
Detach endpoint from "blueprint name"

### ISSUE THREAD

**Issue by italomaia** [flask-admin/flask-admin#513]
First discussed as a important change required by the pull request https://github.com/mrjoes/flask-admin/pull/506 I believe this subject deserves a forum of its own.

Here is the problem:

For flask, a endpoint is the "anchor" used to retrieve a url path related to a view. 
In flask-admin, it has a secondary role: it is used to _name_ the blueprint created for each view. This basically means you cannot have two view's with the same endpoint. 

Furthermore, you could have blueprint name collision between the "endpoint of a view" (actually, the blueprint auto-generated for the view) and the name o a specific blueprint in your project. 

See this gist example: https://gist.github.com/italomaia/11309843

There you have a sane example of name collision. Which is the easiest way to fix this? You would have to provide a custom endpoint to your model. It would not be possible to fix this problem without changing the endpoint and, doing so, in worst case scenario, would require some code rewrite (wiki.index_view endpoint could become wiki_model.index_view per example).

If the view had a name unique identifier, it would be possible avoid this problem in a more ellegant manner, I think.

Opinions?

**Comment by mrjoes** [comment]
I'm going to implement configurable endpoint name logic. I saw many requests that were asking to have 'admin.' prefix, etc.

Even though I'm bumping up old task, should be able to do it soon enough.

**Comment by Kylotan** [comment]
Is there any change regarding this? I want to have a ModelView for my SQLAlchemy 'User' object, and I also have a 'user' blueprint for the main app, but the system doesn't allow this. Even if I explicitly provide a new name to ModelView, that gets ignored by `create_blueprint` which just passes `__name__` to the Blueprint constructor instead.

**Comment by jeanphilippegoldman** [comment]
is the point of this discussion is to be able to tune the default '/admin' endpoint to stg else ? i have another plugin using 'admin' blueprint and therefore have a blueprint collision. or did i misunderstand the whole thing ?. thanks for you answer.

**Comment by petrus-jvrensburg** [comment]
You can change the default by specifying a value for the `url` parameter like:

`admin = admin.Admin(app, name='Example App', template_mode='bootstrap3', url='/example')`

There's also an `endpoint` parameter that's useful for avoiding name clashes between blueprints.
