### ISSUE TITLE
localize filters

### ISSUE THREAD

**Issue by moulinux** [flask-admin/flask-admin#514]
I read in the french admin.po that filters have been translated, for exemple contains is used in flask_admin/contrib/sqla/filters.py:52 :+1: 

return gettext('contains')

running flask-admin in french, the localization is completed, except for filters : contains, equals, .. are not localized

dont't understand why...

**Comment by tahajahangir** [comment]
@mrjoes Filters are *cached* at *import time*, so their language will stick on default language. This prevents localizitation of filters.
