### ISSUE TITLE
NDB

### ISSUE THREAD

**Issue by JosefJezek** [flask-admin/flask-admin#519]
Could you add support for NDB?

https://developers.google.com/appengine/docs/python/ndb

**Comment by mrjoes** [comment]
Pull requests are always welcome.

**Comment by pawl** [comment]
This was actually added by @longhotsummer earlier this year. So, this is actually fixed.

https://github.com/flask-admin/flask-admin/blob/master/flask_admin/contrib/appengine/view.py
