### ISSUE TITLE
primary key is not shown in ModelView

### ISSUE THREAD

**Issue by mfrasca** [flask-admin/flask-admin#52]
not sure whether this is a bug report or just a question.

regarding the visibility of primary keys.

working:
I have a table (Country) with automatic integer primary key and a table (Country_division) referring to it. When I insert a country_division in its table, the interface allows me to select a country. I never see the value of the primary key, but it works.

not working:
I have a table (rank) with string primary key that is manually assigned. as above, I cannot see the column in the interface, but this is now a problem, because I can't specify the key manually.

since I'm still giving form to the database, I can consider falling back to automatic integer primary keys.

**Comment by threemonks** [comment]
Has this issue actually being resolved? I am looking into using flask-admin as my flask web app managing interface instead of writing editing pages for each database object, but unable to specify primary key when creating new object makes this task impossible.

I think a parameter form_display_pk = True should do, and the editing template should just make primary key field not editable.

**Comment by fuzzyami** [comment]
also upvoting here for simple, out of the box option to show the primary key(s). having to write code for this basic functionality is needlessly complicated.

**Comment by MoSunDay** [comment]
```
from ..models import User, UserGroup, Group, Role, PolicyRole, Cluster, Policy


class MfmdView(ModelView):
    def __init__(self, model, session, name=None, category=None, endpoint=None, url=None, **kwargs):
        for k, v in kwargs.items():
            setattr(self, k, v)

        super(MfmdView, self).__init__(model, session, name=name, category=category, endpoint=endpoint, url=url)

    def is_accessible(self):
        return True


def model_list_columns(class_name):
    list_columns = list()
    for attr_key in class_name.__dict__.keys():
        if not attr_key.startswith("_"):
            list_columns.append(attr_key)
    return list_columns


def model_link_view(model_list):
    for model in model_list:
        admin.add_view(MfmdView(model, db.session, column_list=model_list_columns(model)))


model_link_view([User, UserGroup, Group, Role, PolicyRole, Cluster, Policy])
```
This also works well

**Comment by carlosvega** [comment]
Just add:

`column_display_pk = True`

**Comment by hugodutka** [comment]
The solution that worked for me was subclassing `ModelView` and overriding its constructor.
```python
class AdminView(ModelView):
    def __init__(self, model, *args, **kwargs):
        self.column_list = [c.key for c in model.__table__.columns]
        self.form_columns = self.column_list
        super(AdminView, self).__init__(model, *args, **kwargs)
```

**Comment by topher200** [comment]
To show the primary key in list view, use `column_display_pk`, like this:

```
class MyModelView(BaseModelView):
        column_display_pk = True
```

Documentation: https://flask-admin.readthedocs.io/en/latest/api/mod_model/#flask_admin.model.BaseModelView.column_display_pk
