### ISSUE TITLE
filter submit None Error

### ISSUE THREAD

**Issue by nsdont** [flask-admin/flask-admin#547]
see image:
![image](https://cloud.githubusercontent.com/assets/1725434/3073737/03db937a-e304-11e3-8ca7-d8ed2873ec9d.png)
Error:
sqlalchemy.exc.DataError: (DataError) invalid input syntax for integer: ""
LINE 3: WHERE lending_project_plan.period = ''

I fund code(https://github.com/mrjoes/flask-admin/blob/master/flask_admin/contrib/sqla/view.py#L729):
don't check value Null

**Comment by pawl** [comment]
Filters have changed a lot since 2014, and I believe this should be fixed now. Please reopen if this is still an issue.
