### ISSUE TITLE
Custom base url is misleading about index view

### ISSUE THREAD

**Issue by iurisilvio** [flask-admin/flask-admin#561]
```
class IndexView(AdminIndexView):
     pass

admin = Admin(app, url='/foo', index_view=IndexView())
```

I know the behaviour is well documented but it is really misleading.

The code above will add any view relative to `/foo`, but the `/foo` give me a 404. The index view is mounted in `/admin`.

I expected it to mount the index view in the admin (`/foo/`). To fix it, I have to initialize `IndexView(url='/foo')`.

It is easy to change the behaviour, but is is not backward compatible.

**Comment by petrus-jvrensburg** [comment]
Closing this now, but please re-open if it's still a problem.
