### ISSUE TITLE
ModelView in Index page

### ISSUE THREAD

**Issue by gohoho** [flask-admin/flask-admin#580]
Is there is a way to view Model on the admin home page?

**Comment by daimon99** [comment]
@gohoho How you made ModelView as your index page?
I followed your methods, but failed:
```
werkzeug.routing.BuildError: Could not build url for endpoint 'admin.static' with values ['filename', 'v']. Did you mean '/.static' instead?
```

**Comment by daimon99** [comment]
I have resolved the problem, do like this:
```
    admin = Admin(
        app,
        name=app.config['SITE_NAME'],
        template_mode='bootstrap3',
        index_view=MyIndexView(
            Statics, db.session,
            url='/'
        ),
class MyIndexView(ModelView):
    def __init__(self, model, session, *args, **kwargs):
        super(MyIndexView, self).__init__(model, session, *args, **kwargs)
        self.static_folder = 'static'
        self.endpoint = 'admin'
        self.name = '首页'
```

**Comment by LotosikRa** [comment]
I have another question - how to show simple text without any model?

**Comment by LotosikRa** [comment]
https://flask-admin.readthedocs.io/en/latest/introduction/#adding-your-own-views
`
admin = Admin(
    app,
    name=app.config['SITE_NAME'],
    template_mode='bootstrap3',
    index_view=MyIndexView(
        name='Home',
        endpoint='/'
   ),
)

class MyIndexView(BaseView):
    @expose('/')
    def index(self):
        return self.render('myindex.html')
`
**not tested**

**Comment by LotosikRa** [comment]
@LotosikRa

```
admin = Admin(
    app,
    name='Users',
    template_mode='bootstrap3',
    index_view=AdminIndexView(
        template='admin_home.html'
    )
)
```

**Comment by imasish** [comment]
how to pass more than 1 table in this?
