### ISSUE TITLE
"Invalid file extension"-Error when not selecting a new image when saving model

### ISSUE THREAD

**Issue by danieldiekmeier** [flask-admin/flask-admin#611]
So I have a model which should contain a path to an image. I implemented that with the `ImageUploadField` and it generally works: When adding a new object or when overwriting the image with a new one, all is well.

But if i just want to change the title of the model, and don't even want to touch the image, it goes wrong. I get an "Invalid file extension"-error and the upload field gets red.

I downloaded the examples to see if the error exists there, too, and it does. (in examples/forms/simple.py).

What can I do? I don't want the users to have to upload the same image whenever they want to change something in the object.

**Comment by danieldiekmeier** [comment]
¯\_(ツ)_/¯

**Comment by mrjoes** [comment]
I'll keep it open, apparently there were some changed related to FileUploadField - will take a look.
