### ISSUE TITLE
Column filter names in relationships

### ISSUE THREAD

**Issue by iurisilvio** [flask-admin/flask-admin#614]
My model has a `name` field and a relationship, which has a `name` too. Something like `x.name` and `x.y.name`.

``` python
class XView(ModelView):
    column_labels = dict(name='X Name')
    column_filters = ('name', 'y.name')
```

My menu has a `X Name` and a `Y / X Name`. I want to define a name to `y.name` too, but looks like it is not possible.

**Comment by torotil** [comment]
I've just posted a workaround in #1106 which seems to be a duplicate issue or vice-versa.

**Comment by pawl** [comment]
Just tried this on the sqla/app2.py example on master, seems to work fine with:
```
    column_filters = ['car.id']
    column_labels = {'car.id': 'blah'}
```
