### ISSUE TITLE
Idea: URL with slug

### ISSUE THREAD

**Issue by hongquan** [flask-admin/flask-admin#627]
It will be good if we can access to
```
/admin/model/slug/edit/
```
in addtition to
```
/admin/model/edit/?id=1
```

**Comment by jonafato** [comment]
Why slug rather than id?

**Comment by rochacbruno** [comment]
Not every content is a "post" or a "page", there are cases where slug doesn't exist.

What you want is more a CMS feature than an general purpose admin feature.

(take a look at www.quokkaproject,org)

**Comment by hongquan** [comment]
@jonafato Slug allow me to type the address to go to edit page for a certain object quicker, don't have to click to dashboard, to menu, to list page, and to edit.

@rochacbruno That is why I used "in addtition to", not "instead of". I don't want to drop completely the use of ID, but the use of slug can be an additional support.
