### ISSUE TITLE
flask-admin pages inaccessible in production

### ISSUE THREAD

**Issue by Kyrill76** [flask-admin/flask-admin#669]
Hi,
I did a pretty simple implementation of flask-admin in my flask application, without creating any html pages, with something like this:

> admin = admin.Admin(app, 'App Administration')

It works really well in development, and I can access the admin pages via mysite.com/admin/ .

Now, when I want to deploy my app with Apache and mod_wsgi, everything works fine at mysite.com/myapp/ , except flask-admin, which I expected to be available at mysite.com/myapp/admin (but I just get a 404).

Is there some extra configuration to be done with Apache ?
I didn't see anything in the documentation about going into production.

Here's my Apache configuration:

>  &lt;VirtualHost *:443>
>         WSGIDaemonProcess myapp user=myapp group=myapp threads=5
>         WSGIScriptAlias /myapp /var/www/code/MyApp/wsgi/myapp.wsgi
>         WSGIScriptReloading On
>         WSGIPassAuthorization On
>         SSLEngine on
>         SSLCertificateFile /var/www/code/MyApp/ssl.crt
>         SSLCertificateKeyFile /var/www/code/MyApp/ssl.key
>         SSLVerifyClient None
>         SSLOptions +StdEnvVars
>       &lt;Directory /var/www/code/MyApp/wsgi>
>                            WSGIProcessGroup myapp
>                            WSGIApplicationGroup %{GLOBAL}
>                            Order deny,allow
>                            Allow from all
>         &lt;/Directory>
> 
> &lt;/VirtualHost>

I checked the Apache error log but I don't get any error.

Thanks for any help.

**Comment by bdemirtas** [comment]
Hi,

Actually, I am facing the same problem. I did all nginx configuration possble and for flask but still, when I try to edit a model, I receive a 500 error. Here my config, its a [gist](https://gist.github.com/bdemirtas/c4ef51b66e4b5ad58bac) file.


Thank You

Burak

**Comment by harishkashyap** [comment]
Same issue guys! its a pain. I am trying to run the app in uwsgi and none of the links are routed. Seems like flask-admin isn't good enough for production environment. uwsgi + flask + nginx is standard and if that isn't working well then perhaps better to switch to something else.

uwsgi --http 0.0.0.0:3031 --wsgi-file app.py --callable app --stats-server 0.0.0.0:3032 --processes 10

**Comment by mrjoes** [comment]
@harishkashyap Well, I'm sorry, but it certainly not Flask-Admin problem. It is your problem.

Please enable Flask debugger and see why 500 is showing up. I suspect it has something to do with your database permissions.

**Comment by harishkashyap** [comment]
Thanks @mrjoes for your quick response. I appreciate it. However, it indeed is a flask-admin issue unless you can prove otherwise.

Yes, it is initialized properly. Here are steps to repeat the bug quickly:

go to flask-admin/examples/pymongo

1) python app.py works perfectly. 
2) uwsgi --http :3031 --wsgi-file app.py --callable app --stats-server 0.0.0.0:3032 --processes 10

only shows the home page and none of the other pages are rendered. 
uwsgi as you might already know is the best way in production to host the flask app.

**Comment by mrjoes** [comment]
I'm using uwsgi with Flask and Flask-Admin in large project in production it works fine.

And only reason why this particular sample does not work with uwsgi:

```python
if __name__ == '__main__':                                                                                    
```

This check fails if script is hosted by uwsgi and Flask-Admin is not initialized.

**Comment by harishkashyap** [comment]
Thanks @mrjoes. Can you please point a quick example where the uwsgi works with?

**Comment by mrjoes** [comment]
It seems like `layout-bootstrap3` example initializes Flask-Admin globally, so it would work with uwsgi.

Just to reiterate - it has nothing to do with `uwsgi` (or `gunicorn`, `modwsgi`, etc). These samples were supposed to be used by developers to learn how to do various stuff with Flask-Admin.

**Comment by harishkashyap** [comment]
you are right and I am wrong! thanks for the clarification.
