### ISSUE TITLE
Generic Relationships Support

### ISSUE THREAD

**Issue by aphillipo** [flask-admin/flask-admin#670]
Hi Joes,

How easy would it be to add generic relationship support?

http://sqlalchemy-utils.readthedocs.org/en/latest/generic_relationship.html

I think you could then specify the types of model supported in the multiselect:

```
class MyModelForm(ModelView):
    form_args = {
        'generic_relation': { 'models': (ModelTypeOne, ModelTypeTwo) }
    }
```

I might have a stab at building it later if you are open to the idea!  Any tips welcome and I'd obviously need to figure out the frontend.

Ta, A.

**Comment by petrus-jvrensburg** [comment]
Closing this now, but please re-open if it's still relevant. Also, PRs are welcome.
