### ISSUE TITLE
Fields omitted in form_edit_rules are still validated, hence found invalid upon receive

### ISSUE THREAD

**Issue by jgonggrijp** [flask-admin/flask-admin#679]
I have a complex database in which Images can be associated with Pages. When creating a Page, users pick an Image that they uploaded previously (this is required, the `image_id` field is `nullable=False`). When editing the same Page, they are not supposed to be able to pick a different Image; rather, they get the option to add annotations to the Image (which are specific to the Page; the same Image may be used in multiple Pages and have different annotations in each).

So, my intuitive course of action would be to simply omit `image` in the `form_edit_rules`. This _should_ work, because by the time a Page is edited it is already guaranteed to have an Image attached. However, when I tried implementing the edit form in that way, it was impossible for the user to submit the form because the image field was found "invalid" (since it wasn't filled out). I had to keep the field but wrap it in a hiding macro as a workaround. I hope you agree with me that this is an ugly solution.

**Comment by petrus-jvrensburg** [comment]
Closing this now, but please re-open if it's still a problem.
