### ISSUE TITLE
Support uploading images with wrong format postfix.

### ISSUE THREAD

**Issue by Eliacy** [flask-admin/flask-admin#683]
Sometimes, end users name image file as wrong postfix. E.g, they make file name as 'pic.png' but the file data is 'pic.jpg' in fact. And then the ImageUploadField will save it as '.png' but tell the ModelView that it's '.jpg', so the ModelView can not find the uploaded file.

The patch is to modify https://github.com/mrjoes/flask-admin/blob/master/flask_admin/form/upload.py ,
move line 386

```
    filename, format = self._get_save_format(filename, self.image)
```

to be in front of line 380

```
    path = self._get_path(filename)
```

Then the filenames could be consistent.

**Comment by petrus-jvrensburg** [comment]
I don't think this is still a problem. Closing this now, but please re-open if it's still an issue.
