### ISSUE TITLE
Editable extensions in file admin

### ISSUE THREAD

**Issue by msempere** [flask-admin/flask-admin#702]
When 'editable_extensions' is set to empty:

editable_extensions = ()

And all the other options are set to False (mkdir, upload, etc...)  still appears the dropdown button withe Edit option at the end of the page.

**Comment by pawl** [comment]
This was fixed in this commit?: https://github.com/mrjoes/flask-admin/commit/2cb991a244b28b47a281dccf98dba391f7c7d7fc

Doesn't seem to be an issue anymore.

**Comment by msempere** [comment]
Yes @pawl , that commit fixed the problem
