### ISSUE TITLE
Time Based Releases [RFC]

### ISSUE THREAD

**Issue by jirikuncar** [flask-admin/flask-admin#712]
## Problem

Very long time between releases causes problems when known bugs has been fixes in upstream but new version has not been released on PyPI. Also planning of dependent projects is difficult because new versions on _Flask-Admin_ are coming in unpredictable manners. 
## Proposal

Release in time based manners bug fix releases. New feature will get to the release only when it is well tested.

**Repository structure**
- _maint-1.X_ (_maint-1.0_, _maint-1.1_, ...) maintenance branches for **bugfixes only**
- _master_ latest development branch
- _pu_ (proposed updates) for experimental features that can be cherry-picked to _master_

Release _1.X.Y_ regularly - not later than few days/weeks after bugfix has been integrated.
New _1.X_ or _W.X_ should come 2 times per year so project can rely on time when new feature arrives max. 6 months. 

``` text
                                                                
                                                                
     +----------------+----------+----------------> master      
                      |          |                              
     +-----------+----+----+-----+--------->  maint-1.1         
                 |   1.1.0 |    1.1.1                           
     +-----------+---------+---------->  maint-1.0              
                1.0.0     1.0.1                                 
                                                                
```

**Comment by mrjoes** [comment]
Bumping this one. I'm going to create organization, but it won't be strictly Flask-Admin related. I have few ideas for other projects too.

Now, I have to come up with a name and that's hardest part.

**Comment by jmagnusson** [comment]
Just start with `Flask-Admin` as the name and change when/if you materialize those projects?

**Comment by jmagnusson** [comment]
@mrjoes I can see that you created the `Flask-Admin` organization now. Considering how difficult it is to depend on versions not released to PyPI in your own packages I was wondering if you might be able to release a new version to PyPI?

**Comment by mrjoes** [comment]
@pawl Is there something special I should to do in order to include localizations to distributable package?

**Comment by pawl** [comment]
I can't think of anything that needs to be done differently from previous releases.

**Comment by jmagnusson** [comment]
Just `python setup.py sdist/bdist_wheel` and make sure that all the needed files are still in the archive.

**Comment by jmagnusson** [comment]
@mrjoes Anything stopping you from a new release? Would you like some assistance?
