### ISSUE TITLE
Idea: Change logic for actions with checked rows

### ISSUE THREAD

**Issue by ArtemSerga** [flask-admin/flask-admin#713]
Sometimes (in my cases as a rule) it is necessary to make action with filtered rows (i.e. `status='active'`), but not for only selected rows.

I offer:
- rename `With selected` to `Actions`
- if user check rows - action will be executed for selected rows
- if user apply filters and doesn't check anything - action will be executed for filtered rows
- in other cases action will be executed for all rows

For any case developer can add own JS alert message, i.e.:
- Do you want to apply action for selected rows?
- Do you want to apply action to filtered rows?
- Do you want to apply action to all rows?

Also developer can disable action for filters or | and all rows case.

If you ok with this idea - I'm ready to do it.

Thanks!

**Comment by petrus-jvrensburg** [comment]
Closing this now, but please re-open if it's still relevant.
