### ISSUE TITLE
GenericEmbeddedDocumentField support

### ISSUE THREAD

**Issue by Altaisoft** [flask-admin/flask-admin#741]
Hello all,

I cannot find out how to support [GenericEmbeddedDocumentField](http://docs.mongoengine.org/apireference.html#mongoengine.fields.GenericEmbeddedDocumentField) in a Flask-admin application with MongoEngine backend.

That's what I am trying to do in a model definition:

```
data = fields.GenericEmbeddedDocumentField(choices=[
    (OrangeData, 'Orange'),
    (RedData, 'Red'),
])
```

Where `OrangeData` and `RedData` are subclasses of `EmbeddedDocument`. In admin, I get a select box with choice values:
- `<class 'models.OrangeData'>` for `Orange`
- `<class 'models.RedData'>` for `Red`.

And, when submitting, it yells "Invalid choice". The following variant:

```
data = fields.GenericEmbeddedDocumentField(choices=[
    ('OrangeData', 'Orange'),
    ('RedData', 'Red'),
])
```

fails with `Invalid embedded document instance provided to an GenericEmbeddedDocumentField: ['data']`.

I also tried to rename `data`, assuming that might be a reserved name, no success.

Just `fields.EmbeddedDocumentField(OrangeData)` works okay. My intent is to implement the following:
- When creating the new instance, the user will see a list of embedded classes (Orange, Red, Blue, etc), to select a class to use;
- And when editing the instance, there will be no choice to change the embedded document type. User will work with fields defined at that document.

Is it possible to implement using built-in functionality?

Thank you!

**Comment by petrus-jvrensburg** [comment]
replaced by #905
