### ISSUE TITLE
Feature Request: Option That Adds a Primary Key Field to the Edit and Create Forms

### ISSUE THREAD

**Issue by JackStouffer** [flask-admin/flask-admin#749]
I have Flask Admin set up to edit over 20 different tables. All of these tables are mostly the same but with slight differences, and all of them have strings for primary keys. I am currently using a parent class that all of the individual custom ModelViews inherit from to cover common functionality, like adding in the primary key into the form_extra_fields parameter so the users can change it if they need to. 

However, all of the users of my set up have complained because this puts the primary key at the bottom of the form and it is confusing to them. To put the pk at the top, I have tried to add it in the form_columns parameter, but including that overrides all of the other columns and custom behavior that I have added in form_extra_fields.

It would be nice to simply have a 

```
form_edit_pk = True
```

option on ModelView so it could be set in my parent class to add a pk field at the top of all the forms.

**Comment by mensurm** [comment]
I agree completely. Definitely would be a useful feature.

**Comment by threemonks** [comment]
I also complete agree on this feature request. I won't be able to use it without this feature because it means I almost have to implement these workarounds for every model in the application.

**Comment by petrus-jvrensburg** [comment]
Workaround: add the primary key field to the list of form_columns, e.g.
`form_columns = ['id', 'title', 'description']`, and use the flag `column_display_pk = True` to have the values show up in the list view.
