### ISSUE TITLE
form_ajax_refs to fetch from non-reference-field

### ISSUE THREAD

**Issue by cybertoast** [flask-admin/flask-admin#762]
I'm trying to get a list of existing values for a field as an ajax-requested list of possible values for a non-ReferenceField.

Here's a pseudocode example of what I want to do:

```
class MyModel(Document):
    tags = ListField(StringField())

class MyModelAdmin(FlaskView):
    form_overrides = {
        'tags': Select2TagsField
    }
    form_ajax_refs = {
        'tags': QueryAjaxModelLoader('tags', MyModel, fields=['tags'], page_size=10)
    }
```

For some reason this does not trigger the ajax search at all - meaning there is no ajax call sent for the tags field when I start typing into the field.

Am I approaching this wrong? Seems like I can't tie any QueryAjaxModelLoader into a non-ReferenceField field. Is there a suggest way to deal with this?

**Comment by petrus-jvrensburg** [comment]
Closing this now, but please re-open if it's still a problem.
