### ISSUE TITLE
Upload multiple images in one field

### ISSUE THREAD

**Issue by Trif4** [flask-admin/flask-admin#770]
I'm pretty new to Python, so sorry if this is something obvious, but how would I go about extending the image upload functionality to allow for multiple images in one field? I know it's accomplished in HTML just by adding multiple to the input, but I'm not sure how to properly do it with Flask-Admin.

(noob approach below)
So far I've succeeded in adding an inline image upload model to my form. I tried the following just to get a starting point to work from:

```python
class MultiImageUploadInput(ImageUploadInput):
    empty_template = ('<input %(file)s multiple>')

class MultiImageUploadField(ImageUploadField):
    widget = MultiImageUploadInput
```

Using this in my form however results in a TypeError (object() takes no parameters). Am I supposed to be doing something completely different?

**Comment by t4ec** [comment]
Hi, I have the same question, has anyone handled this case properly? Is there a way to do it without overriding whole field class?

**Comment by kharazi** [comment]
+1

**Comment by MikeChav** [comment]
@Trif4  were you able to do it?

**Comment by xqliu** [comment]
I have implemented a multiple image upload Field in the project betterlife/psi
Please see the corresponding wiki page and check the code for detail.
Thanks a multiple image upload field with a client side preview support.
Also currently I am using a online image storage service to store to image.
But it will not be difficult to change t to local file system storage.
Thanks.

via CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.12.61&pv=10.0&source=email_footer_2]
On 周三, 8月 3, 2016 at 5:02 下午, MikeChav <notifications@github.com> wrote:
@Trif4 [https://github.com/Trif4] were you able to do it?
