### ISSUE TITLE
Handle timezone-aware columns

### ISSUE THREAD

**Issue by jmagnusson** [flask-admin/flask-admin#772]
I get this exception when I try to update any object in Flask-Admin where one column is timezone-aware:

> TypeError: can't compare offset-naive and offset-aware datetimes

Full traceback here: https://gist.github.com/anonymous/31a48affeaa586fa8997

**Comment by MateuszG** [comment]
+1

**Comment by mrjoes** [comment]
That's good to have but I'm not sure what's best way to make it happen. 

All form management is done by WTForms and, as fair as I know, WTForms works with naive Date/DateTime objects. It is possible to create custom DateTimeField that will produce timezone-aware dates and make Flask-Admin use it instead of vanilla DateTimeField.

But I'm not sure how to make it part of Flask-Admin - field should configurable enough to support different timezones for different admin views.

**Comment by aldarund** [comment]
+1. Im using postgresql + sqlalchemy. If column in postgres defined as timestamp with timezone i get this error. But only on edit. On create it works fine. And no matter if i set in my model DateTime(timezone=False) or DateTime(timezone=True). It still doesnt work with the error in first message. But only when edit, so i guess edit just should act same as create. Basically right now it makes impossible to use flask-admin with timestamp with timezone fields.

**Comment by pawl** [comment]
Assuming the user is in the same timezone as the server seems like a bad idea. That's what it's doing by default when it creates the new record.

I think if we're going to solve this the right way, we need to add better timezone support to flask-admin.

This might require:
1. Adding an option that tells flask-admin to start storing datetimes in the database as UTC.
2. Configuring the datetime picker to set form values as UTC and display as the user's local timezone.
3. Changing the list view to display datetimes in the user's local timezone using moment.js.
4. If DateTime(timezone=True), wtforms will need to process the datetime field value as a timezone-aware UTC datetime.

**Comment by pawl** [comment]
I made some progress on adding timezone support here (it's still a work in progress): https://github.com/flask-admin/flask-admin/compare/master...pawl:issue_772?expand=1

Here's my approach so far:
* If timezone=true on a datetime or time SQLA column, it will use a different WTForms field type.
* The new WTForms field uses a new WTForms widget with an extra hidden input. That hidden input stores the UTC datetime that gets submitted for processing. The non-hidden text input that gets styled doesn't have a name attribute, so the non-UTC datetime value in that input don't get processed.

The idea is to allow displaying timezone-aware datetimes in the user's local time. But... now I'm stuck trying to find a way to do this that doesn't look hacky (currently it loads one value, then replaces it after the page finished loading).

I may end up taking a different approach and either display timezone aware datetimes as UTC or display datetimes with timezone offsets + processing that format. I'm also having 2nd thoughts on adding timezone support to time or date columns. Without both the date and time, there can be ambiguity when it comes to daylight savings time.

**Comment by hmanicka** [comment]
+1. I'm facing the same issue as what aldarund has mentioned above in November.

**Comment by stdexcept** [comment]
This has been a long time pain for us. It doesn't make sense to use naive datetime's anywhere outside of the scope of a single function.

**Comment by jrcamp** [comment]
This is my workaround so far. It prevents using of the timepicker as bootstrap-datepicker doesn't seem to understand anything about timezones. With some minor tweaks to it I think there could be a half-usable solution here. But at least this allows the form to function.

Note: this requires you have `python-dateutil` installed.

```python
from wtforms.ext.dateutil.fields import DateTimeField

class PlainDateTimeField(DateTimeField):
    pass

form_overrides = {
    'created_at': PlainDateTimeField
}

form_args = {
    'created_at': dict(display_format='%Y-%m-%d %H:%M:%S%Z')
}
```

Looks like this:

![Image](https://s3.amazonaws.com/f.cl.ly/items/002R3U12163c3L2k0b1x/Image%202016-03-15%20at%209.23.52%20PM.png?v=65e32108)

**Comment by hmanicka** [comment]
Please refer to the gist on how I have fixed this issue. It takes care of the error in the edit form and saves the timestamp in UTC.
https://gist.github.com/hmanicka/82834f2e0df016947730dbaf19d25c28

**Comment by joshua-s** [comment]
Can we please revisit this? It is a major pain point and the solution in the last message does not work.
