### ISSUE TITLE
`SynonymProperty` and `hybrid_property` aren't displayed in the model form

### ISSUE THREAD

**Issue by dmedvinsky** [flask-admin/flask-admin#78]
I used to use `db.synonym` from sqlalchemy in my model with Flask-Admin 1.0.1. Everything worked fine.

Recently I tried it with latest master and synonyms aren't rendered in the model form anymore as default `converter` kind of ignores them now.

I also tried using `hybrid_property` as it is superset of `synonym`. They aren't rendered in the model form at all as they aren't listed in the `mapper.iterate_properties`.

Any ideas? Because I'm out of them right now after debugging this (new for me stuff) for a couple of hours.

**Comment by paablux** [comment]
Can this be displayed when using a inline_model?
