### ISSUE TITLE
"Already exists" on edit

### ISSUE THREAD

**Issue by XenGi** [flask-admin/flask-admin#782]
I use Flask-Admin 1.0.9, when I try to edit a user I get the message "Already exists" on the email field which is marked unique in my model definition. When I remove uniqueness it works.

I know that this is because Flask-Admin tries to create a User with no email and then edits it or something like that internally. Is there a fix for this? Because I would like to rely on my database for uniqueness and not on my code.

Flask-Admin should do an UPDATE query with the fields from the form but seems to do something else.

**Comment by mrjoes** [comment]
Can you create small gist to reproduce the issue?

Yes, there's custom `unique` validator in Flask-Admin and check is here: https://github.com/mrjoes/flask-admin/blob/master/flask_admin/contrib/sqla/validators.py#L40

It ignores duplicate value of it is same model.

**Comment by italomaia** [comment]
I had this problem too; to fix it, I had to overwrite the form_base_class; wtforms-alchemy did the trick. On the other hand, a few options from ModelView stopped working (reported here #946).

**Comment by pawl** [comment]
It's an issue caused by using flask_wtf's Form as flask-admin's base form. If you're using it just for csrf validation, I'd recommend using flask-admin's SecureForm: https://flask-admin.readthedocs.org/en/latest/advanced/#enabling-csrf-protection

**Comment by clarete** [comment]
My bad, for anyone that ends up here, the problem I had wasn't related to flask-admin or wtforms. My database instance didn't have a proper `__eq__` working. (for reference, `Flask-User` transforms the `get_id()` of the user in a token generation function that was adding a random padding to it :/
