### ISSUE TITLE
'Create' view of join table fails to render if column value representing joined table is None

### ISSUE THREAD

**Issue by cubisttriangle** [flask-admin/flask-admin#785]
Error occurs when clicking on the 'Create' button for a join table. The reason this fails is obviously due to the TypeError (show below), but the root of the problem is that the column value representing the joined table is None. Consider the following database...

Contact|
---------|
ContactID|
Name|
Organization|

ContactType|
---------------|
ContactTypeID|
Name|

DataSet|
----------|
DataSetID|
Name|
</span>

DataSetContactJct|
-----------------------|
DataSetID|
ContactID|
ContactTypeID|

When displaying the 'create' view for a DataSetContactJct row, flask-admin intelligently makes the following default substitutions...
- DataSetContactJct.DataSetID -> DataSet.Name
- DataSetContactJct.ContactID -> Contact.Name
- DataSetContactJCT.ContacTypeID -> ContactType.Name

This situation is ideal when the substituted values cannot be NULL (None). However, a Contact might be defined by Contact.Organization, rather than by Contact.Name.

In such a case, 

- Loading the 'create' view using the following data will work:
  `<Contact(ContactID=1, Name='Bob', Organization=None)>`

- Loading the 'create' view using the following data will fail:
  `<Contact(ContactID=1, Name=None, Organization='NASA')>`

Finally, a Contact row is uniquely identified by the combination of Contact.Name and Contact.Organization, so __is there a good way to specify what joined table value[s] is/are used in join tables?__

Trace...

    (1) File "/usr/local/lib/python2.7/dist-packages/flask_admin/form/widgets.py", line 25, in __call__
        return super(Select2Widget, self).__call__(field, **kwargs)

    (2) File "/usr/local/lib/python2.7/dist-packages/wtforms/widgets/core.py", line 281, in __call__
        html.append(self.render_option(val, label, selected))

    (3) File "/usr/local/lib/python2.7/dist-packages/wtforms/widgets/core.py", line 299, in render_option
        return HTMLString('<option %s>%s</option>' % (html_params(**options), escape(text_type(label), quote=False)))

Error...

    TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by iurisilvio** [comment]
I had the same issue.

:+1:

**Comment by mrjoes** [comment]
Probably a little late, but this error happens if you're returning None from `__unicode__` or `__str__` functions.

For example, `str(None)` won't crash - it'll return 'None'.

But if you have code like this:
```python
class MyModel(object):
  def __unicode__(self):
    return None

print unicode(MyModel())
```
