### ISSUE TITLE
flask-admin 1.0.9 filter conflict with babel

### ISSUE THREAD

**Issue by shnode** [flask-admin/flask-admin#787]
Flask-Admin 1.0.9 filters still conflict with babel, which shows me a same Error as #692 :

    TypeError: key lu'\u521b\u5efa\u65f6\u95f4' is not a string

current language is Chinese `zh_Hans_CN`

**Comment by mrjoes** [comment]
What is your python version?

**Comment by shnode** [comment]
They are Python 2.7.8 and Python 2.7.6

**Comment by mrjoes** [comment]
This was fixed in current master.
