### ISSUE TITLE
Geocoding feature

### ISSUE THREAD

**Issue by ilhacker** [flask-admin/flask-admin#794]
I'm developing a website with geocoding lookup feature in flask-admin. If anyone finds it useful I'll be glad to push this feature in repo when it is done. But I'm having some issues. In model I use two fields:
    address = db.Column(db.String(255))
    point = db.Column(Geometry('POINT'))

What i can't figure out is how to pass an html attrubute in widget for point field for javascript use. I see it that way: javascript for rendering leaflet map will search for an html attribute in point field (e.g. data-lookup-from="address") and than I can generate a button "Lookup" and insert it after "#address" field. Also then I'll be able to access address value and bind an action for geocoding.

![capture](https://cloud.githubusercontent.com/assets/10095112/6316359/9746ab76-b9d8-11e4-888d-fe476c97c26e.PNG)

**Comment by ilhacker** [comment]
Managed to find a solution. Now I have a working geocoding feature through mapbox api. 
Configuration is made in model view.
Example:
``` python
imports...

class MyModel(db.Model):
    my_address = db.Column(db.String(255))
    my_point = db.Column(Geometry('POINT'))

from flask_admin.contrib.geoa import ModelView as GeoModelView

class MyModelView(GeoModelView):
    form_args = dict(my_point=dict(geocoding='my_address'))

    def __init__(self, session, **kwargs):
...
```
The result is on the picture in the first post. After clicking the Lookup button an ajax request to mapbox api is made. If address is found a marker will appear on the map.

**Comment by jmagnusson** [comment]
Sorry that I'm so late to the party, but that would be an awesome addition @ilhacker.

Now if we could just find a way to force the geocoding request to rely on the concatenation of a specified set of admin fields, in a certain order... Including fields in related models. I'll try to find some time to work on this in the coming weeks.

**Comment by mnlgn** [comment]
@ilhacker How about long/lat instead of an address? There is no way in flask-admin yet, to enter exact data this way :crying_cat_face:

**Comment by dkerkow** [comment]
PR #888 added a similar function half a year ago, but as a search box inside the leaflet map. Looks like there is a bug in there though, could not get it to work. 

The solution outlined by @ilhacker looks cleaner to me, would love to see that happen. Or is there already a way to use it somehow?

**Comment by dkerkow** [comment]
@jmagnusson I think the concatenation order should not be a problem, a geocoder is optimized to handle adresses in a variety of formats and weird user inputs.

Additionally, I would propose [Nominatim](https://wiki.openstreetmap.org/wiki/Nominatim) as an option for a geocoder. It is supported by [geopy](https://geopy.readthedocs.org/en/1.11.0/#geopy.geocoders.Nominatim).

**Comment by petrus-jvrensburg** [comment]
Closing this now, but please re-open if it's still relevant.
