### ISSUE TITLE
ReferenceField default value in edit form

### ISSUE THREAD

**Issue by andrewdiamond** [flask-admin/flask-admin#817]
When editing model with ReferenceField, the default value of the listbox do not corresponds to the model value. It is just the first in options list.

model: 
Class MyModel(Document, ModelMixin):
    message = StringField()

Class ModelMixin(object)
   area = ReferenceField('Area", required=True)

**Comment by mrjoes** [comment]
Form generation logic is offloaded to flask-mongoengine and model is passed as is.

Can you try to recreate issue with this https://flask-mongoengine.readthedocs.org/en/latest/#mongoengine-and-wtforms?
