### ISSUE TITLE
Empty results when searching and NULL relation

### ISSUE THREAD

**Issue by msempere** [flask-admin/flask-admin#834]
I'm facing the same problem as this unsolved problem in stackoverflow:
http://stackoverflow.com/questions/29331403/searching-with-flask-admin-returns-empty-results-when-a-searchable-column-is-nul

When a relation is NULL and is part of the searchable elements, it returns empty every time although the rest of parameters are correct.

**Comment by msempere** [comment]
Any idea about this issue?

**Comment by mrjoes** [comment]
Seems like Flask-Admin is using `INNER JOIN` somewhere, when building query. I will try to troubleshoot.

**Comment by msempere** [comment]
@mrjoes yes, that makes sense. Is there any plan for fixing it?

**Comment by msempere** [comment]
@mrjoes Could it be replace with a LEFT JOIN?

**Comment by pawl** [comment]
These issues might be related?: https://github.com/flask-admin/flask-admin/issues/547

It would really help if there was a Gist that reproduces the issue.

**Comment by msempere** [comment]
@pawl  #547 talks about problems with inputs different than strings.

**Comment by pawl** [comment]
@msempere I tried reproducing this issue with this gist, but couldn't reproduce it: https://gist.github.com/pawl/96afa9e1edbbe6b7e021
