### ISSUE TITLE
Geo module doesn't display maps due to mapbox API upgrade

### ISSUE THREAD

**Issue by nitishr** [flask-admin/flask-admin#842]
The geo module doesn't work with mapbox v4 API as api requests require mapbox access token. The v3 API currently used by flask-admin seems to be no longer supported (returns 401 Unauthorized status).

**Comment by nitishr** [comment]
PR #793 seems to fix this issue, but has been closed without any comment. I could submit another PR if I can understand the issue with PR #793.

**Comment by mrjoes** [comment]
Yes, go ahead with the pull request.

**Comment by nitishr** [comment]
In order to submit another PR, I'll need to understand what's missing from/wrong with PR #793? If there was an issue with it, I'd wanna avoid that. If there wasn't, we should merge it and not need another PR. Please let me know.

**Comment by abkfenris** [comment]
I'm guessing that @ilhacker closed #793 because the changes for geocoding a field got mingled in with the changes for MAPBOX_ACCESS_TOKEN.

**Comment by dhelma** [comment]
I was also wondering if it might be nice to add a config option to support openstreetmap. It works out of the box without any API tokens and the tileLayer code just needs to be changed to http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png

**Comment by mrjoes** [comment]
Pull requests are welcome, but mapbox v2 integration was merged in.
