### ISSUE TITLE
allow_empty forced in all fields return error

### ISSUE THREAD

**Issue by hachreak** [flask-admin/flask-admin#844]
Hi,
I'm trying to use `wtforms_components.SelectMultipleField` in my form to replace deprecated `wtforms.ext.sqlalchemy.fields`.

[The original code](https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/indexer/admin.py#L74).
Resume of my changes in the code:

```python
class IdxINDEXAdmin(ModelView):
   .....
  form_overrides = dict(
    .....
    fields=SelectMultipleField,
    .....
  )
  form_args = dict(
    .....
    fields=dict(
      label=_("Index fields"),
      choices=[]
    )
    .....
  )
```

But I receive the error: 
`TypeError: __init__() got an unexpected keyword argument 'allow_blank'`
Similar to https://github.com/mrjoes/flask-admin/issues/387

Debugging the code I found that `SelectMultipleField` extends `wtforms_components.fields.select.SelectField` that it extends `wtforms.fields.core.SelectField`, that it extends `wtforms.fields.core.SelectFieldBase`, that it extends `wtforms.fields.core.Field`.

And, in Field is the problem: it doesn't support `allow_blank` parameter.

So, we have 2 possibility:
 1. remove the hard-coded `allow_blank` in flask-admin.
 2. ask to modify field to support all possible arguments.
 3. other solutions? :)

Which is the best solution? :)

**Comment by mrjoes** [comment]
Just use `form_extra_fields` and override field completely.
