### ISSUE TITLE
SQLA: Multiple relationships to another model with search

### ISSUE THREAD

**Issue by jmagnusson** [flask-admin/flask-admin#846]
If there's more than one relationship to another model then (I believe) there's no way to add them to search.

```python
class A(Base):
    __tablename__ = 'a'
    id = sa.Column(sa.Integer, primary_key=True)
    name = sa.Column(sa.Text)


class B(Base):
    __tablename__ = 'b'
    a1_id = sa.Column(sa.Integer, sa.ForeignKey(A.id))
    a1 = orm.relationship(A.id, foreign_keys=[a1_id])
    a2_id = sa.Column(sa.Integer, sa.ForeignKey(A.id))
    a2 = orm.relationship(A.id, foreign_keys=[a2_id])

...

class BModelView(ModelView):
    ...
    column_searchable_list = (
        B.a1.name,
    )
# AttributeError: Neither 'InstrumentedAttribute' object nor 'Comparator' object associated with B.a1 has an attribute 'name'

class BModelView(ModelView):
    ...
    column_searchable_list = (
        B.a1,  # (or the string "a1")
    )
# Exception: Invalid field B.a1: does not contains any columns.


class BModelView(ModelView):
    ...
    column_searchable_list = (
       A.name,
    )
# sqlalchemy.exc.InvalidRequestError: Could not find a FROM clause to join from.  Tried joining to a, but got: Can't determine join between 'b' and 'a'; tables have more than one foreign key constraint relationship between them. Please specify the 'onclause' of this join explicitly.
```

How can we add support for this? Would be nice with an API like this:

```python
class BModelView(ModelView):
    ...
    column_searchable_list = (
       # (local_relationship, foreign_attribute)
       (B.a1, A.name),
    )
```

**Comment by mrjoes** [comment]
Try 'B.a1.name' as a string.

**Comment by jmagnusson** [comment]
Nope. Then I got a fourth error:

```
sqlalchemy.exc.AmbiguousForeignKeysError: Could not determine join condition between parent/child tables on relationship B.a1 - there are multiple foreign key paths linking the tables.  Specify the 'foreign_keys' argument, providing a list of those columns which should be counted as containing a foreign key reference to the parent table.
```

**Comment by mrjoes** [comment]
OK, this one will require a bit of work.

**Comment by jmagnusson** [comment]
Hmm maybe (maybe!) I could give it a try. Thankful for any hints where to start.

**Comment by mrjoes** [comment]
https://github.com/flask-admin/flask-admin/pull/808 - this is the idea of something that might fix it, but I didn't have time to finish reviewing it and pull request seems a bit messy.

**Comment by jmagnusson** [comment]
Posted a gist in #808 that shows the problem. And that #808 doesn't fix the problem entirely.

**Comment by mrjoes** [comment]
I refactored everything and now search, filters and sorting are smart enough to follow explicit JOIN path that was provided to the Flask-Admin.

So, if you use 'model1.model2.model3.something' as a filter, it'll explicitly follow this path.

**Comment by jmagnusson** [comment]
This works great @mrjoes. Thanks, man!

Any chance for a new release?

**Comment by jmagnusson** [comment]
This closes #808 btw.

**Comment by mrjoes** [comment]
I want to fix few more critical issues. ETA - this weekend/next week.

**Comment by jmagnusson** [comment]
Sounds great. Keep up the good work! Is there any place one can give you a donation for your efforts?

**Comment by jmagnusson** [comment]
Just tell me if you need help with some of the critical issues. I might actually have some spare time this weekend.

**Comment by bepetersn** [comment]
I'm wondering if you're seeing this work for filters. I get this error when trying to filter across multiple relationships:   

File "/home/brian/.virtualenvs/my-project/src/flask-admin/flask_admin/contrib/sqla/tools.py", line 198, in is_hybrid_property
    attr = getattr(last_model, names[i])
AttributeError: 'Mapper' object has no attribute 'location'

I can open a new issue also if you want.

**Comment by khialb32** [comment]
this multiple mapping is a problem since 2018 , any updates on sqlalchemy-flask fixed this yet ?

**Comment by NickNaskida** [comment]
> ```
> File "/home/brian/.virtualenvs/my-project/src/flask-admin/flask_admin/contrib/sqla/tools.py", line 198, in is_hybrid_property
>     attr = getattr(last_model, names[i])
> AttributeError: 'Mapper' object has no attribute 'location'
> ```

Have this problem now, seems it wasn't fixed since then 😕
