### ISSUE TITLE
Internal Server Error when doing nearly anything

### ISSUE THREAD

**Issue by SteveAtBrickSimple** [flask-admin/flask-admin#848]
I apologize if this is too vague, but I'm getting 500 responses from most pages loaded using Flask Admin v1.1.0, using Flask v0.10.1 and Flask-sqlalchemy 2.0.

I don't know what's causing this (maybe there's something being sent in my headers?), but I get the same issues when using the official examples [here](http://examples.flask-admin.org/).  They can be seen by trying to create any new models, or by going to, say, [here](http://examples.flask-admin.org/simple/admin/myadminview/), which is just a simple test view from the example site.

**Comment by petrus-jvrensburg** [comment]
@SteveAtBrickSimple Just updated the live examples to refresh themselves from https://github.com/flask-admin/flask-admin, so they're working again.

Have you tried `app.run(debug=True)` on your Flask app, so you can get more feedback on what's going on?

**Comment by SteveAtBrickSimple** [comment]
Hi @petrus-jvrensburg,

Yes, I did, and I've solved the issue on my end.  I was going to post an update.  It looks like I was doing something silly.  Normally I assume it's my fault off the bat, but since the examples were broken I wondered if something else was going on.

Thanks for the quick reply.

**Comment by petrus-jvrensburg** [comment]
no problem ;)
