### ISSUE TITLE
Filename download with FileField and mongoengine (maybe others)

### ISSUE THREAD

**Issue by bloer** [flask-admin/flask-admin#856]
Let's say I've defined the following model with MongoEngine:

``` python
def Experiment(Document):
    date = DateTimeField()
    description = StringField()
    config = FileField()
    results = FileField()
```

If my user adds an entry with config="default_settings.cfg" and results="weird_anomaly.dat", these names show up fine on the list view page, but, when you click to download, you get a popup that asks if you want to download "<blank>, which is of type BIN file". If you say yes, it gives it a semi-random name like 82jss76asd.bin, which obviously makes it hard to associate back to the original. 

I know that part of the problem is that the content-type is which is a whole different bag of worms.  However, getting the original filename to display in the dialog prompt is pretty trivial, just add 

``` python
'Content-Disposition': "inline; filename=%s"%data.filename
```

to the ModelView.api_file_view method. 

I can't see any obious drawback to adding this header, though that doesn't mean there isn't one

**Comment by petrus-jvrensburg** [comment]
Closing this, but please re-open if it's still a problem.
