### ISSUE TITLE
Delete record cause a CSRF missing problem.

### ISSUE THREAD

**Issue by XiaokunHou** [flask-admin/flask-admin#858]
I enabled CSRF checking, and a ModelView is created, when try to delete one record, there is the error,

Bad Request
CSRF token missing or incorrect
.
How to solve this problem.

**Comment by pawl** [comment]
Are you overriding the template with the token? The overridden template may need to be updated.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          From: XiaokunHouSent: Saturday, April 25, 2015 9:33 AMTo: flask-admin/flask-adminReply To: flask-admin/flask-adminSubject: [flask-admin] Delete record cause a CSRF missing problem. (#858)I enabled CSRF checking, and a ModelView is created, when try to delete one record, there is the error,

Bad Request
CSRF token missing or incorrect
.

—Reply to this email directly or view it on GitHub.

**Comment by XiaokunHou** [comment]
I didn't use a customized view, just a based ModleView. Where should I add the token?

**Comment by mrjoes** [comment]
How did you enable CSRF protection?

Just in case, Flask-Admin tries to be smart about it - templates detect if form has CSRF field and render it.

Long story short - can you provide gist illustrating the issue?

**Comment by XiaokunHou** [comment]
First enable CSRT for app.
``` python
app=Flask(__name__,template_folder='templates')
babel= Babel(app)
app.config.from_object('config')
csrf=CsrfProtect(app)
bcrypt=Bcrypt(app)
db=SQLAlchemy(app)
from iInvest import trustProductView, articleView, assetManagementView, views
from iInvest.manage import views
···
Then here is the view,
``` python
class TrustProductManage(sqla.ModelView):
    column_list = ('name','reason','threshold')
    column_sortable_list = ('name','reason')
    form_args = dict(
                    reason=dict(validators=[validators.required()])
                )
    # def __init__(self, session, **kwargs):
    #     # You can pass name and other parameters if you want to
    #     super(MyView, self).__init__(User, session, **kwargs)
    def create_form(self):
        form = super(TrustProductManage,self).create_form()
        return form
    def is_accessible(self):
        return login.current_user.is_authenticated()    
    column_display_pk = True
```
Add this view.
``` python
# Create admin
admin = admin.Admin(app, 'iInvest:', index_view=MyAdminIndexView(), base_template='my_master.html')
# Add view
admin.add_view(TrustProductManage(TrustProduct, db.session, gettext('TrustProduct Management')))
```
Here is the detail.
https://github.com/XiaokunHou/FlaskProject/blob/master/iInvest/manage/views.py

One wierd thing is that only delete doesn't work well.

**Comment by csik** [comment]
Similar issue.  Alright for add and edit, delete throws csrf.

**Comment by rochacbruno** [comment]
I had the same issue one week ago, I thought the problem was my templates so I downgraded my flask-admin and it worked.

**Comment by mrjoes** [comment]
I can't reproduce it. Are you sure you're overriding flask-admin default form class to use wtforms base class?

If you enable wtforms CSRF you'll have to use wtforms base class: http://flask-admin.readthedocs.org/en/v1.0.9/api/mod_model/#flask.ext.admin.model.BaseModelView.form_base_class

```python
from flask_wtf import Form

class MyAdmin(BaseModelView):
    form_base_class = Form
```

Without this, `csrf_token` field won't be set and delete will fail. Here's how Flask-Admin is using it: https://github.com/flask-admin/flask-admin/blob/master/flask_admin/templates/bootstrap3/admin/model/list.html#L113

**Comment by jbub** [comment]
i am experiencing the same issue, after removing csrf:

    csrf = CsrfProtect(app)

... its working

**Comment by mrjoes** [comment]
Please update your base `BaseModelView` class to use `Form` class from `flask_wtf`.

**Comment by Ssawa** [comment]
I came across this issue myself a few days ago myself as well and it was very confusing because if you notice, the 'actions' form actually get's filled out with the CSRF token just fine on the same page. The problem I found was that the view's 'delete_form' wasn't being set with the necessary 'csrf_token' field for whatever reason, as can be seen in how it's invoked in the template here:
 https://github.com/flask-admin/flask-admin/blob/master/flask_admin/templates/bootstrap3/admin/model/list.html#L113

I ended up solving it by overriding the view's 'get_delete_form' and 'delete_form' methods and making sure that delete_form.csrf_token was set (Mind you, it must be set to an the actual HTML input string you want used in the form, as the template doesn't call a HiddenField instance as it does for 'id' and 'url')

Again, all of this seems rather odd as if you look at:
https://github.com/flask-admin/flask-admin/blob/master/flask_admin/templates/bootstrap3/admin/actions.html#L17
the CSRF token of the actions form gets set just fine by only invoking the "csrf_token" jinja2 macro (which in my case was actually just flask-wtf's generate_csrf() python function). In fact, you can alternatively also fix the problem by extending the list template and overriding the 'list_row_actions ' block to use the process shown in the 'actions' form.

**Comment by mrjoes** [comment]
@Ssawa Did you override base form class like I showed in this thread?

**Comment by drcongo** [comment]
For the record @mrjoes, I was having this issue too until I followed your instructions. My model view now looks like this:

```class MyModelView(ModelView):

    form_base_class = Form

    def is_accessible(self):
        if current_user.is_authenticated() \
            and current_user.has_role('Admin') \
                or current_user.has_role('Super'):
            return True

        return False```

...and the delete in list views works perfectly now. Thank you.

**Comment by Ssawa** [comment]
@mrjoes no I'm sorry I should have specified, the hack I worked out was before I came across your much simpler solution. I just thought I'd offer what I came across concerning where in the implementation the issue occurs and how the template seems to be trying to accomplish the same thing in two different ways.

**Comment by antoine-lizee** [comment]
I am sorry to re-open this, but I have exactly this issue in spite of following exactly what is on the [flask-admin doc](http://flask-admin.readthedocs.io/en/latest/advanced/#enabling-csrf-protection).

```
...
from flask_admin.form import SecureForm
...

class AdminModelView(ModelView):
    form_base_class = SecureForm
```

I have `WTForms==2.1`

**Comment by antoine-lizee** [comment]
I also confirm that directly using `flask_wtf` solved the issue. Why not make that the default in the doc?

**Comment by antoine-lizee** [comment]
Update - my bug seems to actually be related to #1346, where the CSRF tokens were failing on prod with several workers, but failed silently on actions different than delete (edit and create).

**Comment by seaders** [comment]
I'm coming here after being bugged by this... bug for a long, long time.  I have CSRF protection across my entire application, with `CSRFProtect`, so just using `SecureForm` didn't work for me, as the way it did its CSRF generation was completely different to the rest of the app.

However, if I use `FlaskForm` from `flask_wtf`, the CSRF problems go away, and I'm able to edit from the list page, via inline pieces, but full editing fails.

Anyway, the solution that works for me is to create my own SecureForm, which is kind of a mixin, and takes the "form" of flask-admin's SecureForm, but the "logic" of FlaskForm,
    
    from flask import session, current_app
    from flask_wtf.csrf import _FlaskFormCSRF
    from flask_admin.form import BaseForm
    from wtforms.meta import DefaultMeta
    from flask_admin.contrib.sqla import ModelView

    class CustomSecureForm(BaseForm):
        class Meta(DefaultMeta):
            csrf_class = _FlaskFormCSRF
            csrf_context = session
    
            @property
            def csrf_secret(self):
                return current_app.config.get('WTF_CSRF_SECRET_KEY',
                                              current_app.secret_key)
    
    class CustomView(ModelView):
        form_base_class = CustomSecureForm

Inheriting from that CustomView, for any of my further views solves *every* one of my CSRF problems with flask-admin.  *Finally*.
