### ISSUE TITLE
Localization does not work at all!

### ISSUE THREAD

**Issue by mapio** [flask-admin/flask-admin#869]
Following the documentation at http://flask-admin.readthedocs.org/en/latest/localization/ or running the example at https://github.com/flask-admin/flask-admin/tree/master/examples/babel one gets just the english language messages.

**Comment by pawl** [comment]
Sorry about that. This should fix the problem: https://github.com/flask-admin/flask-admin/pull/870

It was missing some .mo files and some of the folders were not named correctly.

Can you pull and try again?

**Comment by mapio** [comment]
Sorry for my rude wording in the bugrep… I was on a hurry; thank you for the prompt answer, but unfortunately the bug presists in e54a8bba1fc7081c517b51cce1bd56837e58a006 as you can see from the attached screenshot.
![screen shot 2015-05-04 at 16 39 41](https://cloud.githubusercontent.com/assets/612826/7455494/100f7466-f27d-11e4-9ada-a5d6aa39245b.png)

**Comment by pawl** [comment]
Did you make sure to "python setup.py install" again after you pulled? I tested a few of the translations and they were working.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Massimo SantiniSent: Monday, May 4, 2015 9:46 AMTo: flask-admin/flask-adminReply To: flask-admin/flask-adminCc: Paul BrownSubject: Re: [flask-admin] Localization does not work at all! (#869)Sorry for my rude wording in the bugrep… I was on a hurry; thank you for the prompt answer, but unfortunately the bug presists in e54a8bb as you can see from the attached screenshot.


—Reply to this email directly or view it on GitHub.

**Comment by mapio** [comment]
My fault! I was testing it in a temporary virtualenv where I happened to have a previous copy of flask-admin :( 

Sorry, it works now (and probably it worked even before)!

**Comment by mapio** [comment]
Maybe there is still some problem, see #1076.
