### ISSUE TITLE
Please update Read The Docs documentation

### ISSUE THREAD

**Issue by mapio** [flask-admin/flask-admin#872]
As reported here https://readthedocs.org/projects/flask-admin/ the project still pulls from https://github.com/mrjoes/flask-admin/ so that the updated doc (with updated link to this repo, instead of to the old one) has not yet been processed.

Could you please fix it?

**Comment by mrjoes** [comment]
Done, thank you.

**Comment by mapio** [comment]
I see that it has been rebuilt now, but the page still reports the wrong homepage…

![screen shot 2015-05-04 at 19 49 45](https://cloud.githubusercontent.com/assets/612826/7458710/e919e0ac-f296-11e4-9fc3-0229bab6510c.png)
