### ISSUE TITLE
FileUploadField leaves dirt data if file is not allowed due to a nonempty allowed_extensions

### ISSUE THREAD

**Issue by mapio** [flask-admin/flask-admin#874]
If you pass a nonempty `allowed_extensions` argument and try to upload a file with a not allowed extension you get the following, which I suppose is not the intended output.

![screen shot 2015-05-11 at 21 15 12](https://cloud.githubusercontent.com/assets/612826/7573981/25df4d22-f82a-11e4-9330-4d8b496cef61.png)

The gist https://gist.github.com/mapio/73362360fb118161b87e is a very minimal app that leads to that screenshot.

**Comment by pawl** [comment]
You need to use allowed_extensions in form_args like this:
```
    form_args = {
        'path': {
            'label': 'File',
            'base_path': file_path,
            'allow_overwrite': False,
            'allowed_extensions': ['jpg', 'gif', 'png']
        }
    }
```

Tested with this gist: https://gist.github.com/pawl/ae9149408be1919448e0
