### ISSUE TITLE
Babel example does not work as expected

### ISSUE THREAD

**Issue by nikitinsm** [flask-admin/flask-admin#876]
Going through tutorial here https://github.com/flask-admin/flask-admin/blob/master/examples/babel/README.rst, after server start no translation applies, changing language at index does not affect

Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2

**Comment by mrjoes** [comment]
Translations were moved to https://crowdin.com/project/flask-admin. You'll have to grab translations from there and there's shell script for that: https://github.com/flask-admin/flask-admin/blob/master/babel/crowdin_pull.sh

@pawl Do you know if we can get all translations without requiring API key?

**Comment by pawl** [comment]
@nikitinsm are you using the newest code cloned from this repository? Also, which string are you use for localization (like "fr")?

Any other code examples would help too.

Not sure about pulling without the api key, need to look into that. Shouldn't be necessary to fix this issue.

**Comment by nikitinsm** [comment]
Nothing special, I just follow the tutorial. 

```bash
git clone https://github.com/flask-admin/flask-admin.git
cd flask-admin
virtualenv env
source env/bin/activate
pip install -r 'examples/babel/requirements.txt'
python examples/babel/app.py
```

**Comment by pawl** [comment]
Installing requirements from `examples/babel/requirements.txt` will install Flask-Admin from here: https://pypi.python.org/pypi/Flask-Admin

It looks like translations are very broken in the 1.1.0 release, but they seem to work fine when I try this:
```
git clone https://github.com/flask-admin/flask-admin.git
cd flask-admin
virtualenv env
source env/bin/activate
pip install -r 'examples/babel/requirements.txt'
python setup.py install
python examples/babel/app.py
```

**Comment by nikitinsm** [comment]
Installing development version fixes problem, thanks!
