### ISSUE TITLE
Buttons on create view

### ISSUE THREAD

**Issue by petrus-jvrensburg** [flask-admin/flask-admin#884]
Should we default to having three buttons [Save, Save and continue editing, Cancel] on the default create model view?
Thanks @rochacbruno
https://github.com/flask-admin/flask-admin/pull/831#issuecomment-105062373

**Comment by mrjoes** [comment]
I'm for it. Seems like majority likes to have three buttons.

**Comment by rochacbruno** [comment]
:+1:

**Comment by petrus-jvrensburg** [comment]
As per https://github.com/flask-admin/flask-admin/pull/831#issuecomment-115265197

It looks like the concensus is for three buttons on both the 'add' and 'edit' views: 
`Save`, `Save and continue`, `Save and add`. 

Furthermore, in stead of having an explicit `cancel` button, we'll display the same tabs from the 'add' view on the 'edit' view.

**Comment by Kyusen** [comment]
Hello, I wonder how can I change the name of these buttons, the application for which I am now developing staff wish it had another name. I thank you.
