### ISSUE TITLE
AttributeError: 'module' object has no attribute 'add_view'

### ISSUE THREAD

**Issue by qasimalbaqali** [flask-admin/flask-admin#885]
Can't add a model view always getting the same error. Here is my code that I am running. I am using a Factory Pattern for my flask app. 

```
class UserView(ModelView):
    column_list = ('username', 'email')
```

```

if __name__ == '__main__':
    admin.add_view(sqla.ModelView(User.username, db.session))
    manager.run()
```

I tried using flask-superadmin and got that to work but I'd rather use a constant updated extension such as flask-admin but I am having a really hard time doing it. Any help is appreciated. Thank you.

**Comment by mrjoes** [comment]
Please follow tutorial here: http://flask-admin.readthedocs.org/en/v1.0.9/quickstart/#initialization

Your admin is `flask.ext.admin` module, but you need to create `Admin` class instance and add views to it.
