### ISSUE TITLE
Custom Filter with Backref

### ISSUE THREAD

**Issue by divs1210** [flask-admin/flask-admin#886]
```python
class FooAdminView(sqla.ModelView):
    column_filters = [
        FilterEqual(Foo.bar, 'Bar')
    ]
```

`OneToMany(Bar, Foo)`. So Bar can have many `Foo`s. `Foo` has a `.bar` (via backref), but I'm seeing the following error:
`AttributeError: Neither 'InstrumentedAttribute' object nor 'Comparator' object associated with Foo.bar has an attribute 'table'`

What do I do?

**Comment by mrjoes** [comment]
You can't filter on "model" - you have to filter on a property of a model. Try using `Bar.some_field` instead. If it is related model, Flask-Admin will figure out JOIN.
