### ISSUE TITLE
sqla.ModelView column with unique=True and FileUploadField cause issue

### ISSUE THREAD

**Issue by plaes** [flask-admin/flask-admin#890]
When column field is overriden using FileUploadFile causes issue when column has `unique=True` constraint (modified example based on `examples/forms/app.py`):

```
class File(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Unicode(64))
    path = db.Column(db.Unicode(128), unique=True) # The unique argument here causes the issue

class FileView(sqla.ModelView):
    form_overrides = {
        'path': form.FileUploadField
    }
```

```
sqlalchemy.exc.InterfaceError

InterfaceError: (sqlite3.InterfaceError) Error binding parameter 0 - probably unsupported type. [SQL: u'SELECT file.id AS file_id, file.name AS file_name, file.path AS file_path \nFROM file \nWHERE file.path = ?'] [parameters: (<FileStorage: u'out.dot' ('application/msword-template')>,)]
```
This also happens on Postgresql/psycopg2.

**Comment by mrjoes** [comment]
Ugh, I'm not sure it makes sense, to be honest.

1. Validation is happening on a file object
2. FileUploadFill would generate random name anyway, so chances that it won't be unique are minimal

I guess I can pass random file name as a value down to validators, but not sure it is best approach.

**Comment by plaes** [comment]
Yeah, it doesn't make sense, but I was converting existing model to use Flask-Admin and it took basically whole day to figure out what was actually broken. (I even suspected that Flask-WTF was somehow hijacking and then screwing up the form validation).

**Comment by mrjoes** [comment]
Same thing would happen if you use vanilla wtforms `FileField` - it is just fields `value` type is `FileStorage` and that's something that SQLAlchemy can't figure out.

**Comment by plaes** [comment]
OK, I did some checks and uncovered two more subtle bugs with FileUploadField:

1. Uploaded file overwrites file with existing name in destination directory. 
2. When form submit fails in first try (due to another required column being empty), rendered form displays attached file. But on second submit after filling the previously missing column, the file isn't uploaded.

**Comment by plaes** [comment]
This is what's breaking the FileUploadField when form validation fails.

Before:
```
<input id="path" name="path" type="file">
```
After:
```
<input name="path" readonly="readonly" type="text" value="&lt;FileStorage: u'file.name' ('application/x-desktop')&gt;">
<input type="checkbox" name="_path-delete">Delete</input></div>
<input id="path" name="path" type="file">
```

**Comment by jgonggrijp** [comment]
I walked into a problem that turned out to be an instance of this issue. See [this StackOverflow question](http://stackoverflow.com/questions/31287446/flask-adminsqlalchemy-image-upload-works-in-mysql-production-env-but-not-in-sql) and the accepted answer for a reduced testcase (linked from Gist) and a very detailed analysis of the problem.

**Comment by jgonggrijp** [comment]
Is the bug resolved? Or is this a "wontfix"?

**Comment by plaes** [comment]
@jgonggrijp I think I fixed most of the issues (see commits below), but I didn't add tests.
1161ade3158fe15b448bceb085903192ffac5cb9
fe640216404b73f8f1ff9ece5ecb2dd503920de0
1d83e2bf9fefad5695b1d858727679e5cde706d5

**Comment by mrjoes** [comment]
I'm cleaning up the issues and this one was fixed.

**Comment by jgonggrijp** [comment]
Great! Thanks both!
