### ISSUE TITLE
form_extra_fields on InlineBaseFormAdmin?

### ISSUE THREAD

**Issue by manuelbua** [flask-admin/flask-admin#892]
I'm trying to use the `form_extra_fields` that i see declared in the [InlineBaseFormAdmin base class](https://github.com/flask-admin/flask-admin/blob/14dec4f5396c094fce6c726d7d1b7e0afee62a83/flask_admin/model/form.py#L55), but it looks like this isn't being used? Using `postprocess_form` works fine, just wondering what the field is about then?

**Comment by pawl** [comment]
Looks like this was fixed here: https://github.com/flask-admin/flask-admin/commit/48d383339b91d7f4392b556844ddc802f23626e0
