### ISSUE TITLE
Decerotor for /admin/

### ISSUE THREAD

**Issue by qasimalbaqali** [flask-admin/flask-admin#893]
So let's say I have a decorator called ```@admin_required``` and instead of doing all of Flask-Login integration I just want to put the decorator on the /admin/ view, is that possible?

**Comment by mrjoes** [comment]
Sure, admin views are ordinary flask views. You can use decorators if you want to.

**Comment by qasimalbaqali** [comment]
@mrjoes May I know which file exactly should I navigate to so I could add the decorator on that has the /admin/ view on it?

**Comment by mrjoes** [comment]
You change base classes of Flask-Admin, like IndexView or base model views.

https://github.com/flask-admin/flask-admin/blob/master/flask_admin/base.py#L391

**Comment by qasimalbaqali** [comment]
@mrjoes Done, thank you!
