### ISSUE TITLE
WYSIWYG example fails with 'template_mode=bootstrap3'

### ISSUE THREAD

**Issue by plaes** [flask-admin/flask-admin#894]
Running WYSIWYG example with `template_mode=bootstrap3` results in non-functioning example. This is because the `class` property is specified twice for the textarea widget:
```
<textarea class="form-control" class="ckeditor" id="text" name="text"></textarea>
```

**Comment by mrjoes** [comment]
OK, proper way would be to override `class_` completely, as it is custom widget anyway and developer can figure out required class names.

I'm not sure it is good idea to expose `class_` as a object-level variable though as it is a bit hackish approach.

**Comment by plaes** [comment]
How about passing it around as `inputclass` or `widget_class`?

**Comment by pawl** [comment]
How about this solution?: https://github.com/pawl/flask-admin/blob/2918eee54cfc544618e945cc6592ca8cf2949788/examples/wysiwyg/app.py#L21

I just used what was in the WTForms docs for custom widgets here: http://wtforms.readthedocs.org/en/latest/widgets.html#custom-widgets

**Comment by plaes** [comment]
Official solution is excellent!

Any idea where to add docs (title: "Custom form widgets") for this? Under 'Usage tips' or 'Form rendering rules' ?

**Comment by petrus-jvrensburg** [comment]
@plaes Added an example for this during refactoring of the docs at #929 under 'Replacing individual form fields'.
