### ISSUE TITLE
Continuous pagination without expensive counting.

### ISSUE THREAD

**Issue by neglectedvalue** [flask-admin/flask-admin#897]
Is there any way to disable calculating a total number of objects with ModelView.get_count_query?

I have big tables with more than 10 millions records and when I apply filters and ordering it starts work really slow.
I don't need in the accurate number of objects and pages, continuous pagination would be sufficient.

As a workaround I could apply limit in ModelView.get_query but I think it is not the best solution.

**Comment by mrjoes** [comment]
Unfortunately, right now there's no good built-in way to do it. But it is good suggestion and I'll take a look.

While there's relatively hackish way to do it by overriding get_list (which call get_query, get_count_query), it is quite big to override easily and should be split into smaller chunks.

**Comment by neglectedvalue** [comment]
Great! Thanks! :+1:
