### ISSUE TITLE
Adding a icon to a category in a menu

### ISSUE THREAD

**Issue by jochenklein** [flask-admin/flask-admin#898]
If you have a category with some views (which are added with `admin.add_view`), you can use the parameters `menu_icon_type` and `menu_icon_value` to set a icon (finally displayed with `{{ menu_icon(item) }} ` in the menu).

Is there a possiblity to add a icon for the category too? Because in this case the category isn't a view.

**Comment by mrjoes** [comment]
Right now there's no way to, as icons are not displayed for category items. But you can add this functionality through custom mixin and custom template.

**Comment by jochenklein** [comment]
All right, thanks.

**Comment by jochenklein** [comment]
Is it possible to add this feature and if yes, how and where in the code would be the best solution?
