### ISSUE TITLE
DateTime picker not selecting current time

### ISSUE THREAD

**Issue by javierwilson** [flask-admin/flask-admin#899]
Whenever you create a new record, DateTime picker will pre-select the current date, however time will show: "0:00". I've tested this on version 1.1.0. You can also see it in the examples:
http://examples.flask-admin.org/sqla/simple/admin/post/new/?url=%2Fsqla%2Fsimple%2Fadmin%2Fpost%2F
![datetimepicker](https://cloud.githubusercontent.com/assets/596817/8145468/01db6b4e-11c6-11e5-80de-8530e2f3a1bf.png)

**Comment by pawl** [comment]
@javierwilson I submitted a pull request for this.

Would you mind pip installing from my branch and seeing if the fix is what you expected?:

```
pip install -e git+https://github.com/pawl/flask-admin.git@fix_datepicker100#egg=flask-admin
```

**Comment by javierwilson** [comment]
Yes, it fixes this issue. Thanks!
