### ISSUE TITLE
Issue with empty List of ReferenceField since 1.2.0

### ISSUE THREAD

**Issue by fredpro** [flask-admin/flask-admin#908]
Hello,

There is an issue (or is it a feature ?) with MongoEngine's ListField of ReferenceField. I cannot save my object in Flask-Admin (be it a new or edited object) when an attribute of ListField(ReferenceField()) type is empty. The save returns to the same page saying that the value is not correct.

Here is the sample attribute:

roles = db.ListField(db.ReferenceField(Role), default=[])

I reverted to v1.1.0 which is working fine. The problem appeared when I updated to v1.2.0

**Comment by mrjoes** [comment]
Apparently there were some changes in flask_mongoengine form generation logic, but adding `Optional` validator automatically helped the case.

**Comment by cfol103** [comment]
it doesn't look like this was completely fixed by commit faf440a because the 'validator' key can come in with an empty list as the value....making it skip adding the optional validator.

#1008 should fix that.
