### ISSUE TITLE
Foundation Template

### ISSUE THREAD

**Issue by ondoheer** [flask-admin/flask-admin#911]
I want to add a Zurb Foundation 5 template to the our projects, I wanted to know if I could add it to this project, and also, Should I add it to templates so it canbe chosen as the BS2 & BS3? or would I add it to contrib?

**Comment by mrjoes** [comment]
Create pull request with files under this directory: https://github.com/flask-admin/flask-admin/tree/master/flask_admin/templates

Copy all templates from one of the bootstrap folders and change them to use Foundation 5 markup. I think name of the directory should be `zurb5`.

When you initialize your `Admin` object, pass name of the directory:

```python
admin = admin.Admin(app, 'Demo', template_mode='zurb5')
```

I saw quite a few requests to support Foundation 5 from other users, so having official support would be great.

**Comment by ondoheer** [comment]
Ok, will do it following those instructions!

**Comment by ondoheer** [comment]
Done, I have sent the PR 5 mins ago.

**Comment by mrjoes** [comment]
I'll keep pull request open and close the ticket.
