### ISSUE TITLE
Variant SQLAlchemy object not recognized?

### ISSUE THREAD

**Issue by hachreak** [flask-admin/flask-admin#912]
See [Issue](https://github.com/inveniosoftware/invenio/issues/3311#issuecomment-115570021) for details.
I'm using this SQLAlchemy column field (instead of a Text field):

``` python
Text().with_variant(Text(length=2**32-2), 'mysql')
```

And, after I restarted the application, the text field disappears from the form.
Someone have the same problem? :)

**Comment by mrjoes** [comment]
I'm pretty sure that Flask-Admin never supported invariant columns. But I'll take a look, maybe there's easy fix.

**Comment by hachreak** [comment]
@mrjoes maybe Flask-Admin can use `column.impl` to recognize which kind of field it is?

**Comment by petrus-jvrensburg** [comment]
Closing this now. Please re-open if it's still a problem.
