### ISSUE TITLE
flask_admin.contrib.mongoengine and required integer fields with 1.2.0

### ISSUE THREAD

**Issue by rmoskal** [flask-admin/flask-admin#913]
I have a model with an integer field:

     stock_count = db.IntField(required=True, default=0)

I'm unable to set the value of the that field to 0 on the flask-admin  edit page. I can set it to -1, 10, or a million. But if I set it to 0 I always get a  "This field is required." validation error.

Is this the expected behavior?  It seems like a bug to me, though it's hard to believe such a bug exists.

**Comment by mrjoes** [comment]
Fixed, caused by the wtform `Required` validator which is using `bool(value)` and `0` returns `False`. Will use `InputRequired` now.

**Comment by rmoskal** [comment]
Thanks!  Guess I'll have to pull the latest into my requirements file.

**Comment by rmoskal** [comment]
Sorry I grabbed the latest with your fix:

            kwargs['validators'].append(validators.InputRequired())

Same issue.

**Comment by mrjoes** [comment]
Weird:
![image](https://cloud.githubusercontent.com/assets/179880/8385068/921900fc-1c13-11e5-999b-46169b3df8c2.png)
and
![image](https://cloud.githubusercontent.com/assets/179880/8385076/9ca6b74e-1c13-11e5-9c5d-894a028c953f.png)

Gist: https://gist.github.com/mrjoes/8a60db1ac7136d58f020

What's your WTForms version?

**Comment by rmoskal** [comment]
2.0.2

**Comment by mrjoes** [comment]
Tried with wtforms 2.0.2 and it still works.

Make sure you're really using version from git master branch. Just in case, I also bumped version number, it should be 1.2.1-dev.

Try my gist as well - navigate to http://localhost:5000/admin/model/new/ and see if it works.

**Comment by rmoskal** [comment]
All cool. I had an older version of flask_admin in my virtualenv along with
the new one. Strange. Anyway, all good. Sorry for the extra bother!  Thanks
for the useful library!
