### ISSUE TITLE
bootstrap3 edit view broken on smaller screens

### ISSUE THREAD

**Issue by cankerpie** [flask-admin/flask-admin#915]
This probably applies not only to the edit view, but our main gripe is with that.
https://github.com/flask-admin/flask-admin/blob/master/flask_admin/templates/bootstrap3/admin/lib.html#L104 (what worked for me was adding ```col-xs-5``` aside ```col-md-2``` and a bunch of CSS to preserve alignment, etc.)

**Comment by pawl** [comment]
Here's a screenshot of the edit view on a smaller screen: http://i.imgur.com/FeWfg2B.png

It looks fine to me. Can you show a screenshot of your issue?

**Comment by cankerpie** [comment]
Oh, this is very embarassing. I accidentally broke it all myself.
Sorry!
