### ISSUE TITLE
Cannot translate category names

### ISSUE THREAD

**Issue by sebleblanc** [flask-admin/flask-admin#922]
It seems that category names cannot be translated lazily, because the category collection uses the name of the category as a key to a dictionary. Since a lazy gettext string is not hashable, adding a category with a lazily-translated name will fail:

    from flask_babel import lazy_gettext as _
    class MyModelView:
        ...

    model_view = MyModelView(
        models.Model, db.session, name=_('MyModelView'), category=_('MyModelView'))

    draft_model_link = MenuLink(
        name=_('Draft models'), url='/path/to/model/?draft=1', category=_('MyModelView'))

    admin.add_view(model_view)
    admin.add_link(draft_model_link)

Traceback:

    Traceback (most recent call last):
      File "/code/scripts/manage.py", line 4, in <module>
        from myapp import app
     File "/code/myapp/__init__.py", line 56, in <module>
        import myapp.admin
      File "/code/myapp/admin.py", line 641, in <module>
        admin.add_view(MyModelView(models.Event, db.session, name=_('MyModelView'), category=_('MyModelView')))
      File "/code/venv/src/flask-admin/flask_admin/base.py", line 523, in add_view
        self._add_view_to_menu(view)
      File "/code/venv/src/flask-admin/flask_admin/base.py", line 558, in _add_view_to_menu
        self._add_menu_item(MenuView(view.name, view), view.category)
      File "/code/venv/src/flask-admin/flask_admin/base.py", line 545, in _add_menu_item
        category = self._menu_categories.get(target_category)
    TypeError: unhashable type: '_LazyString'

**Comment by rochacbruno** [comment]
You need lazy_gettext


```
from flask.ext.admin.babel import lazy_gettext as _l

..

category=_l('MyModelView')

```

**Comment by mrjoes** [comment]
Does not work with `lazy_gettext` - it is not hashable.

**Comment by rochacbruno** [comment]
It worked for me https://github.com/quokkaproject/quokka-cart/blob/master/admin.py#L133

**Comment by mrjoes** [comment]
Yeah, it works for `name`, but not for `category`. You use non-lazy version of the `gettext` for `category.

**Comment by sebleblanc** [comment]
@rochacbruno, we are talking about the category name.

**Comment by mrjoes** [comment]
This was corrected, use version from master.
