### ISSUE TITLE
Inline model creation fails when relationship has cascade="delete" set

### ISSUE THREAD

**Issue by aebrahim** [flask-admin/flask-admin#928]
This is the likely cause for #759 

This example script recreates the problem:
```python
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, relationship, scoped_session
from sqlalchemy import Column, Integer, String, ForeignKey

from flask import Flask
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView

engine = create_engine("sqlite:///data.db")
Base = declarative_base(bind=engine)
Session = scoped_session(sessionmaker(bind=engine))


class Basket(Base):
    __tablename__ = "baskets"

    id = Column(Integer, primary_key=True)
    recipient = Column(String(10))
    apples = relationship("Apple", cascade="delete")


class Apple(Base):
    __tablename__ = "apples"

    id = Column(Integer, primary_key=True)
    basket_id = Column(Integer, ForeignKey("baskets.id", onupdate="CASCADE",
                                           ondelete="CASCADE"), nullable=False)
    type = Column(String(10))
    basekets = relationship(Basket)


Base.metadata.create_all()


session = Session()


class BasketView(ModelView):
    inline_models = [Apple]

app = Flask(__name__)
app.config["SECRET_KEY"] = "12345"

admin = Admin(app, name="demo", template_mode="bootstrap3")
admin.add_view(BasketView(Basket, session))
admin.add_view(ModelView(Apple, session))

if __name__ == "__main__":
    app.run(host="0.0.0.0", debug=True)
```

Entering data into the form:
![image](https://cloud.githubusercontent.com/assets/1380168/8511789/ab19e846-22da-11e5-9c11-61629f5abf14.png)

However, after hitting "Save" they are not actually created.
![image](https://cloud.githubusercontent.com/assets/1380168/8511811/93715084-22db-11e5-9524-5fd8c376c1e5.png)

If I remove the cascade="delete" flag from the relationship, then this works fine.
![image](https://cloud.githubusercontent.com/assets/1380168/8511800/3405178e-22db-11e5-90bc-0fcaad5544f8.png)

**Comment by aebrahim** [comment]
Oh I forgot to mention that the``` flask_admin.__version__``` is ```'1.2.0'```

**Comment by mrjoes** [comment]
It is combination of SQLAlchemy auto-flush behaviour with cascade configuration.

Flask-Admin (or wtforms for that case) creates inline models before creating main model. SQLAlchemy does auto-flush, does INSERT without committing session and figures out that there's no parent and marks objects for deletion. After child models get their parent model set, it no longer matter - they're going to be deleted when `commit` will be called. 

I'll see what I can do, I know there's a way to tell SQLAlchemy that models should be deleted.
