### ISSUE TITLE
Where is the PDF version of the manual?

### ISSUE THREAD

**Issue by asarch** [flask-admin/flask-admin#931]

**Comment by asarch** [comment]
One way to get around this is to export it to the TeXinfo format and resize to 50% all the images to get the PDF version of the TeXinfo format

**Comment by mrjoes** [comment]
Apparently readthedocs.org compiles documentation to PDF and all last builds were successful. But for whatever reason it is not showing PDF link.

**Comment by petrus-jvrensburg** [comment]
Fixed in 01589c4c0fe5ad0a61202f333101580ec9772c17.
