### ISSUE TITLE
Flask admin with Nginx Reverse proxy

### ISSUE THREAD

**Issue by christopher-abastar** [flask-admin/flask-admin#936]
Hello,

I tried deploying flask admin with nginx reverse proxy. I was able to up the website but whenever I do a Create / Update, it stucks in the page and never redirects?  I see an HTTP 302 status code in nginx but somehow the page never get there?

Need help thanks

**Comment by SophiaAP** [comment]
@christopher-abastar, I am having the same issue here (on version 1.4.2). Did you ever figure this out? Would really appreciate any insight! Thank you!

**Comment by SophiaAP** [comment]
For anyone who finds themselves here, adding an X-Forwarded-Host header to my nginx.conf resolved the redirect issue for me:
```
proxy_set_header Host $http_host;
proxy_set_header X-Forwarded-Host $http_host;
```
See [Nginx redirects to port 8080 when accessing url without slash](https://serverfault.com/questions/351212/nginx-redirects-to-port-8080-when-accessing-url-without-slash)
