### ISSUE TITLE
admin.static is hard coded, doesn't update with endpoint change

### ISSUE THREAD

**Issue by wumb0** [flask-admin/flask-admin#943]
I'm trying to define my admin interface's index with another endpoint name besides admin (lets say adminpanel for the sake of this issue). 
```python
admin = Admin(app, "Admin Panel", subdomain="sub", index_view=views.ProtectedIndexView(endp="adminpanel"))
```
Where views.ProtectedIndexView is just an AdminIndexView with is_accessible() defined for access control and an overridden __init__ class to allow me to specify the endpoint I want as shown above:
```python
def __init__(self, endp):
    super(ProtectedIndexView, self).__init__(endpoint=endp)
```
When I print out all of the endpoints both adminpanel.static and adminpanel.index exist and are resolvable with url_for, but when I try to browse to the index page it throws an error saying that admin.static could not be found. This seems like it is due to flask_admin/templates/bootstrap3/admin/static.html where admin.static is hard coded in ({{ url_for('admin.static', *varargs, **kwargs) }}). I'm not sure something you can or will address, but let me know either way if there is a possible solution to this problem.

**Comment by ArthurPBressan** [comment]
I'm having this problem as well.

**Comment by mrjoes** [comment]
This was partially solved with `get_url` and static url functionality.

**Comment by lapseofreason** [comment]
> This was partially solved with `get_url` and static url functionality.

Could you provide more information what you mean by that? Overriding `get_url` like in #1342?

I also do not understand what use-case there is for changing the endpoint if the templates still require `admin.static`. Is that only intended for two instances of flask-admin where one is the `admin` endpoint and thus provides the static files?

I've run into this issue on two separate occasions:
1. Add flask-admin to existing application with existing `admin` endpoint (not flask-admin)
2. Two instances of flask-admin for single application (e.g. `admin1` and `admin2`) for different admins.

**Comment by marksteward** [comment]
This has been bugging me, as I basically want to namespace all admin pages under a particular endpoint and URL, and nested blueprints aren't a thing yet. Using the partial solution means passing a custom endpoint and url to every ModelView.

Instead, I'm doing this:

```
import flask_admin.base

_get_url = flask_admin.base.BaseView.get_url
_create_blueprint = flask_admin.base.BaseView.create_blueprint

def get_url(self, endpoint, **kwargs):
    if endpoint == 'admin.static':
        endpoint = '{}.static'.format(self.admin.endpoint_prefix)
    return _get_url(self, endpoint, **kwargs)

def create_blueprint(self, admin):
    if self.endpoint == admin.endpoint:
        self.endpoint = admin.endpoint_prefix
    else:
        self.url = self._get_view_url(admin, self.url)
        self.endpoint = '{}.{}'.format(admin.endpoint_prefix, self.endpoint)
    return _create_blueprint(self, admin)

flask_admin.base.BaseView.get_url = get_url
flask_admin.base.BaseView.create_blueprint = create_blueprint
flask_admin.base.AdminIndexView.get_url = get_url
flask_admin.base.AdminIndexView.create_blueprint = create_blueprint
```

and then setting endpoint_prefix on my Admin object. This results in the index page's endpoint being the endpoint_prefix, with the ModelViews nested under it. I still need to be careful with templates, but it basically does what I want.

Should I create a PR to add `endpoint_prefix` properly, or is there a better way to solve this?

(Also, it seems strange that the Admin object's endpoint depends on the index_view passed in and not vice-versa. Perhaps that's worth separating at the same time?)
