### ISSUE TITLE
ListField with flask-admin 1.2.0 and mongoengine cannot be empty

### ISSUE THREAD

**Issue by sladinji** [flask-admin/flask-admin#944]
I recently upgrade from flask-admin 1.1.0 to 1.2.0 and I can't submit form with empty value for a ListField anymore. I played with pdb and I found this in **flask_mongoengine/wtf/fields.py** :
```python
 78  	    def pre_validate(self, form):
 79  ->	        if not self.allow_blank or self.data is not None:
 80  	                if not self.data:
 81  	                    raise ValidationError(_(u'Not a valid choice'))
```
self.data type is an empty mongoengine.base.datastructures.BaseList so it always raises error...

**Comment by cfol103** [comment]
can verify that this is also happening to my flask-admin on 1.2.0.  the following pull request should fix it: https://github.com/flask-admin/flask-admin/pull/1008

**Comment by rochacbruno** [comment]
I am also having the same issue on 1.2.1-dev

**Comment by Fraggle** [comment]
I'm having the same issue on 1.4.
