### ISSUE TITLE
form_choices doesn't work

### ISSUE THREAD

**Issue by wumb0** [flask-admin/flask-admin#945]
```python    
can_post = [(x.id, x.nickname) for x in
                User.query.filter_by(role=USER_ROLES['admin'])]
    form_args = dict(
        author=dict(
            default=User.query.filter_by(role=USER_ROLES['admin']).first()
        ))
    form_choices = {'author': can_post}
```
Form choices are not updated. I validated that can_post is a list with only the admin users, yet all users still show on the dropdown. I also have another site with similar code that doesn't work either.

**Comment by pawl** [comment]
It's probably best to use the QuerySelectField for that, here are some docs about it: http://wtforms.readthedocs.org/en/latest/ext.html#id2

Here's an example of it used in a flask application: https://github.com/pawl/MakerManager2/blob/master/application/views/badge_request.py#L100

**Comment by pawl** [comment]
In flask-admin, you can override query_factory with form_args to change the query used to get select field choices:
```
def cars_with_test_desc():
    return Car.query.filter_by(desc="test")

class TyreAdmin(sqla.ModelView):
    column_display_pk = True
    can_view_details = True
    form_args = dict(
        car=dict(
            query_factory=cars_with_test_desc
        )
    )
    form_columns = ['car', 'tyre_id', 'desc']
```
https://github.com/flask-admin/flask-admin/blob/master/examples/sqla/app2.py

**Comment by jgeigerm** [comment]
That second one works nicely, thanks! Should I keep this open, since the argument does not do what it was designed to do?

**Comment by petrus-jvrensburg** [comment]
We should make the `query_factory` more prominent in the docs. It seems like a pretty common thing to do.

**Comment by mrjoes** [comment]
Originally Flask-Admin was using WTForms `QuerySelect`, but it was moved out later.

I think it is important to specify that all these arguments like `form_choices` are, basically, parameters to WTForm fields and for different fields they will be different. `QuerySelectField` is not the same as `SelectField`.

**Comment by nickretallack** [comment]
[The only place form_choices is ever used is in the contrib.sqla](https://github.com/flask-admin/flask-admin/blob/c0f904a50f43e893e3b8f7e321021eb9a3584d20/flask_admin/contrib/sqla/form.py#L243).  That means it won't do anything in peewee, mongodb, appengine, etc.

I was hoping to use this with App Engine, but unfortunately it seems [flask-admin does not pass any arguments to the form scaffolding for App Engine](https://github.com/flask-admin/flask-admin/blob/master/flask_admin/contrib/appengine/view.py#L35).

**Comment by mrjoes** [comment]
Pull requests are always welcome! App Engine support was contributed and none of core devs are actually using it.

**Comment by savraj** [comment]
Oops, was struggling with this as I'm using peewee and was wondering why form_choices doesn't work. Argh!
