### ISSUE TITLE
`form_columns` is not applied if `form_base_class` is used

### ISSUE THREAD

**Issue by italomaia** [flask-admin/flask-admin#946]
I just had to overwrite the form_base_class attribute from a ModelView of mine in order to avoid the problem where an "Already exists" message is show if the model has a unique field, as reported here #782. By doing so, the `form_columns` option, that controls which fields of the form should appear when the form is rendered does not do its job anymore. I believe it should still work, despite using a custom form class. 
I have yet to test it, but I believe there are other options that suffer from the same problem.

**Comment by petrus-jvrensburg** [comment]
Closing this now, but please re-open if it's still a problem.
