### ISSUE TITLE
Has anyone managed to get sentry running with flask-admin?

### ISSUE THREAD

**Issue by dpnova** [flask-admin/flask-admin#948]
I'm doing the regular flask sentry integration but it doesn't seem to report anything. Not surprising as I expect admin is doing some low level magic that may handle errors differently.

Thoughts?

**Comment by pawl** [comment]
Can give an example gist of how you're using it? I've used it successfully with a flask-admin application (that used the application factory pattern) and don't remember needing to do anything besides what's in the guide: http://raven.readthedocs.org/en/latest/integrations/flask.html

**Comment by dpnova** [comment]
Actually I found the problem, I didnt have the flask dependency that is required for signal handling installed.

Thanks!
