### ISSUE TITLE
Please do not auto-translate new strings

### ISSUE THREAD

**Issue by plaes** [flask-admin/flask-admin#955]
Could you please stop autotranslating new strings when they are added?

Falling back to english translation is usually better than autotranslated gibberish.

**Comment by pawl** [comment]
Will do. I didn't know it was that bad. Some of the auto-translated stuff also comes from other projects, so it's supposed to make some educated guesses.

**Comment by plaes** [comment]
Thanks!

With some languages the autotranslation just works. But there are unfortunately some (like Estonian - https://en.wikipedia.org/wiki/Estonian_grammar ), where it currently doesn't.
