### ISSUE TITLE
ImageUploadField validation does not allow leaving the file as is

### ISSUE THREAD

**Issue by denoted** [flask-admin/flask-admin#966]
I have a form where one of the fields is an ImageUploadField. If I edit an SQLA model using it, but leave the file alone (I'm editing other data), then the form and/or model doesn't validate because I haven't specified a new file.  I would like to just keep the file name the same as before.

This very well could be using ImageUploadField improperly, but after chasing my tail for a few hours, I figured I'd just ask.

If you give me a pointer on where this validation might be failing, I'll fix the issue in a pull request.

**Comment by denoted** [comment]
Here is a simplified version of what I'm doing.

```
class Parent(BaseModel):
    __tablename__='parent'
    id=Column(Integer(), primary_key=True, nullable=False, autoincrement=True)
    readable_name=Column(String(64), nullable=False, server_default='---')
    type=Column(String(32))

    __mapper_args__ = {
        'polymorphic_identity':'parent',
        'polymorphic_on':type
    }

class Child(Parent):
    __tablename__='child'
    id=Column(Integer(), ForeignKey('parent.id'), primary_key=True)
    image_url=Column(String(255), nullable=False)

    __mapper_args__ = {
        'polymorphic_identity':'child',
    }
```

and the view:

```
class ChildView(flask.ext.admin.contrib.sqla.ModelView):
    form_excluded_columns = ('type',) 
    form_overrides = dict(image_url=ImageUploadField)
    form_args = dict(
        image_url=dict(label='Image:', base_path='/tmp/mydir', allowed_extensions = ('jpg', 'jpeg', 'png'))
    )
```

**Comment by mrjoes** [comment]
What's your Flask-Admin version? This one was fixed some time ago.

**Comment by denoted** [comment]
Flask-Admin==1.2.0

**Comment by denoted** [comment]
I just realized that in the example app running at http://examples.flask-admin.org/forms/admin/, the path in:

```
class Image(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Unicode(64))
    path = db.Column(db.Unicode(128))

    def __unicode__(self):
        return self.name
```

is nullable, where in my case, image_url is not:

```
class Child(Parent):
    __tablename__='child'
    id=Column(Integer(), ForeignKey('parent.id'), primary_key=True)
    image_url=Column(String(255), nullable=False)

    __mapper_args__ = {
        'polymorphic_identity':'child',
    }
```

Getting rid ot the nullable=False allowed this to work as expected.
