### ISSUE TITLE
[Theme] Suggestion: Bootflat Admin

### ISSUE THREAD

**Issue by rochacbruno** [flask-admin/flask-admin#969]
I came across this https://github.com/silverbux/bootflat-admin

![https://raw.githubusercontent.com/silverbux/bootflat-admin/master/dist/img/screensho1.png](https://raw.githubusercontent.com/silverbux/bootflat-admin/master/dist/img/screensho1.png)

I think this would fit perfectly in Flask-Admin, maybe I will start porting the template, does anybody want to help on this?

**Comment by pawl** [comment]
Reminds me of some themes on https://bootswatch.com/

I don't think it's necessary to make this the default, but maybe you could improve the layout examples with it? https://github.com/flask-admin/flask-admin/tree/master/examples/layout_bootstrap3

**Comment by petrus-jvrensburg** [comment]
Yes, If you could make an example that runs with that, I'd love to put it up at http://examples.flask-admin.org/.

**Comment by mrjoes** [comment]
One thing though - need to check license. If it is not BSD, we can't include it to the main repo, but can reference it from layout example or docs.

**Comment by silverbux** [comment]
:+1:  ;)

**Comment by lj020326** [comment]
Hi - just curious - I would love to use a layout to possibly use for a flask-admin dashboard with d3.js - did an example ever get created with it?

**Comment by petrus-jvrensburg** [comment]
Bootswatch has been included. To select a theme, use:
`app.config['FLASK_ADMIN_SWATCH'] = 'cerulean'` and have a look at http://bootswatch.com/3/ for the available themes.

It would be great to have an example of a dashboard for monitoring / analytics. If you've implemented one, please contribute.
