### ISSUE TITLE
Instance folder and flask-admin - cannot make it work

### ISSUE THREAD

**Issue by litnimax** [flask-admin/flask-admin#976]
Hi!
I'd like to restructure my application to use instance folder for custom configurations.
So the only thing I do is putting app.run() one level higher:
- root_folder
- root_folder/run.py
- root_folder/myapp/
- root_folder/myapp/views.py
- root_folder/myapp/models.py
- root_folder/myapp/templates
- root_folder/myapp/templates/my_list.html

And this breaks paths to templates.
list_temlpate = 'my_list.html'
I this is searched in root_folder/templates, not in root_folder/myapp/templates, and I cannot overcome it as root_foldertemplates added before anything in list_template.

Can you pls advise?
Thanks.

**Comment by petrus-jvrensburg** [comment]
Closing this, but please re-open if it's still a problem.
