### ISSUE TITLE
Deleting broken with modelform

### ISSUE THREAD

**Issue by italomaia** [flask-admin/flask-admin#978]
I have a ModelAdminView which uses a form created with modelform, where the model is a sqlalchemy orm class with a few fields with nullable=false. When trying to delete a row with the delete icon (the trash bin), I get a error telling me which a few fields are required and, because of that, the row cannot be delete (weird verification for a delete operation). If I select the checkbox for that same row and click on "delete" from "with selected", I get to delete the row alright. I'm quite positive this is not a expected behavior. Anyone had this issue before?

**Comment by pawl** [comment]
Are you upgrading from an older version of flask-admin? Did you override the list template somehow? 

Are you doing something weird with the primary keys for that row?

Would be nice to see a gist of the problem.

**Comment by italomaia** [comment]
I'm not upgrading. I did not override the list template. Nothing weird is being done to the primary keys. I'll create a gist about it later today.

**Comment by boolbag** [comment]
I wonder if this is related to [this issue](https://github.com/flask-admin/flask-admin/issues/1004), for which I created a gist.
