### ISSUE TITLE
Redirecting to details page after create/edit

### ISSUE THREAD

**Issue by plaes** [flask-admin/flask-admin#985]
Now that Flask-Admin has details view, how could we utilize it to redirect the user to the details view after record has been created/edited?

Current behavior:
* Create new record, use [Save] button and user is redirected to 'Edit' page
* Edit record, use [Save] button, user is redirected to list view
* Edit record, use [Save and Continue], user is redirected back to Edit page

Unfortunately I haven't found a simple way to override these redirects.

**Comment by pawl** [comment]
I think this would require changing https://github.com/flask-admin/flask-admin/blob/master/flask_admin/model/base.py#L1670 (and the same line in edit_view) to something like:
```
else:
    # save button
    return self.get_save_return_url(model)
```

And adding a method to ModelView:
```
def get_save_return_url(self, model=None):
    '''
        Returns url used in the redirect after the user uses the save button. Override this
        method to return the user to the details_view instead.
    "'
    return get_redirect_target() or self.get_url('.index_view')
```
