### ISSUE TITLE
Extending @action functionality to respect filters

### ISSUE THREAD

**Issue by litnimax** [flask-admin/flask-admin#990]
Currently we can define an action for selected rows.
But what if we need actions for all rows?
Like "delete all", "export all".
I guess functionality  action "with selected" should be extended to return current filters.
In that case when we click on separate checkboxes (selecting them individually) action should get *ids* parameter  (as it does now).
But in case we select all records
```
<input type="checkbox" name="rowtoggle" class="action-rowtoggle" title="{{ _gettext('Select all records') }}" />
```
*ids* must be empty,  instead action should get the current filter set.
This will allow selecting all records according to filter not only those 20 records per page.

Any ideas?

**Comment by pawl** [comment]
There's a discussion about that here: https://github.com/flask-admin/flask-admin/issues/713
